- pom.xml
- src/main/scala/org/kframework/minikore/MiniToText.scala
- src/main/scala/org/kframework/minikore/MiniToTextToMini.scala
- src/main/scala/org/kframework/minikore/Scanner.scala
- src/main/scala/org/kframework/minikore/TextToMini.scala
- src/test/scala/org/kframework/minikore/TextToMiniTest.scala
@grosu please review. Addressed was your previous comments.
> Fix parser

- src/main/haskell/language-kore/src/Data/Kore/AST.hs
- src/main/haskell/language-kore/src/Data/Kore/Parser/CString.hs
- src/main/haskell/language-kore/src/Data/Kore/Parser/LexemeImpl.hs
- src/main/haskell/language-kore/src/Data/Kore/Parser/ParserImpl.hs
- src/main/haskell/language-kore/src/Data/Kore/Unparser/Unparse.hs
- src/main/haskell/language-kore/test/parser/AllParserTests.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/ASTGen.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/CStringTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/CharDictTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/CharSetTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/LexemeTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/ParserTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/ParserTestUtils.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Parser/RegressionTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/Unparser/UnparseTest.hs
@virgil-serbanuta please review
> Refactorings

- src/main/haskell/language-kore/package.yaml
> Link doesn't work. I think this is the intended file.

- src/main/haskell/language-kore/package.yaml
- src/main/haskell/language-kore/src/Data/Kore/ASTPrettyPrint.hs
- src/main/haskell/language-kore/src/Data/Kore/Implicit/ImplicitKore.hs
- src/main/haskell/language-kore/src/Data/Kore/MetaML/Lift.hs
- src/main/haskell/language-kore/src/Data/Kore/MetaML/UnLift.hs
- src/main/haskell/language-kore/src/Data/Kore/MetaML/Unlift.hs
- src/main/haskell/language-kore/test/parser/AllParserTests.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/ASTVerifier/DefinitionVerifierUniqueNamesTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/MetaML/ASTGen.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/MetaML/LiftTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/MetaML/LiftUnliftTest.hs
- src/main/haskell/language-kore/test/parser/Data/Kore/MetaML/UnliftTest.hs
- src/main/haskell/language-kore/test/parser/Test/Tasty/HUnit/Extensions.hs
Increased coverage for lift and unlift.  Tested that unlift is an inverse of lift.
> Lift unlift

- src/main/haskell/matching-logic/src/Kore/MatchingLogic/AST.hs
- src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProofSystem/Minimal.hs
Also added some compilation annotations, as `stylish-haskell` does not seem to be reading project setup info.
> Fixing Haddock errors

- src/main/haskell/language-kore/src/Data/Kore/Implicit/Attributes.hs
- src/main/kore/attributes.kore
- src/test/expected/attributes.kore.golden
Small update, added the smtlib attribute and abstracted a function (as smtlib and hook attributes are almost identical)  I can continue to add more attributes if this was the correct way to do it.
> add smtlib attribute; update golden

- docs/prover_repl.md
- src/main/haskell/matching-logic/src/Kore/MatchingLogic/ProverRepl.hs
This PR adds a couple of new/improved commands for the prover REPL. 
It also adds a new documentation file for the REPL, where those new commands are described.
> New prover REPL commands and docs

- docs/proof_object.md
Note this only touches documentation, code should not be affected.
> Document plan for Object-level/Mixed-level proofs

- src/main/haskell/kore/src/Data/Graph/TopologicalSort.hs
- src/main/haskell/kore/src/Kore/AST/PureML.hs
- src/main/haskell/kore/src/Kore/ASTVerifier/AttributesVerifier.hs
- src/main/haskell/kore/src/Kore/Step/Error.hs
- src/main/haskell/kore/src/Kore/Unification/Error.hs
- src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
- src/main/haskell/kore/test/Test/Tasty/HUnit/Extensions.hs
> Fix broken documentation markers

- src/main/haskell/kore/src/Kore/ASTPrettyPrint.hs
- src/main/haskell/kore/src/Kore/ASTUtils/SmartPatterns.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/PatternAttributes.hs
- src/main/haskell/kore/src/Kore/Step/PatternAttributesError.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Iff.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Implies.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/In.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Not.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Or.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
- src/main/haskell/kore/src/Kore/Step/StepperAttributes.hs
- src/main/haskell/kore/src/Kore/Unification/Unifier.hs
- src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
- src/main/haskell/kore/test/Test/Kore/Comparators.hs
- src/main/haskell/kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/PatternAttributes.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/test/Test/Kore/Step/Step.hs
- src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs
> Equals simplification improvements + test

- design-decisions/2018-09-03-Owise-encoding.md
> Owise encoding decision.

- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
Also, test all the things in Equals.hs that I care to test.
---
> Fix equality for functions.

- src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
> Fix ceil for constructors

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/Predicate/Predicate.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Exists.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/ExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Simplifier.hs
- src/main/haskell/kore/src/Kore/Step/Step.hs
- src/main/haskell/kore/src/Kore/Substitution/List.hs
- src/main/haskell/kore/src/Kore/Unification/SubstitutionNormalization.hs
- src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Exists.hs
> Simplify Exists

- src/main/haskell/kore/src/Kore/Step/PatternAttributes.hs
- src/main/haskell/kore/src/Kore/Step/PatternAttributesError.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/src/Kore/Step/StepperAttributes.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
> Ceil for total patterns

- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
> Integration test for owise

- src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Bottom.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/CharLiteral.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/DomainValue.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Exists.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Floor.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Forall.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Iff.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Implies.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/In.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Next.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Not.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Or.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Rewrites.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/StringLiteral.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Top.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Variable.hs
> Rename package in documentation

- src/main/haskell/kore/app/exec/Main.hs
> Added --output option to kore-exec

- design-decisions/0000-00-00-Template.md
- design-decisions/2018-09-20-Decision-Template.md
> Design decision template

- design-decisions/2018-09-18-Substitution-Predicate-Top-Evaluation.md
> Predicate evaluation at the top of the formula.

- docs/hooks.md
- src/main/haskell/kore/src/Kore/AST/Common.hs
- src/main/haskell/kore/src/Kore/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/src/Kore/Builtin/List.hs
- src/main/haskell/kore/src/Kore/Unparser.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Bool.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/KEqual.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/List.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
This pull request will add the LIST builtins needed for EVM. Documentation is also added for INT builtins.
---
> Add LIST builtins

- src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/PredicateSubstitution.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/src/Kore/Unification/SubstitutionNormalization.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Bottom.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Exists.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Floor.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Forall.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Top.hs
- src/main/haskell/kore/test/Test/Kore/Step/Substitution.hs
> Extract PredicateSubstitution to its own file.

- src/main/haskell/kore/src/Kore/AST/Sentence.hs
- src/main/haskell/kore/src/Kore/ASTVerifier/AttributesVerifier.hs
- src/main/haskell/kore/src/Kore/ASTVerifier/SentenceVerifier.hs
- src/main/haskell/kore/src/Kore/Builtin/Hook.hs
- src/main/haskell/kore/src/Kore/IndexedModule/Resolvers.hs
- src/main/haskell/kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
- src/test/resources/expected/test-attribute-1.kore.golden
- src/test/resources/expected/test-attribute-2.kore.golden
- src/test/resources/expected/test-hooks-8.kore.golden
- src/test/resources/expected/test-hooks-9.kore.golden
- src/test/resources/test-attribute-1.kore
- src/test/resources/test-attribute-2.kore
- src/test/resources/test-hooks-8.kore
- src/test/resources/test-hooks-9.kore
This pull request implements verification for hook attributes according to the design document added in #233.
---
> Verify hook attributes

- docs/hooks.md
- src/main/haskell/kore/src/Kore/AST/Common.hs
- src/main/haskell/kore/src/Kore/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Set.hs
- src/main/haskell/kore/src/Kore/Unparser.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
> Add SET builtins

- docs/hooks.md
- src/main/haskell/kore/package.yaml
- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
> Implement pow, powmod, and log2 for builtin Int

- docs/hooks.md
- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
> Builtin Int bitwise operations

- src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
> Kore.Step.Condition.Evaluator: Remove Debug.Trace

- src/main/haskell/kore/src/Data/Result.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs-boot
- src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
- src/main/haskell/kore/test/Test/Data/Result.hs
FunctionResult is factored out of Kore.Step.Simplification.AndTerms and
generalized in Data.Result to encompass success, failure, and
indeterminacy. Tests are added for the various instances.
---
> Add Data.Result

- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs
> Making inj-constructor fail

- src/main/haskell/kore/Makefile
- src/main/haskell/kore/src/Kore/SMT/SMT.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs
- src/main/k/working/function-evaluation-demo/tests/Nat.output.golden
- src/main/k/working/function-evaluation-demo/tests/NatList.output.golden
- src/main/k/working/function-evaluation-demo/tests/Truth.output.golden
- src/main/k/working/imp-concrete-heat-cool/tests/collatz.output.golden
- src/main/k/working/imp-concrete-heat-cool/tests/primes.output.golden
- src/main/k/working/imp-concrete-heat-cool/tests/sum.output.golden
- src/main/k/working/imp-monosorted/tests/collatz.output.golden
- src/main/k/working/imp-monosorted/tests/primes.output.golden
- src/main/k/working/imp-monosorted/tests/sum.output.golden
> Fix integration tests

- src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
> Simplifying predicates before sending them to the SMT

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/Builtin/Bool.hs
- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/src/Kore/SMT/Config.hs
- src/main/haskell/kore/src/Kore/SMT/SMT.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Data.hs
- src/main/haskell/kore/test/Test/Kore/SMT/SMT.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Condition/Evaluator.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
> Smt improvements

- .gitignore
- .gitmodules
- Makefile
- src/main/k/working/Makefile
- src/main/k/working/function-evaluation-demo/Makefile
- src/main/k/working/imp-concrete-heat-cool/Makefile
- src/main/k/working/imp-monosorted/Makefile
> Added K as a submodule and created Makefiles

- src/main/haskell/kore/Makefile
- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/Predicate/Predicate.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/src/Kore/Step/PredicateSubstitution.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/test/Test/Kore/Predicate/Predicate.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
> Use matching instead of unification for axiomFunctionEvaluator

- src/main/haskell/kore/src/Kore/Builtin/List.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/src/Kore/Step/Substitution.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
> Unify builtin lists

- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/src/Kore/Builtin/List.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/src/Kore/Builtin/Set.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
> Apply unit laws to builtin functions

- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/RecursiveAttributes.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
> faster replacements for isFunctional,Function,TotalPattern

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
> Updated K to latest master

- src/main/haskell/kore/src/Kore/Predicate/Predicate.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
Fixes the issues noticed in the post-review of #272.
---
> Minor refactoring and styling fixes

- stack.yaml
> Updated to lts-12.14

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/IndexedModule/MetadataTools.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/IndexedModule/MetadataTools.hs
- src/main/haskell/kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Step/Step.hs
- src/main/haskell/kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
- src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs
- src/main/k/working/imp-concrete-heat-cool/Makefile
- src/main/k/working/imp-concrete-heat-cool/tests/max-symbolic.imp
- src/main/k/working/imp-concrete-heat-cool/tests/max-symbolic.output.golden
- src/main/k/working/imp-concrete-state/Makefile
- src/main/k/working/imp-concrete-state/tests/max-symbolic.imp
- src/main/k/working/imp-concrete-state/tests/max-symbolic.output.golden
- src/main/k/working/imp-monosorted/Makefile
- src/main/k/working/imp-monosorted/tests/max-symbolic.imp
- src/main/k/working/imp-monosorted/tests/max-symbolic.output.golden
> Symbolic execution fix

- src/main/haskell/kore/src/Kore/Builtin/List.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
> Unify return concrete

- src/main/haskell/kore/src/Kore/Builtin/String.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/String.hs
> Removed readSigned from parsing Hex and Octal.

- src/main/haskell/kore/src/Kore/ASTUtils/AlphaCompare.hs
- src/main/haskell/kore/src/Kore/ASTUtils/SmartPatterns.hs
- src/main/haskell/kore/test/Test/Kore.hs
- src/main/haskell/kore/test/Test/Kore/ASTUtils.hs
- src/main/haskell/kore/test/Test/Kore/ASTUtils/AlphaCompare.hs
May not be what we need for merging branches, but still a very basic feature which should probably exist for other purposes...
Also, extended the generator in Test.Kore to use previously bound variables.
---
> Compare mod alpha

- docs/2018-11-12-Unification.md
- docs/glossary.md
> Unification design document

- design-decisions/2018-11-14-Heating-Cooling-Representation.md
I would like to get some feedback on this. Is this the right thing to do? Did I miss anything?
If this is, indeed, the right thing to do, I would also like to merge this PR.
---
> Heating and cooling rule representation.

- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/src/Kore/Step/Step.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Definition.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
- src/main/haskell/kore/test/Test/Kore/Comparators.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/python/debugFilter.py
> Split the configuration in the stepper.

- docs/2018-11-08-One-Path-Reachability-Proofs.md
- src/main/haskell/kore/src/Kore/AST/MLPatterns.hs
> Remove outdated TODO and fix line length

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/bench/exec/Main.hs
- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/Exec.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/src/Kore/Step/Step.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
- src/main/haskell/kore/test/Test/Kore/Exec.hs
- src/main/haskell/kore/test/Test/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Step.hs
> Split and rename AxiomPattern

- src/main/haskell/kore/Makefile
- src/main/haskell/kore/src/Kore/AST/Error.hs
- src/main/haskell/kore/src/Kore/AST/PureToKore.hs
- src/main/haskell/kore/src/Kore/AST/Sentence.hs
- src/main/haskell/kore/src/Kore/ASTPrettyPrint.hs
- src/main/haskell/kore/src/Kore/ASTVerifier/SentenceVerifier.hs
- src/main/haskell/kore/src/Kore/IndexedModule/IndexedModule.hs
- src/main/haskell/kore/src/Kore/MetaML/Lift.hs
- src/main/haskell/kore/src/Kore/Parser/ParserImpl.hs
- src/main/haskell/kore/src/Kore/Unparser.hs
- src/main/haskell/kore/test/Test/Kore/Parser/Parser.hs
> Added claims

- src/main/haskell/kore/src/Kore/OnePath/Verification.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Verification.hs
> One-path verification

- src/main/haskell/kore/test/Test/Kore/OnePath/Verification.hs
> Add a comment I forgot.

- include.mk
- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/ASTVerifier/DefinitionVerifier.hs
- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/src/Kore/Exec.hs
- src/main/haskell/kore/src/Kore/IndexedModule/IndexedModule.hs
- src/main/haskell/kore/src/Kore/OnePath/Step.hs
- src/main/haskell/kore/src/Kore/OnePath/Verification.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Function/Data.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/PredicateSubstitution.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Step.hs
- src/main/k/working/imp/Makefile
- src/main/k/working/imp/prove/addspec.k
- src/main/k/working/imp/prove/maxspec.k
- src/main/k/working/imp/tests/sum-spec.k
- src/main/python/debugFilter.py
Still need to wait for https://github.com/kframework/k/pull/205 to be integrated in `K` before merging.
---
> Added basic kprove functionality

- src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Step.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
> And idempotence

- src/main/haskell/kore/src/Kore/Debug.hs
> Added conditional debug functions

- src/main/python/debugFilter.py
- src/main/python/debugger.py
> Update the debugger filter. Add an interactive debugging tool.

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/SMT.hs
> added --smt-prelude command line option

- src/main/k/working/tests/collections/list-map-unify-concrete/Makefile
- src/main/k/working/tests/collections/list-map-unify-concrete/list-map-unify-concrete.k
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/1.list-map-unify-concrete
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/1.output.golden
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/2.list-map-unify-concrete
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/2.output.golden
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/3.list-map-unify-concrete
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/3.output.golden
> updated K submodule

- src/main/python/debugFilter.py
- src/main/python/debugger.py
> Improved debug filter and debugger

- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/Step/StepperAttributes.hs
- src/main/haskell/kore/src/Kore/Unification/SubstitutionNormalization.hs
- src/main/haskell/kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
> Better cycle detection for substitution

- src/main/haskell/kore/bench/exec/Main.hs
Previously, we called `kast --kore` to get the kore pattern to give to
`kore-exec`, but this was producing the wrong pattern, so the benchmarks
were executing way faster than they should have.
---
> Fix concrete execution benchmarks

- src/main/haskell/kore/src/Kore/OnePath/Step.hs
- src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
- src/main/haskell/kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Step.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Verification.hs
- src/main/haskell/kore/test/Test/Kore/Proof/Value.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/PatternAttributes.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/And.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/DomainValue.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Exists.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
- src/main/haskell/kore/test/Test/Kore/Step/Substitution.hs
- src/main/haskell/kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
> Reminder simplification for one-step (author: vladciobanu)

- src/main/haskell/kore/src/Kore/Builtin/String.hs
> implement STRING.chr builtin

- src/main/haskell/kore/src/Kore/Builtin/Int.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
> Fail when hooks don't simplify concrete patterns.

- src/main/haskell/kore/src/Kore/AST/Common.hs
- src/main/haskell/kore/src/Kore/AST/Kore.hs
- src/main/haskell/kore/src/Template/Tools.hs
> Extract TH section splitting to a function

- src/main/python/debugFilter.py
> Update the debug tools

- src/main/haskell/kore/app/exec/Main.hs
> put back deleted lines

- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
> Test.Kore.Step.MockSymbols: De-duplicate builtin Bool, Int constructors

- src/main/haskell/kore/src/Kore/Builtin/Set.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
> Fix framing variable unification test

- docs/2018-11-08-One-Path-Reachability-Proofs.md
> New notation for weak eventually and notation erata

- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/ExpandedPattern.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
> Reevaluate duplicate function results only once.

- docs/2018-12-21-Function-Evaluation.md
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
> Function evaluation design

- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/test/Test/Kore/Exec.hs
- src/main/haskell/kore/test/Test/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
See also: kframework/k#241
Trello: https://trello.com/c/GmxON75i
---
> AxiomPatterns: Fix the form of rewrite rules

- design-decisions/2019-01-14-Function-Evaluation-Simplification.md
- src/main/haskell/kore/src/Kore/Builtin/Attributes.hs
- src/main/haskell/kore/src/Kore/Builtin/List.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/src/Kore/Builtin/Set.hs
- src/main/haskell/kore/src/Kore/Proof/Functional.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/PatternAttributes.hs
- src/main/haskell/kore/src/Kore/Step/PatternAttributesError.hs
- src/main/haskell/kore/src/Kore/Step/StepperAttributes.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/List.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
- src/main/haskell/kore/test/Test/Kore/Comparators.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/PatternAttributes.hs
> Sanity checks for function evaluation.

- src/main/haskell/kore/package.yaml
- src/main/haskell/kore/src/Kore/Attribute/Simplification.hs
- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/src/Kore/Step/Function/Data.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Attribute/Simplification.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
> Separate simplification axiom evaluation

- src/main/haskell/kore/src/Kore/Builtin/Bool.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Bool.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Definition.hs
> Implement BOOL.andThen and BOOL.orElse hooks

- docs/2018-12-21-Function-Evaluation.md
> Improve function evaluation design wording.

- src/main/haskell/kore/package.yaml
- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/OnePath/Step.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Function/Data.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
- src/main/haskell/kore/src/Kore/Step/Step.hs
- src/main/haskell/kore/src/Kore/Step/Substitution.hs
- src/main/haskell/kore/src/Kore/Unification/Procedure.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/test/Test/Kore/Comparators.hs
- src/main/haskell/kore/test/Test/Kore/OnePath/Step.hs
- src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
> Function evaluation with remainders and unification

- src/main/haskell/kore/app/exec/Main.hs
- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/OnePath/Step.hs
- src/main/haskell/kore/src/Kore/Step/BaseStep.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/python/debugger.py
> Permanent debugger instrumentation

- src/main/haskell/kore/app/exec/Main.hs
I'll merge without waiting for approvals if feasible.
---
> Remove debugging instrumentation.

- Makefile
> change mkdir --parent to mkdir -p

- Jenkinsfile
> generate test results to display on jenkins

- src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/src/Kore/Builtin/Krypto.hs
- src/main/haskell/kore/src/Kore/Builtin/Map.hs
- src/main/haskell/kore/src/Kore/Builtin/Set.hs
- src/main/haskell/kore/src/Kore/Builtin/String.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Definition.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Krypto.hs
Duplicate PR because the old one got closed accidentally.
---
> Implemented KRYPTO.ecdsaRecover hook

- src/main/haskell/kore/src/Kore/AST/Common.hs
- src/main/haskell/kore/src/Kore/Exec.hs
- src/main/haskell/kore/src/Kore/Step/Function/Data.hs
- src/main/haskell/kore/src/Kore/Step/Function/EvaluationStrategy.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Simplifier.hs
- src/main/haskell/kore/test/Test/Kore/AST/Common.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/EvaluationStrategy.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
- src/main/haskell/kore/test/Test/Tasty/HUnit/Extensions.hs
I left a TODO about moving some functions to the new EvaluationStrategy.hs file, I plan to move them in a follow-up PR.
---
> Decide how to evaluate symbols when the program starts.

- src/main/haskell/kore/src/Kore/Step/Function/EvaluationStrategy.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/EvaluationStrategy.hs
> Refactoring: Move functions from Evaluator to EvaluationStrategy

- src/main/haskell/kore/src/Kore/Builtin.hs
- src/main/haskell/kore/src/Kore/Debug.hs
- src/main/haskell/kore/src/Kore/Exec.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/src/Kore/Step/Function/Data.hs
- src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
- src/main/haskell/kore/src/Kore/Step/Function/Identifier.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
- src/main/haskell/kore/src/Kore/Step/Simplification/Simplifier.hs
- src/main/haskell/kore/test/Test/Kore/Comparators.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Identifier.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
- src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
> Generalize axiom simplification to prepare for ceil axioms.

- Makefile
- include.mk
- src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
This pull request will initially fail, to check the builder.
---
> Makefile: Build with --pedantic

- src/main/haskell/kore/src/Kore/Builtin/Krypto.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Definition.hs
- src/main/haskell/kore/test/Test/Kore/Builtin/Krypto.hs
> Fixed a bug in ECDSA recover, added unit test for Keccak

- src/main/haskell/kore/src/Kore/Attribute/Overload.hs
- src/main/haskell/kore/src/Kore/Attribute/Parser.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
- src/main/haskell/kore/test/Test/Kore/Attribute/Overload.hs
@ehildenb This pull request would fix the first bug we found with KWASM today.
---
> Ignore overload axioms

- src/main/haskell/kore/src/SimpleSMT.hs
> Removed leftover Debug.Trace

- src/main/haskell/kore/src/Kore/Attribute/Label.hs
- src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
- src/main/haskell/kore/test/Test/Kore/Attribute/Label.hs
> Label attribute

- design-decisions/2018-10-24-And-Not-Exists-Simplification.md
> Fix design decision references.

- include.mk
- kore/src/Kore/Debug.hs
- kore/src/Kore/OnePath/Verification.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/BaseStep.hs
- src/main/k/working/imp/Makefile
- src/main/k/working/imp/prove/sum-div-spec.k
- src/main/python/debugger.py
> Ceil integration

- kore/src/Kore/Repl.hs
> repl: better indication of the current node

- kore/src/Kore/Repl.hs
> repl: removed unused parameter

- kore/src/Kore/Repl.hs
> config optional argument

- kore/src/Kore/Exec.hs
- kore/src/Kore/OnePath/Verification.hs
- kore/src/Kore/Step/AxiomPatterns.hs
- kore/src/Kore/Step/BaseStep.hs
- kore/test/Test/Kore/Builtin/Map.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/OnePath/Step.hs
- kore/test/Test/Kore/OnePath/Verification.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Axiom/UserDefined.hs
- kore/test/Test/Kore/Step/AxiomPatterns.hs
- kore/test/Test/Kore/Step/BaseStep.hs
- kore/test/Test/Kore/Step/Function/Integration.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
- kore/test/Test/Kore/Step/Step.hs
- src/main/k/working/imp/prove/max-spec.k
> Add ensures to axiom patterns

- design-decisions/2019-03-20-Ensures-for-Axioms.md
> Design decision for 'ensures' clauses in rewrite axioms.

- kore/app/exec/Main.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Condition/Evaluator.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/Kore/Step/SMT/Lemma.hs
- kore/src/Kore/Step/SMT/Translate.hs
- kore/test/Test/Kore/Step/Condition/Evaluator.hs
Also some indentation changes in kore/app/exec/Main.hs and an error message change in kore/src/Kore/Step/Axiom/EvaluationStrategy.hs.
---
> Move SMT handling to its own directory

- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> show unevaluated or stuck leafs

- include.mk
PR generated by './scripts/update-k-nightly-pr.sh'
> Update K Nightly version used for integration testing

- Jenkinsfile
- scripts/kevm-integration.sh
---
Should we keep the revert or not?
> Testing Strategy: Kevm integration tests

- kore/src/Kore/Repl/Interpreter.hs
> repl: step skips evaluated nodes

- Jenkinsfile
---
This should enable sending emails on failed jobs to `master` or `[kevm-integration]` tagged commits.
> Jenkinsfile: post-build action which sends a slack notification

- scripts/kevm-integration.sh
> Use the same K for all integration tests

- kore/src/Kore/Repl/Interpreter.hs
> repl: fix step

- kore/test/Test/Kore/Repl/Parser.hs
> repl: rule command test

- kore/src/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Builtin/Set.hs
> unify select with empty set

- kore/src/Kore/Attribute/Axiom.hs
- kore/src/Kore/Attribute/RuleIndex.hs
- kore/src/Kore/OnePath/Verification.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> repl: add index attribute + print index in showRule + bug fix in try

- kore/src/Kore/Logger.hs
- kore/src/Kore/Step/Simplification/Data.hs
> Add Kore.Logger.WithLog

- kore/src/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Builtin/Set.hs
> Set unification 2

- kore/src/Kore/Repl/Interpreter.hs
> repl: try axiom workaround for branchings

- kore/src/Kore/Exec.hs
- kore/src/Kore/OnePath/Verification.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/OnePath/Verification.hs
> claim attributes

- kore/src/Kore/Repl/Interpreter.hs
> Remove unneeded haddock comment to fix make docs

- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Repl/Interpreter.hs
> Fix one of the comments in https://github.com/kframework/kore/pull/528

- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Step/Axiom/UserDefined.hs
- kore/src/Kore/Step/Remainder.hs
- kore/src/Kore/Step/Representation/MultiOr.hs
- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Step.hs
> Fix some of the unanswered comments in #524

- kore/src/Kore/OnePath/Step.hs
> Fix unanswered comment from #526

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> repl: annotate edges of graph with index of axiom/claim

- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
Added a clear command and fixed a bug with `addIndexesToAxioms`.
---
> Repl clear

- kore/src/Kore/Builtin/Set.hs
> Fixed pending comments from https://github.com/kframework/kore/pull/573/

- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> Fixed a bug in the omit parser and improved output for showLeafs.

- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Variables/Fresh.hs
- kore/src/Kore/Variables/Target.hs
Extract a general utility from `Kore.Step.Rule.refreshRulePattern`.
---
> Extract Kore.Variables.Fresh.refreshVariables

- include.mk
- kore/src/Kore/Exec.hs
- kore/src/Kore/OnePath/Verification.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Step/Axiom/Registry.hs
- kore/src/Kore/Step/Rule.hs
- kore/test/Test/Kore/OnePath/Verification.hs
> Parameterized Repl and Prover on claims. Added OnePath and AllPath claims

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Unification/Unify.hs
> Repl first failed unification

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Predicate/Predicate.hs
- kore/src/Kore/Step/Pattern.hs
- kore/src/Kore/Step/Representation/ExpandedPattern.hs
- kore/src/Kore/Step/Representation/PredicateSubstitution.hs
- kore/src/Kore/Step/Representation/Predicated.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Step/Substitution.hs
- kore/src/Kore/Unification/Substitution.hs
- kore/src/Kore/Unification/SubstitutionNormalization.hs
- kore/test/Test/Kore/Step/Simplification/Exists.hs
- kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
- kore/test/Test/Kore/Step/Substitution.hs
- kore/test/Test/Kore/Unification/Substitution.hs
- kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
> Simplify \exists with bound substitutions

- kore/package.yaml
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: pipe command

- kore/src/Kore/AST/AstWithLocation.hs
- kore/src/Kore/AST/Common.hs
- kore/src/Kore/AST/Lens.hs
- kore/src/Kore/AST/MLPatterns.hs
- kore/src/Kore/AST/Valid.hs
- kore/src/Kore/ASTPrettyPrint.hs
- kore/src/Kore/ASTVerifier/PatternVerifier.hs
- kore/src/Kore/Parser/ParserImpl.hs
- kore/src/Kore/Step/SMT/Translate.hs
- kore/src/Kore/Step/Simplification/Pattern.hs
- kore/src/Kore/Step/Simplification/SetVariable.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Parser/Parser.hs
> Added Set Variables (take 2)

- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Step.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Axiom/UserDefined.hs
- kore/src/Kore/Step/Result.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Step/Simplification/And.hs
- kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
- kore/test/Test/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Substitution.hs
> Distinguish \bottom unifier and \bottom result

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: append command output to file

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> Repl interpretor refactor / cleanup

- kore/app/exec/Main.hs
> kore-exec: Remove stray print

- kore/src/Kore/AST/Common.hs
- kore/src/Kore/AST/Identifier.hs
- kore/src/Kore/Sort.hs
> Remove unparseLowerID

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: save graph image

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> repl: try bug fix

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs-boot
- kore/src/Kore/Step/Step.hs
- kore/src/Kore/Step/Substitution.hs
- kore/src/Kore/Step/Substitution.hs-boot
- kore/src/Kore/Unification/Error.hs
- kore/src/Kore/Unification/Procedure.hs
- kore/src/Kore/Unification/SubstitutionNormalization.hs
- kore/src/Kore/Unification/UnifierImpl.hs
- kore/src/Kore/Unification/Unify.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
- kore/test/Test/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Substitution.hs
- kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Remove variable parameter from SubstitutionError

- kore/src/Kore/ASTPrettyPrint.hs
- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Step/Axiom/Data.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Merging/OrPattern.hs
- kore/src/Kore/Step/Merging/Pattern.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Step/Simplification/Predicate.hs
- kore/src/Kore/Step/Substitution.hs
- kore/src/Kore/Step/Substitution.hs-boot
- kore/src/Kore/Unification/Substitution.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Simplifier.hs
Postpone normalizing in some cases where we cannot handle multiple results.
Depends on: #615
---
> Postpone normalizing in some cases

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
> Added basic tests for the REPL Interpreter.

- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
@vladciobanu This pull request fixes the simplifiers to remove the trap I accidentally laid.
---
> Test.Kore.Builtin.Builtin: Use reasonable simplifiers

- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Simplification/AndTerms: better error message

- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> REPL / Aliases with no arguments

- kore/app/repl/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: init script file

- Jenkinsfile
> Jenkinsfile: update bad color used for failure messages to Slack

- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: load script command

- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Unification/Error.hs
- kore/test/Test/Kore/Builtin/Map.hs
> Selecting from empty and singleton maps

- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
> Set lookup branching

- kore/app/repl/Main.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Unification/Error.hs
- kore/test/Test/Kore/Builtin/Map.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Map lookup branching

- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Unification/Error.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
> Map and Set unification without `withoutTerm`.

- kore/src/Kore/Unification/Procedure.hs
> Explain sort mismatch

- scripts/kevm-integration.sh
---
More changes to EVM semantics which led to needing a more specific target.
> scripts/kevm-interaction: update target name

- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Unification/Substitution.hs
- kore/test/Test/Kore/Step/Simplification/Exists.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
- kore/test/Test/Kore/Unification/Substitution.hs
> exists x. y=x simplification

- kore/src/Kore/Step.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Unification/Error.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Substitution.hs
- kore/test/Test/Kore/Unification/Unifier.hs
Debugging code I wrote for investigating the regression-new failures.
---
> More details for unification errors.

- kore/test/Test/Kore/Step/Simplification/Integration.hs
> Exists simplification - fix review comments

- kore/src/Kore/AST/AstWithLocation.hs
- kore/src/Kore/AST/Common.hs
- kore/src/Kore/ASTVerifier/PatternVerifier.hs
- kore/src/Kore/Builtin.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Parser/Lexeme.hs
- kore/src/Kore/Parser/Parser.hs
- kore/src/Kore/Step/SMT/Translate.hs
- kore/src/Kore/Step/Simplification/Mu.hs
- kore/src/Kore/Step/Simplification/Nu.hs
- kore/src/Kore/Step/Simplification/SetVariable.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Syntax.hs
- kore/src/Kore/Syntax/Mu.hs
- kore/src/Kore/Syntax/Nu.hs
- kore/src/Kore/Syntax/PatternF.hs
- kore/test/Test/Kore/ASTVerifier/DefinitionVerifier.hs
- kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Parser/Parser.hs
> Added Mu and Nu

- kore/app/repl/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
> repl: run script mode

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> repl: graph file extension

- kore/src/Kore/Step/Simplification/Exists.hs
- kore/test/Test/Kore/Step/Simplification/Exists.hs
> exists x . f(x)=f(a)

- kore/src/Kore/Repl/Data.hs
> helpText: Add missing newline

- kore/src/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/k/working/tests/collections/set-unify-framing-variable/set-unify-framing-variable.k
> Set idempotence

- docs/2019-05-23-Unification-Modulo-Equations.md
> Unification modulo equations proposal

- src/main/k/working/imp/prove/max-spec.k
- src/main/k/working/imp/prove/sum-div-spec.k
- src/main/k/working/imp/prove/unreachable-spec.k
This is some clean-up and an extra specification I wrote for my demo.
---
> IMP: Clean-up and extra specifications

- stack.yaml
> LTS Haskell 13.22

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> repl: cmd to show current claim

- include.mk
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/1.output.golden
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/2.output.golden
- src/main/k/working/tests/collections/list-map-unify-concrete/tests/3.output.golden
PR generated by './update-deps/update-deps'
> Update submodule dependencies

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> [REPL] Add 'tryf' command

- scripts/kevm-integration.sh
> scripts/kevm-integration.sh: Updated .build/k to deps/k

- kore/src/SMT/SimpleSMT.hs
> Log SMT models

- kore/src/Kore/ASTVerifier/PatternVerifier.hs
- kore/src/Kore/ASTVerifier/SentenceVerifier.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Step.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Unification/Procedure.hs
- kore/src/SMT.hs
> Style guide fixes.

- kore/src/Kore/Builtin/Builtin.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Debug.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/src/Kore/IndexedModule/MetadataTools.hs
- kore/src/Kore/IndexedModule/Resolvers.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Parser.hs
- kore/src/Kore/Unification/Unify.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
- kore/test/Test/Kore/Step.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Set concat unification

- kore/src/Kore/Attribute/Pattern/Defined.hs
- kore/src/Kore/Attribute/Pattern/Functional.hs
- kore/src/Kore/Builtin/Builtin.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/Builtin.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Ceil.hs-boot
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/Not.hs
- kore/test/Test/Kore/Attribute/Pattern/Defined.hs
- kore/test/Test/Kore/Attribute/Pattern/Functional.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Unification/Unifier.hs
- kore/test/Test/Kore/With.hs
> Use NormalizedSet as the internal set representation

- kore/src/Kore/Domain/Builtin.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Proof/Value.hs
> Delete some unneeded Eq1/Show1/Ord1 instances.

- kore/src/Kore/Attribute/Pattern/Defined.hs
- kore/src/Kore/Attribute/Pattern/Functional.hs
- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Builtin/Attributes.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/MapSymbols.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Builtin/SetSymbols.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/test/Test/Kore/Attribute/Pattern/Defined.hs
- kore/test/Test/Kore/Attribute/Pattern/Functional.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Map.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Simplification/Builtin.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
- kore/test/Test/Kore/With.hs
> Map normalization

- kore/src/Kore/Builtin/AssociativeCommutative.hs
> Refactor AC unification

- include.mk
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
> Addressed review comments.

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Step/Rule.hs
> address review comments

- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/Builtin.hs
All comments except the one about functor/foldable instances should be fixed. I asked a question about that in the review thread for #770 
---
> Fix review request for PR 770, Map normalization

- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
> Fix AC unification loop

- kore/app/exec/Main.hs
- kore/app/parser/Main.hs
- kore/app/repl/Main.hs
- kore/app/share/GlobalMain.hs
Fixes https://github.com/kframework/kore/issues/720
> Print timing info to the log

- Makefile
- include.mk
- src/main/k/in-progress/all-path/00-basic/00-no-rules/Makefile
- src/main/k/in-progress/all-path/00-basic/01-one-rule/Makefile
- src/main/k/in-progress/all-path/00-basic/02-cyclic-rule/Makefile
- src/main/k/in-progress/all-path/00-basic/03-concurrent-rules/Makefile
- src/main/k/in-progress/all-path/00-basic/04-different-length/Makefile
- src/main/k/in-progress/all-path/02-constructors/00-case-analysis/Makefile
- src/main/k/in-progress/all-path/03-unification/set-select/Makefile
- src/main/k/in-progress/all-path/limitations/interfering-specs/Makefile
- src/main/k/working/include.mk
> Faster Makefile invocation

- kore/src/Kore/Exec.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Step/Simplification/Rule.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Simplification/Rule.hs
> Extract and test simplifyRulePattern

- kore/src/Kore/Attribute/Pattern.hs
This pull request implements a cleanup suggested by @virgil-serbanuta.
---
> Remove ambiguous field accessor

- scripts/install-stack.sh
- stack.yaml
- stack.yaml.lock
> Update LTS Haskell and Stack

- kore/src/Kore/ModelChecker/Simplification.hs
- kore/src/Kore/ModelChecker/Step.hs
- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Step.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Axiom/UserDefined.hs
- kore/src/Kore/Step/Condition/Evaluator.hs
- kore/src/Kore/Step/Merging/Pattern.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/Kore/Step/Search.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
- kore/src/Kore/Step/Simplification/Pattern.hs
- kore/src/Kore/Step/Simplification/Predicate.hs
- kore/test/Test/Kore/OnePath/Step.hs
- kore/test/Test/Kore/Step.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Axiom/UserDefined.hs
- kore/test/Test/Kore/Step/Condition/Evaluator.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/SMT/Evaluator.hs
- kore/test/Test/Kore/Step/Simplification/Application.hs
> Separate SMT evaluation

- docs/2019-07-25-Using-Configuration-Predicates.md
> Using configuration predicates

- kore/src/Kore/ModelChecker/Simplification.hs
- kore/src/Kore/ModelChecker/Step.hs
- kore/src/Kore/OnePath/Step.hs
- kore/src/Kore/Step.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
- kore/test/Test/Kore/Step/Simplification/OrPattern.hs
> Add ceils to predicates before SMT

- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Axiom/UserDefined.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
> Use the concrete attribute for function definitions

- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/test/Test/Kore/Step/Function/Evaluator.hs
> Warn about missing hooks

- scripts/should-run-kevm-integration.sh
> should-run-kevm-integration.sh: Only check head of pull request

- kore/src/Kore/Builtin.hs
- kore/src/Kore/Internal/MultiAnd.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Axiom/UserDefined.hs
- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Map.hs
- kore/test/Test/Kore/Builtin/Set.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
- kore/test/Test/Kore/Step/Axiom/UserDefined.hs
- kore/test/Test/Kore/Step/Function/Integration.hs
- kore/test/Test/Kore/Step/Step.hs
> Incremental matching

- docs/hooks.md
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/MapSymbols.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Map.hs
> implement MAP.size (hooks)

- kore/src/Kore/Step/Axiom/Identifier.hs
- kore/src/Kore/Step/Axiom/Registry.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Axiom/Identifier.hs
> Add AxiomIdentifier cases for \exists and \equals

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
I was waiting on tests to run, so I decided to delete some boilerplate.
---
> Clean up Kore.Step.Simplification.AndTerms

- deps/k_release
> Updated K nightly to version with set vars

- docs/hooks.md
- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Builtin/SetSymbols.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Set.hs
> implement list2set hook

- kore/app/profiler/Main.hs
- kore/package.yaml
- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Profiler/Profile.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Step/Axiom/Identifier.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Strategy.hs
- kore/src/Kore/Step/Transition.hs
- kore/src/Kore/Unification/Unify.hs
- kore/src/SMT.hs
- stack.yaml
- stack.yaml.lock
> Profiling instrumentation and analysis.

- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Step.hs
> Remove redundant constraints take 3

- kore/app/profiler/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Profiler/Profile.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Data.hs
> Tracing filters

- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/SMT/SimpleSMT.hs
> decidePredicate: Warn about unknown result

- src/main/kore/prelude.kore
> Added prelude.kore to backend repo

- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Remainder.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Step/Simplification/Application.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Ceil.hs-boot
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/In.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Unification/Procedure.hs
- kore/test/Test/Kore/Step/Function/Evaluator.hs
- kore/test/Test/Kore/Step/Function/Integration.hs
- kore/test/Test/Kore/Step/Simplification/Application.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
> axiom-constraints iteration 3

- deps/k_release
- scripts/update-k-nightly-pr.sh
- scripts/update-k-nightly.sh
> Updated K nightly

- Jenkinsfile
> Jenkinsfile: Update K submodules on master

- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Step/Simplification/Data.hs
> Inline Monad instances

- kore/package.yaml
- kore/test/Test/Kore.hs
- scripts/stylish.sh
- stack.yaml
- stack.yaml.lock
> Update LTS to 14.4

- kore/package.yaml
- kore/src/Control/Monad/Counter.hs
- kore/src/Kore/ASTVerifier/PatternVerifier.hs
- kore/src/Kore/Attribute/Pattern.hs
- kore/src/Kore/Attribute/Synthetic.hs
- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Debug.hs
- kore/src/Kore/Internal/MultiAnd.hs
- kore/src/Kore/Internal/MultiOr.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Transition.hs
- kore/src/ListT.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Tasty/HUnit/Extensions.hs
> Remove UndecidableInstances from default extensions

- docs/2019-09-09-Combining-Rewrite-Axioms.md
> Design doc for combining axioms.

- kore/src/Kore/Unification/Error.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
See #956 and https://runtimeverification.slack.com/archives/C9B9QBF46/p1568380474021100 
---
> Refactor 'UnsupportedPatterns' (needed for Created attribute)

- kore/src/Kore/Internal/TermLike.hs
> Minor styling fix for #956

- Jenkinsfile
> Fix Slack notifications from Jenkins

- docs/2018-11-08-Configuration-Splitting-Simplification.md
> Addressing review comments

- kore/src/Kore/IndexedModule/IndexedModule.hs
- kore/src/Kore/Step/SMT/AST.hs
- kore/src/Kore/Step/SMT/Resolvers.hs
- kore/src/Kore/Step/SMT/Translate.hs
- kore/test/Test/Kore/OnePath/Step.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
> Translate variables of non-builtin sorts

- kore/src/Kore/Attribute/Pattern/Created.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/test/Test/Kore/Unification/Unifier.hs
This PR addresses this post-merge https://github.com/kframework/kore/pull/956#pullrequestreview-288648890
---
> Additional fixes for #956: Track Pattern Origins

- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
> Simplification with remainders are skipped instead of failing

- kore/test/Test/Kore/OnePath/Step.hs
> Better test description for Step.hs

- kore/src/Kore/Step/Rule.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Rule.hs
> Fix yet one more Rule free-vars bug.

- kore/app/repl/Main.hs
> Fix a issue in REPL related to user-defined sorts and lemmas

- kore/src/Kore/Strategies/Goal.hs
> simplify one path strategy

- kore/app/profiler/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Profiler/Profile.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Application.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Strategies/Goal.hs
- kore/src/SMT.hs
- kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
> Profiling: branches, fine-grained control, human readable output.

- scripts/ktest.sh
> scripts/ktest.sh: Cannot run different frontend processes in parallel

- docs/2019-09-09-Combining-Rewrite-Axioms.md
- kore/app/exec/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/Rule/Combine.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/test/Test/Kore/Comparators.hs
- kore/test/Test/Kore/Step/Rule/Combine.hs
- src/main/k/working/imp/Makefile
- src/main/k/working/imp/imp.k
- src/main/k/working/imp/merge/1.merge
- src/main/k/working/imp/merge/1.merge-golden
- src/main/k/working/imp/merge/2.merge
- src/main/k/working/imp/merge/2.merge-golden
- src/main/k/working/include.mk
> CLI for merging rewrite rules.

- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
I noticed that we are already using the "classic" environment comonad pattern with `Conditional`, so I thought to give it its usual name.
---
> Add instance Comonad Conditional

- kore/src/Kore/Step/Simplification/OrPattern.hs
This is a slight refactoring of `simplifyPredicatesWithSmt` to avoid using `traverse`. Although `traverse` over `BranchT` and `OrPattern` does not always give the right semantics, this occurrence was alright. Rather, I think using one `scatter` and one `gather` is easier to follow than two `traverse`s and two `gather`s.
---
> simplifyPredicatesWithSmt: Avoid traverse

- kore/src/Data/Graph/TopologicalSort.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/Rule/Combine.hs
- kore/src/Kore/Unification/SubstitutionNormalization.hs
- kore/test/Test/Data/Graph/TopologicalSort.hs
- src/main/k/working/imp/merge/1.merge-golden
- src/main/k/working/imp/merge/2.merge-golden
> Fix typo and formatting

- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
> Better error message for simplification with multiple results

- Jenkinsfile
Reverts kframework/kore#1042
I promise not to touch the build again. :slightly_frowning_face:
> Revert "Jenkinsfile: Run integration tests in parallel"

- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/Rule/Combine.hs
I forgot about this when merging https://github.com/kframework/kore/pull/1039, the helper does not make much sense now.
---
> Refactor rule combining.

- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/Rule/Simplify.hs
- kore/test/Test/Kore/Step/Rule/Simplify.hs
- src/main/k/evm-semantics/sum-to-n/sum-to-n-spec.k
- src/main/k/working/k-equal/specs/iszero-ge-spec.kprove.golden
- src/main/k/working/k-equal/specs/iszero-gt-spec.kprove.golden
> Simplify the LHS of claims

- src/main/k/working/include.mk
> add debug flag to kbmc

- kore/test/Test/Kore/Step/PatternAttributes.hs
> Write tests for PatternAttributes

- kore/src/Kore/Exec.hs
- kore/src/Kore/Logger/Output.hs
> Log expanded claims

- kore/src/Kore/Unparser.hs
- kore/test/Test/Kore/Unparser.hs
> Improve unparsing And

- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/ModelChecker/Simplification.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Internal/TermLike.hs
> Rename rule variables for the 'try' repl command.

- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Incomplete unification in intermediate results

- .gitignore
- kore/Makefile
> Fix Stack's --work-dir in the Makefile

- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/State.hs
> Fix repl discrepancy between step and stepf

- kore/src/Kore/Unification/Error.hs
- kore/src/Kore/Unification/Substitution.hs
- kore/src/Kore/Unification/SubstitutionNormalization.hs
- kore/src/Kore/Unification/UnifierImpl.hs
- kore/test/Test/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Substitution.hs
- kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
> Refactor substitution normalization to allow partial normalization

- scripts/integration-kwasm.sh
> Run both kwasm tests

- kore/src/Kore/Repl.hs
I started off with the `Either` idea, and after some amount of work I realised this might get us pretty much all the way there (the only downside being it just stops when it hits the first error, whereas if we stored errors in `Either Error ProofState` we could accumulate them in the graph). Is that worth the more complex approach?
I could use some feedback @ttuegel 
---
> Report REPL errors

- kore/src/Kore/Builtin/Bool/Bool.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Step/Simplification/Floor.hs
- kore/src/Kore/Step/Simplification/Forall.hs
- kore/src/Kore/Step/Simplification/Iff.hs
- kore/src/Kore/Step/Simplification/In.hs
- kore/src/Kore/Step/Simplification/Inhabitant.hs
- kore/src/Kore/Step/Simplification/Mu.hs
- kore/src/Kore/Step/Simplification/Next.hs
- kore/src/Kore/Step/Simplification/Not.hs
- kore/src/Kore/Step/Simplification/Nu.hs
- kore/src/Kore/Step/Simplification/Rewrites.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
- kore/test/Test/Kore/Unification/Unifier.hs
> Fix markSimplified usage

- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Step/Simplification/Forall.hs
- kore/test/Test/Kore/Step/Simplification/Forall.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
> Fix forall predicates

- kore/app/share/GlobalMain.hs
- kore/src/Branch.hs
- kore/src/Kore/Logger.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Kore/Step/Transition.hs
- kore/src/Kore/Unification/Unify.hs
- kore/src/ListT.hs
- kore/src/SMT.hs
- kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
Remove class WithLog in favor of MonadLog. The WithLog name remains as a
constraint synonym for MonadLog.
---
> Remove class WithLog

- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Step/Simplification/Application.hs
- kore/src/Kore/Step/Simplification/Implies.hs
- kore/test/Test/Kore/Step/Simplification/Application.hs
- kore/test/Test/Kore/Step/Simplification/Implies.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
> Fix implies on predicates and application sorts

- stack.yaml
> LTS Haskell 14.11

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/Application.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/Floor.hs
- kore/src/Kore/Step/Simplification/Not.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
- kore/test/Test/Kore/Step/Simplification/Floor.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
- kore/test/Test/Kore/Step/Simplification/Not.hs
> Fix term sorts in predicates

- kore/src/Kore/Builtin/AssociativeCommutative.hs
> Fix set-var unification infinite loops.

- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
Fixes https://github.com/kframework/kore/issues/1133
---
> Fix OrPattern.toPattern for predicates.

- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Map/Map.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Map.hs
> Implement the 'MAP.values' hook

- kore/src/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
Fixes https://github.com/kframework/kore/issues/1148
---
> Fix the simplified bit for list unification failures

- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
- kore/src/Kore/Unification/Substitution.hs
- kore/src/Kore/Unification/SubstitutionNormalization.hs
- kore/src/Kore/Unification/UnifierImpl.hs
- kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs
- kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
This reverts commit 72e96b53f97635fa27d8bcb25d537f2c5031c11a.
An existing bug was exposed by #1113, so we reverted that pull request until we could fix the bug in #1154.
---
> Replay "Kore.Step.Simplification.SubstitutionSimplifier (#1113)"

- kore/src/Kore/Step/Rule/Combine.hs
- kore/test/Test/Kore/Step/Rule/Combine.hs
Fixes https://github.com/runtimeverification/polkadot-verification/issues/45
---
> Polkadot merge rules

- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Strategies/Goal.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
Fixes https://github.com/kframework/kore/issues/1153
See the issue for details about what this attempts to solve.
---
> Fix equals simplification

- kore/src/Kore/Builtin/List.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
> Mark list unification results as simplified

- scripts/integration-kwasm.sh
> Kwasm memory spec was renamed

- kore/src/Kore/Logger.hs
- kore/src/Kore/Logger/Output.hs
> Instance Entry SomeEntry

- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
> functionLike checks for simplification

- stack.yaml
- stack.yaml.lock
> LTS Haskell 14.13

- Dockerfile
> Dockerfile: Install z3-4.6

- Jenkinsfile
> Jenkinsfile: Do not fail because of rv-devops jobs

- kore/app/share/GlobalMain.hs
> Added KORE_EXEC_OPTS environment variable

- scripts/update-stack-resolver.sh
- stack.yaml
- stack.yaml.lock
> LTS Haskell 14.14

- docs/hooks.md
- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/List/List.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/List.hs
Fixes https://github.com/kframework/kore/issues/1223
`MAP.values` was already implemented but the documentation for it was missing.
---
> Hooks: LIST.in

- kore/src/Kore/Attribute/Assoc.hs
- kore/src/Kore/Attribute/Axiom/Concrete.hs
- kore/src/Kore/Attribute/Axiom/Constructor.hs
- kore/src/Kore/Attribute/Axiom/Unit.hs
- kore/src/Kore/Attribute/Comm.hs
- kore/src/Kore/Attribute/Constructor.hs
- kore/src/Kore/Attribute/Function.hs
- kore/src/Kore/Attribute/Functional.hs
- kore/src/Kore/Attribute/Idem.hs
- kore/src/Kore/Attribute/Injective.hs
- kore/src/Kore/Attribute/Parser.hs
- kore/src/Kore/Attribute/Simplification.hs
- kore/src/Kore/Attribute/SmtLemma.hs
- kore/src/Kore/Attribute/Sort/HasDomainValues.hs
- kore/src/Kore/Attribute/Symbol.hs
- kore/src/Kore/Attribute/Symbol/Anywhere.hs
- kore/src/Kore/Attribute/Symbol/Klabel.hs
- kore/src/Kore/Attribute/Symbol/Memo.hs
- kore/src/Kore/Attribute/Symbol/SymbolKywd.hs
- kore/src/Kore/Attribute/Trusted.hs
- kore/test/Test/Kore/Attribute/Symbol.hs
- kore/test/Test/Kore/Attribute/Symbol/Klabel.hs
- kore/test/Test/Kore/Attribute/Symbol/SymbolKywd.hs
- kore/test/Test/Kore/Internal/Symbol.hs
> Attributes for klabel and symbolKywd

- kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
> Add check in deduplicateSubstitution

- kore/test/Test/Kore/Repl/Interpreter.hs
> Test.Kore.Repl.Interpreter: Remove debug output

- kore/test/Test/ConsistentKore.hs
- kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
> Generate maps and sets

- kore/src/Kore/Logger/WarnUnhookedSymbol.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Simplify.hs
Fixes #1185 also see https://runtimeverification.slack.com/archives/CC360GUTG/p1573726962193100
---
> WarnUnhookedSymbol

- kore/src/Kore/Internal/Symbol.hs
- kore/src/Kore/Logger.hs
- kore/src/Kore/Logger/DebugAppliedRule.hs
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Logger/WarnFunctionWithoutEvaluators.hs
- kore/src/Kore/Logger/WarnSimplificationWithRemainder.hs
- kore/src/Kore/Logger/WarnUnhookedSymbol.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Step/Axiom/Evaluate.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Simplify.hs
- kore/src/Kore/Step/Step.hs
- kore/src/Kore/Variables/Target.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> Log applied rules

- kore/src/Kore/Step/Rule.hs
> Error for functions with ensures

- kore/src/Kore/Step/Rule.hs
See also: kframework/k#923
---
> Decode function axiom ensures clause

- kore/src/Kore/Step/Simplification/Or.hs
- kore/test/Test/Kore/Step/Axiom/Evaluate.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
- kore/test/Test/Kore/Step/Simplification/Or.hs
The next issue for idempotency seems to be sort mismatches (_predicate vs original sort).
---
> Make or simplification trivial.

- kore/src/Kore/Step/Simplification/Overloading.hs
- src/main/k/working/tests/overloads/domain-values/Makefile
- src/main/k/working/tests/overloads/domain-values/domain-values-spec.k
- src/main/k/working/tests/overloads/domain-values/domain-values.k
- src/main/k/working/tests/overloads/domain-values/prove/domain-values-spec.k
> Overloaded constructors and domain values

- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Rule/Simplify.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
- kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
- kore/test/Test/Kore/Builtin/List.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- src/main/k/working/imp/merge/1.merge-golden
- src/main/k/working/imp/merge/2.merge-golden
- src/main/k/working/tests/collections/list-unify-assoc/Makefile
- src/main/k/working/tests/collections/list-unify-assoc/list-unify-assoc.k
- src/main/k/working/tests/collections/list-unify-assoc/proofs/push-spec.k
> List unification with unit.

- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Logger.hs
- kore/src/Kore/Logger/DebugAppliedRule.hs
- kore/src/Kore/Logger/DebugSolver.hs
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/ModelChecker/Bounded.hs
- kore/src/Kore/Step/EquationalStep.hs
- kore/src/Kore/Step/RewriteStep.hs
- kore/src/Kore/Step/SMT/Evaluator.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/src/Kore/Unification/Procedure.hs
- kore/src/SMT.hs
- kore/src/SMT/AST.hs
- kore/src/SMT/SimpleSMT.hs
Fixes https://github.com/kframework/kore/issues/1317 + removes `Logger.WithScope`
---
> Show TypeRep in log entry

- stack.yaml
- stack.yaml.lock
> LTS Haskell 14.16

- kore/src/Kore/Logger/DebugAppliedRule.hs
- kore/src/Kore/Logger/DebugAxiomEvaluation.hs
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> Log equality axiom evaluation

- kore/src/Kore/Logger/DebugAxiomEvaluation.hs
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Step/Axiom/Evaluate.hs
- kore/src/Kore/Step/Function/Evaluator.hs
~Depends on https://github.com/kframework/kore/pull/1323~
Fixes #1263 
---
> Function evaluation logging

- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Repl/State.hs
> Fix smt solver log changes

- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/Simplification/Rule.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
- src/main/k/working/tests/with-config/Makefile
- src/main/k/working/tests/with-config/prove/one-spec.k
- src/main/k/working/tests/with-config/prove/owise-spec.k
- src/main/k/working/tests/with-config/with-config.k
> Fix map matching

- deps/k_release
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Internal/TermLike/TermLike.hs
> Break up Kore.Internal.TermLike

- kore/app/exec/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Strategies/Verification.hs
- kore/test/Test/Kore/Strategies/AllPath/Verification.hs
- kore/test/Test/Kore/Strategies/Common.hs
- kore/test/Test/Kore/Strategies/OnePath/Verification.hs
- kore/test/Test/Kore/Strategies/Reachability/Verification.hs
- src/main/k/working/imp/Makefile
- src/main/k/working/imp/save-proofs/sum-spec.k
- src/main/k/working/imp/save-proofs/sum-spec.save-proofs-golden
- src/main/k/working/include.mk
This solves half of #1277 
---
> Dump proven claims to file

- Jenkinsfile
> Jenkinsfile: switch to generic submodule updater

- kore/app/exec/Main.hs
- kore/app/repl/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Strategies/Verification.hs
- kore/test/Test/Kore/Strategies/AllPath/Verification.hs
- kore/test/Test/Kore/Strategies/Common.hs
- kore/test/Test/Kore/Strategies/OnePath/Verification.hs
- kore/test/Test/Kore/Strategies/Reachability/Verification.hs
- src/main/k/working/imp/save-proofs/sum-spec.save-proofs-golden
- src/main/k/working/include.mk
- src/main/k/working/tests/save-proofs/Makefile
- src/main/k/working/tests/save-proofs/save-proofs.k
- src/main/k/working/tests/save-proofs/save-proofs/test-1.k
- src/main/k/working/tests/save-proofs/save-proofs/test-2.k
- src/main/k/working/tests/smt-lemma/smt-lemma.k
~Needs https://github.com/kframework/kore/pull/1356~
Fixes #1277 
---
> Skip proving rules that are already proven

- kore/src/Kore/Logger/DebugSolver.hs
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Logger/Registry.hs
- kore/src/Kore/Logger/WarnBottomHook.hs
- kore/src/Kore/Logger/WarnFunctionWithoutEvaluators.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
Fixes https://github.com/kframework/kore/issues/1353
---
> Add registry of log entry types

- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
- src/main/k/working/tests/with-config-arbitrary-map/Makefile
- src/main/k/working/tests/with-config-arbitrary-map/prove/one-spec.k
- src/main/k/working/tests/with-config-arbitrary-map/with-config.k
> Fix map matching with opaque on the right.

- kore/app/share/GlobalMain.hs
- kore/src/Kore/Logger/Registry.hs
Fixes https://github.com/kframework/kore/issues/1400
---
> Add LogMessage to the Registry

- kore/src/Kore/Attribute/Pattern.hs
- kore/src/Kore/Attribute/Pattern/ConstructorLike.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Internal/TermLike/TermLike.hs
- kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
> Fix ConstructorLike for maps

- kore/package.yaml
- kore/src/Kore/Logger/Output.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Repl/State.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
> Configureable timestamps in log

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
Fixes https://github.com/kframework/kore/issues/1403
---
> Repl: allow user to specify graph save format

- include.mk
> include.mk: Disable builtin rules

- kore/src/Kore/Attribute/Pattern.hs
- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Internal/Condition.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Internal/Substitution.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/AndPredicates.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/Mu.hs
- kore/src/Kore/Step/Simplification/NoConfusion.hs
- kore/src/Kore/Step/Simplification/Nu.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
> Use the Simplified monoid

- design-decisions/2020-01-02-Side-conditions-for-predicates.md
> Clarify Side conditions design doc after discussion with yi.zhang

- docs/hooks.md
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Map/Map.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Map.hs
Fixes https://github.com/kframework/kore/issues/1437
---
> Hook: MAP.keys_list

- README.md
> Add link to yq in README.md

- kore/src/Kore/Internal/MultiOr.hs
- kore/src/Kore/Internal/OrCondition.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Step/Axiom/Evaluate.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/OrPattern.hs
- kore/test/Test/Kore/Step/Axiom/Evaluate.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Simplification/OrPattern.hs
- test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
> Optimize smt

- kore/src/Debug.hs
- kore/src/Kore/Attribute/Pattern.hs
- kore/src/Kore/Attribute/Pattern/Simplified.hs
- kore/src/Kore/Internal/SideCondition/SideCondition.hs
> Fix comments from #1409

- .hlint.yaml
- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Log/DebugAppliedRule.hs
- kore/src/Kore/Log/DebugEvaluateCondition.hs
- kore/src/Kore/Log/WarnBottomHook.hs
- kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
- kore/src/Kore/Log/WarnSimplificationWithRemainder.hs
- kore/src/Kore/Step/EqualityPattern.hs
- kore/src/SQL.hs
- kore/src/SQL/Column.hs
- kore/src/SQL/Key.hs
- kore/src/SQL/Query.hs
- kore/src/SQL/SOP.hs
- kore/src/SQL/SQL.hs
- kore/src/SQL/Table.hs
- kore/test/Test/Kore/Log/DebugAppliedRule.hs
- kore/test/Test/SQL.hs
- Derive sum type instances for the Table class.
- Use the full type name (not the type constructor name) to disambiguate instantiations of polymorphic types.
Fixes: #1266 
---
> Structured logging: Sum type support

- Dockerfile
- README.md
- global-stack.yaml
- scripts/check.sh
- scripts/stylish.sh
> Pin stylish-haskell-0.9.4.4

- kore/src/Kore/Builtin/String.hs
- kore/src/Kore/Builtin/String/String.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/String.hs
> Implement the int2string hook

- docs/hooks.md
> docs/hooks.md: add entry for 'STRING.int2string'

- docs/hooks.md
- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/List/List.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/List.hs
> Add LIST.size hook

- kore/src/Debug.hs
- kore/src/Kore/Debug.hs
- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Profiler/Profile.hs
- kore/src/Prelude/Kore.hs
- kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
> Add Debug.Tracing to Prelude.Kore

- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Step/Function/Integration.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- kore/test/Test/Kore/Step/Simplification/Exists.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
- test/bmc/fail-2-bmc-spec.k.out.golden
Fixes 7 of the evm lemma tests, 2 are still failing.
---
> Subterm ceil

- kore/src/Kore/Internal/TermLike/TermLike.hs
- test/imp/Makefile
- test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
- test/include.mk
- test/regression-evm-semantics-39dd1e5/test-branching-invalid.sh.out.golden
- test/regression-evm-semantics-39dd1e5/test-straight-line.sh.out.golden
> TermLike: No line break in unparsed comment

- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Internal/Substitution.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Variables/Target.hs
- kore/test/Test/Kore/Internal/Substitution.hs
Fixes https://github.com/kframework/kore/issues/1551
---
> Use Target variable in exists simplifier

- kore/app/exec/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/SMT.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
> Remove UnliftIO from SMT

- kore/src/Prelude/Kore.hs
- kore/test/Test/Kore/Attribute/Parser.hs
- kore/test/Test/Kore/Parser.hs
> Prelude.Kore: Export isLeft and isRight

- kore/src/Kore/Builtin/Encoding.hs
- kore/test/Test/Kore/Builtin/Encoding.hs
Fixes: #1553 
~After: #1558~
---
> Parse Bytes domain values correctly

- kore/app/exec/Main.hs
- kore/src/Control/Monad/Counter.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Log.hs
- kore/src/Kore/Profiler/Data.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Step/Function/Memo.hs
- kore/src/Kore/Step/SMT/Lemma.hs
- kore/src/Log.hs
- kore/src/Prelude/Kore.hs
- kore/src/SQL/SQL.hs
- kore/test/Test/SMT.hs
- kore/test/Test/Tasty/HUnit/Ext.hs
> Prelude.Kore: MonadIO

- kore/package.yaml
> Remove unliftio from dependencies

- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
> Red for stuck nodes in the repl graph.

- kore/src/Kore/Step/RulePattern.hs
- kore/src/Kore/Strategies/Goal.hs
- kore/test/Test/Kore/Strategies/AllPath/Verification.hs
- kore/test/Test/Kore/Strategies/OnePath/Verification.hs
Fixes https://github.com/kframework/kore/issues/900
---
> Group and apply rewrite rules according to their priority

- kore/src/Kore/Step/Simplification/Data.hs
- kore/src/Log.hs
- kore/src/SMT.hs
- kore/src/SMT/SimpleSMT.hs
> SimpleSMT: Do not capture LogAction at initialization

- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Step/RulePattern.hs
> Bug: repl should not generate only one-path claims at exit

- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Step/Axiom/Registry.hs
- kore/test/Test/Kore/Step/Axiom/Registry.hs
Also, removing one unused function
---
> Sorting simplification axioms

- kore/app/exec/Main.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Internal/TermLike.hs
- kore/src/Kore/Internal/TermLike/TermLike.hs
- kore/src/Kore/Log/DebugAxiomEvaluation.hs
- kore/src/Kore/Step/Function/Evaluator.hs
- kore/src/Kore/Step/RulePattern.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/Rule.hs
- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/RewriteStep.hs
- kore/test/Test/Kore/Step/Simplification/And.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
- test/imp/impossible-branch.imp.out.golden
- test/imp/impossible-branch.imp.search-final.out.golden
- test/imp/max-symbolic.imp.out.golden
- test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
- test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
- test/save-proofs/test-1-spec.k.save-proofs.kore.golden
This is the unoptimized version, with rather bad time complexity.
Running simplifiers without simplifier axioms seems rather dangerous.
---
> Better and normalization

- kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
- kore/src/Kore/Internal/MultiAnd.hs
- kore/src/Kore/Internal/OrCondition.hs
- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Step/Simplification/CeilSimplifier.hs
- kore/src/Prelude/Kore.hs
- kore/test/Test/Kore/Builtin/AssocComm/CeilSimplifier.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification.hs
- kore/test/Test/Kore/Step/Simplification/Ceil.hs
- test/imp/2.merge.out.golden
- test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
> Simplify Ceil of Map and Set

- kore/src/Changed.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/test/Test/Kore/Step/Simplification/And.hs
> Simplify with negated predicates from a top-level conjunction

- kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/src/Kore/Internal/TermLike/TermLike.hs
- kore/src/Kore/Step/Simplification/Ceil.hs
- kore/src/Kore/Syntax/ElementVariable.hs
- kore/src/Kore/Syntax/SetVariable.hs
- kore/src/Kore/Syntax/Variable.hs
- kore/test/Test/Kore/Builtin/AssocComm/CeilSimplifier.hs
- test/imp/2.merge.out.golden
- test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
> Make values irrelevant to Map key membership

- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Domain/Builtin.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/Set.hs
Fixes https://github.com/kframework/kore/issues/1605
---
> Evaluate in hook for symbolic sets

- kore/app/exec/Main.hs
- kore/app/format/Main.hs
- kore/app/parser/Main.hs
- kore/app/repl/Main.hs
- kore/app/share/GlobalMain.hs
> Print command line and KORE_EXEC_OPTS when parsing fails

- kore/src/Kore/Step/Simplification/AndTerms.hs
> Define inequality of Bytes

- deps/k_release
- kore/Makefile
- kore/src/Kore/Attribute/Axiom.hs
- kore/src/Kore/Step/EqualityPattern.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/RulePattern.hs
- kore/test/Test/Kore/Exec.hs
- kore/test/Test/Kore/Step/Rule.hs
- test/setvars/setvars.k
> Better identification for rewrite rules based on priority

- kore/src/Kore/Log/DebugAppliedRewriteRules.hs
- kore/src/Kore/Log/DebugProofState.hs
> Change Pretty instance for DebugAppliedRewriteRules and DebugProofState

- kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
- test/imp/2.merge.out.golden
- test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
> Clean-up after Map and Set definedness changes

- kore/src/Kore/Log/DebugSkipSimplification.hs
- kore/src/Kore/Log/Registry.hs
- kore/src/Kore/Log/SQLite.hs
- kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Log/DebugSkipSimplification.hs
- test/simplification/Makefile
> Replace WarnSimplificationWithRemainder with DebugSkipSimplification

- kore/src/Kore/ASTVerifier/SentenceVerifier.hs
- kore/src/Kore/Attribute/Axiom.hs
- kore/src/Kore/Attribute/Axiom/Concrete.hs
- kore/src/Kore/Attribute/Parser.hs
- kore/src/Kore/Attribute/Pattern/FreeVariables.hs
- kore/src/Kore/Step/EqualityPattern.hs
- kore/src/Kore/Syntax/Sentence.hs
- kore/test/Test/Kore/Attribute/Axiom/Concrete.hs
- kore/test/Test/Kore/Step/Axiom/Evaluate.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Rule.hs
This is partial progress toward #1557. I want to merge this now because I have to put that task down.
---
> Concrete axiom attribute

- docs/hooks.md
- kore/src/Kore/Builtin/String.hs
- kore/src/Kore/Builtin/String/String.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/String.hs
Fixes https://github.com/kframework/kore/issues/1655
---
> Hook: STRING.eq

- kore/src/Kore/Attribute/Attributes.hs
- kore/src/Kore/Attribute/Axiom.hs
- kore/src/Kore/Attribute/Axiom/Concrete.hs
- kore/src/Kore/Attribute/Axiom/Symbolic.hs
- kore/src/Kore/Attribute/Parser.hs
- kore/src/Kore/Step/EqualityPattern.hs
- kore/test/Test/Kore/Attribute/Axiom/Concrete.hs
- kore/test/Test/Kore/Attribute/Axiom/Symbolic.hs
> Enabled concrete to take a list of arguments

- kore/src/Kore/Strategies/Goal.hs
- kore/test/Test/Kore/Strategies/OnePath/Step.hs
- test/imp/sum-save-proofs-spec.k.out.golden
Fixes https://github.com/kframework/kore/issues/1643
---
> Return stuck goal after remove destination

- kore/src/Kore/Attribute/Axiom/Concrete.hs
- kore/src/Kore/Step/Axiom/Evaluate.hs
- kore/src/Kore/Step/Axiom/Matcher.hs
- kore/src/Kore/Step/EqualityPattern.hs
- kore/src/Kore/Step/EquationalStep.hs
- kore/src/Kore/Step/RulePattern.hs
- kore/src/Kore/Step/Simplification/Exists.hs
- kore/src/Kore/Step/Step.hs
- kore/test/Test/Kore/Step/Axiom/Evaluate.hs
- kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
- kore/test/Test/Kore/Step/Axiom/Matcher.hs
> implemented substitution checks for concrete and symbolic attributes

- dist/kast.kscript
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Parser.hs
Fixes https://github.com/kframework/kore/issues/1687
---
> Repl: fix claim command parser

- kore/src/Kore/Log/InfoReachability.hs
- kore/src/Kore/Log/Registry.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Step/RulePattern.hs
- kore/src/Kore/Strategies/Goal.hs
- kore/src/Kore/Strategies/Rule.hs
- kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
> Print Info when a strategy step starts

- kore/src/Kore/Step/Axiom/Matcher.hs
Fixes https://github.com/kframework/kore/issues/1690
---
> Sort constraints when matching

- .hlint.yaml
- kore/src/Kore/Log.hs
- kore/src/Kore/Log/DebugAxiomEvaluation.hs
- kore/src/Kore/Log/Registry.hs
- kore/src/Log/Entry.hs
- test/kreflection/test-kreflection.sh.out.golden
> Improve several log entry formats

- kore/src/Kore/Log/InfoReachability.hs
---
I should have done this in #1682
> Continue #1682: Implement shortDoc for InfoReachability

- kore/src/Data/Sup.hs
- kore/src/Debug.hs
- kore/src/Kore/IndexedModule/OverloadGraph.hs
- kore/src/Kore/IndexedModule/SortGraph.hs
- kore/src/Kore/Internal/Conditional.hs
- kore/src/Kore/Internal/Inj.hs
- kore/src/Kore/Log/DebugAxiomEvaluation.hs
- kore/src/Kore/Log/DebugSkipSimplification.hs
- kore/src/Kore/Log/Registry.hs
- kore/src/Kore/Log/WarnFunctionWithoutEvaluators.hs
- kore/src/Kore/Sort.hs
- kore/src/Kore/Step/Strategy.hs
- kore/src/Kore/Step/Transition.hs
- kore/src/Kore/Strategies/Goal.hs
- kore/src/Kore/Strategies/Verification.hs
- kore/src/Log/Entry.hs
- kore/src/Prelude/Kore.hs
- kore/src/SQL.hs
- kore/src/SQL/SOP.hs
- kore/src/SQL/Table.hs
- kore/test/Test/Kore/Strategies/OnePath/Step.hs
> Prelude.Kore (Typeable)

- include.mk
- test/include.mk
> Makefile rule for running repl scripts

- kore/src/Log.hs
> logEntry: Add context to log message

- test/include.mk
> Fix bug in repl-script Makefile rule

- kore/src/Kore/Log.hs
> Display the type of each context entry in the log

- kore/package.yaml
> Begin kore-0.20.0.0

- include.mk
- test/include.mk
This is a support task for Issue #1731 
---
> Added task for verifying definitions

- kore/src/Kore/Builtin.hs
- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/src/Kore/Builtin/Bool.hs
- kore/src/Kore/Builtin/Builtin.hs
- kore/src/Kore/Builtin/Int.hs
- kore/src/Kore/Builtin/InternalBytes.hs
- kore/src/Kore/Builtin/KEqual.hs
- kore/src/Kore/Builtin/Krypto.hs
- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Builtin/Set.hs
- kore/src/Kore/Builtin/String.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/Integration.hs
This pull request refactors hooked functions to eliminate boilerplate and make the implementations easier to test.
---
> Refactor hooked functions

- kore/src/Kore/Builtin/Krypto.hs
- kore/test/Test/Kore/Builtin/Krypto.hs
> New names for crypto hooks

- kore/src/Kore/Log/Registry.hs
- kore/src/Kore/Log/SQLite.hs
- kore/src/Kore/Log/WarnSymbolSMTRepresentation.hs
- kore/src/Kore/Step/SMT/Lemma.hs
- kore/src/Kore/Step/SMT/Translate.hs
- kore/test/Test/Kore/Log/WarnSymbolSMTRepresentation.hs
> Warn when a symbol that is hooked for the solver cannot be translated to SMT-LIB

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.22.0.0

- kore/app/repl/Main.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Repl.hs
> Use KoreLogOptions in repl state

- kore/src/Kore/Log/KoreLogOptions.hs
- kore/src/Kore/Repl/Data.hs
> Document logging equations

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.24.0.0

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.25.0.0

- kore/src/Kore/Repl.hs
---
I couldn't find any refactoring to make in #1953 , just another small suggestion
> One more change for #1953

- kore/src/Prof.hs
> Missing instance MonadProf for StateT

- docs/2020-06-30-Combining-Priority-Axioms.md
- kore/src/Kore/ASTVerifier/SentenceVerifier.hs
- kore/src/Kore/Internal/Alias.hs
- kore/src/Kore/Step/AntiLeft.hs
- kore/src/Kore/Step/Rule.hs
- kore/src/Kore/Step/Rule/Combine.hs
- kore/src/Kore/Step/Rule/Expand.hs
- kore/src/Kore/Step/RulePattern.hs
- kore/src/Kore/Step/Simplification/Rule.hs
- kore/test/Test/Kore/Exec.hs
- kore/test/Test/Kore/Step/AntiLeft.hs
- kore/test/Test/Kore/Step/Rule/Combine.hs
- kore/test/Test/Kore/Step/RulePattern.hs
- test/priority/1.merge
- test/priority/2.merge
- test/priority/2.merge.out.golden
- test/priority/Makefile
- test/priority/priority.k
> Merge priority rules

- kore/app/exec/Main.hs
- kore/src/SMT.hs
- kore/src/SMT/SimpleSMT.hs
Fixes https://github.com/kframework/kore/issues/1934
---
> Handle Z3 exceptions

- kore/src/Kore/BugReport.hs
> No bug report on ExitSuccess

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.26.0.0

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.27.0.0

- kore/src/SMT.hs
> SMT.setTimeOut: Use the correct command for setting timeout option

- kore/src/Kore/Strategies/Verification.hs
Fixes: #2028 
This pull request does not actually fix anything, but it makes it clear what a helper function is doing.
---
> verifyClaim: Name discardAppliedRules

- kore/src/Kore/Builtin/String.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Builtin/Definition.hs
- kore/test/Test/Kore/Builtin/String.hs
> Symbolic rules for ==String

- kore/src/Kore/Log/ErrorException.hs
> AssertionFailed: prompt the user to file a bug report

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.28.0.0

- kore/src/Kore/Internal/TermLike/TermLike.hs
Fixes: #2104 
I am waiting on a performance analysis in actual use, but the unit tests are about 10% faster.
---
> TermLike: Inline definition of Cofree

- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Rule/Combine.hs
- kore/test/Test/Kore/Unification/Unifier.hs
- test/imp/impossible-branch.imp.out.golden
- test/imp/max-breadth-limit-one-spec.k.out.golden
- test/imp/max-symbolic.imp.out.golden
- test/issue-2010/1.test.out.golden
- test/k-equal/iszero-ge-spec.k.out.golden
> Make AndTerms.functionAnd commutative

- kore/src/Kore/Internal/MultiAnd.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Step/Simplification/And.hs
- kore/src/Kore/Step/Simplification/Equals.hs
- kore/src/Kore/Step/Simplification/Implies.hs
- kore/src/Kore/Step/Simplification/In.hs
- kore/src/Kore/Step/Simplification/Not.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/src/Kore/Step/Substitution.hs
- kore/test/Test/Kore/Step/Simplification/And.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Simplification/Application.hs
- kore/test/Test/Kore/Step/Simplification/Equals.hs
- kore/test/Test/Kore/Step/Simplification/Not.hs
- test/priority/1.merge.out.golden
- test/priority/2.merge.out.golden
> Linear \and simplification

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.29.0.0

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.30.0.0

- kore/src/Kore/Equation/Application.hs
- kore/test/Test/Kore/Equation/Application.hs
Fixes https://github.com/kframework/kore/issues/2143
---
> Disable function evaluation when simplifying Equation's argument predicate

- kore/src/Kore/Reachability/Claim.hs
- kore/test/Test/Kore/Reachability/Claim.hs
- kore/test/Test/Kore/Step/Rule/Simplify.hs
Fixes https://github.com/kframework/kore/issues/2145-
--
> Filter unsatisfiable patterns from the right-hand side of claims

- kore/src/Kore/Attribute/Pattern/Simplified.hs
- kore/src/Kore/Internal/MultiAnd.hs
- kore/src/Kore/Internal/OrPattern.hs
- kore/src/Kore/Internal/Pattern.hs
- kore/src/Kore/Step/Simplification/Floor.hs
- kore/src/Kore/Step/Simplification/TermLike.hs
- kore/test/Test/Kore/Internal/Pattern.hs
- kore/test/Test/Kore/Step/MockSymbols.hs
- kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs
> Use hasSimplifiedChildren in term simplifier check

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.31.0.0

- kore/src/Kore/Reachability/Claim.hs
- kore/src/Log.hs
- kore/src/Prof.hs
- kore/src/SMT.hs
- kore/src/SMT/SimpleSMT.hs
> Reset the SMT solver at fixed intervals

- kore/app/share/GlobalMain.hs
- kore/src/Kore/ASTVerifier/AttributesVerifier.hs
- kore/src/Kore/Log/ErrorParse.hs
- kore/src/Kore/Log/Registry.hs
- test/no-injection-into-hooked/test.k.verify.out.golden
> Fix "Hooked sorts may not have subsorts" error

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.32.0.0

- kore/src/Kore/Equation/Application.hs
> final log now falls under initial context

- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.33.0.0

- .github/workflows/test.yml
- kore/CHANGELOG.md
- kore/package.yaml
> kore-0.34.0.0

- docs/hooks.md
- kore/src/Kore/Builtin/List.hs
- kore/test/Test/Kore/Builtin/List.hs
- kore/test/Test/Kore/Step/Function/Integration.hs
> LIST.update is \bottom for negative indices

- .github/PULL_REQUEST_TEMPLATE.md
The pull request box is not formatted in the same way as other Markdown around
the GitHub site, so looking at the preview after the last changes to the
template gave the wrong impression.
---
The author performs the actions on the checklist.
The reviewer evaluates the work and checks the boxes as they are completed.
-   [x] **Summary**
Write a summary of the changes.
Explain what you did to fix the issue, and why you did it.
Present the changes in a logical order.
Instead of writing a summary in the pull request,
you may push a clean Git history.
-   [x] **Documentation**
Write documentation for new functions.
Update documentation for functions that changed,
or complete documentation where it is missing.
-   [x] **Tests**
Write unit tests for every change.
Write the unit tests that were …
> Fix pull request template formatting

- kore/CHANGELOG.md
- kore/kore.cabal
- kore/package.yaml
- nix/kore.nix.d/kore.nix
> kore-0.36.0.0

- .github/workflows/test.yml
- kore/src/Kore/Step/Simplification/TermLike.hs
- scripts/check.sh
> Format with stylish-haskell automatically

- default.nix
Needed for kframework/k#1665 to work around input-output-hk/haskell.nix#787.
---
-   [ ] …
> default.nix: Don't use cleanGit

- kore/src/Kore/Log.hs
Fixes #2284 
Performs an empty `writeFile` in the relevant filepath writing into it.
---
-   [ …
> Overwrite solver transcript log

- kore/test/Test/Kore/Builtin/InternalBytes.hs
@ana-pantilie This fixes the broken test case name you saw. (I got blocked on this, too.)
---
- …
> Fix illegal test case name

- default.nix
Needed by kframework/k#1665. Fix caching by giving a fixed name to `src`.
---
-   [ ] **Clean …
> default.nix: Give a fixed name to src

- .github/workflows/test.yml
- .github/workflows/update.yml
- default.nix
- Move some steps to a separate Update workflow that runs on `push` events, so that we can accept pull requests from forks.
- Use a whitelist for source files available in the Nix builder, to improve caching.
---
-   [ ] **Tests.** Write unit tests for every change. Write …
> Nix: Allow pull requests from forks. Improve caching.

- kore/src/Kore/Reachability/Claim.hs
- kore/test/Test/Kore/Reachability/Claim.hs
> checkImplication.examine: check if RHS is \bottom

- kore/src/Kore/Reachability/Prove.hs
- kore/src/Prelude/Kore.hs
See https://github.com/kframework/kore/pull/2324/checks?check_run_id=1642512161
---
-   [x] …
> Prelude.Kore: Export fromLeft and fromRight

- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Step/SMT/Helpers.hs
- kore/test/Test/SMT.hs
> Increase solver timeout in sort declaration tests

- .github/workflows/test.yml
- default.nix
- kore/CHANGELOG.md
- kore/kore.cabal
- kore/package.yaml
- nix/kore.nix.d/kore.nix
- nix/rematerialize.sh
> kore-0.37.0.0

- kore/src/Debug.hs
> Minor fix: Debug/Diff Map instances

- kore/app/exec/Main.hs
- test/bmc/pass-3-bmc-spec.k.out.golden
Fixes #2342.
---
-   [x] **Clean up.** The changes are already clean. Clean up anything near …
> Return \top when BMC exceeds bound, but emit a warning

- kore/app/parser/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Options.hs
Required for https://github.com/runtimeverification/c-semantics/pull/213
---
-   [ ] **Clean …
> kore-parser: Parse and validate multiple pattern files

- kore/CHANGELOG.md
- kore/kore.cabal
- kore/package.yaml
- nix/kore.nix.d/kore.nix
> kore-0.39.0.0

- README.md
Add instructions for running a single test in Docker.
---
-   [ ] **Clean up.** The changes are …
> Add instructions for running one test in Docker

- include.mk
- kore/app/repl/Main.hs
> Support the --bug-report and --no-bug-report options in kore-repl

- kore/src/Kore/Step/Function/Evaluator.hs
This PR reverts the changes introduced in PR #2334 as they are no longer needed after PR #2469 was merged in.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as …
> Revert PR #2334

- default.nix
Part of https://github.com/kframework/k/issues/1864
---
-   [ ] **Clean up.** The changes are …
> Add ref = "main"; to default.nix

- scripts/generate-regression-tests.sh
See https://runtimeverification.slack.com/archives/CC360GUTG/p1616770604091000?thread_ts=1616680678.069600&cid=CC360GUTG
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the …
> Update evm test generation script

- kore/CHANGELOG.md
- kore/kore.cabal
- kore/package.yaml
- nix/kore.nix.d/kore.nix
> kore-0.43.0.0

- kore/src/Kore/Internal/NormalizedAc.hs
Fixes the master job.
It turns out that the pull request was merged against failing tests because the automerge user had inappropriate permissions.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include …
> Remove redundant parentheses

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.44.0.0

- scripts/generate-regression-tests.sh
Don't allow `make` to echo the command being ran when generating the files for the proving tests.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration …
> Fix regression test generator script

- kore/src/Kore/Step/Simplification/Next.hs
- kore/test/Test/Kore/Step/Simplification/Next.hs
> Distribute \next over \or in simplifier

- kore/src/Kore/Internal/MultiOr.hs
This is _not_ an `Unparse` instance because it doesn't produce valid Kore (the sorts are missing), but it's close enough for debugging.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples …
> Add instance Pretty MultiOr

- kore/app/exec/Main.hs
- kore/app/repl/Main.hs
- kore/src/Options/SMT.hs
- kore/src/SMT.hs
> Add flag to limit z3 resouce

- docs/2020-06-22-Rewrite-Rule-Priorities.md
> Write 'n' index as subscript in 2020-06-22-Rewrite-Rule-Priorities.md

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.48.0.0

- .hlint.yaml
- kore/kore.cabal
- kore/src/Kore/Step/Simplification/Inj.hs
- kore/test/Test/Kore/Step/Simplification/Inj.hs
- nix/kore.nix.d/kore.nix
- test/imp/1.merge.out.golden
- test/imp/2.merge.out.golden
- test/issue-2244/test-issue-2244.sh.out.golden
> Mark Inj simplified

- kore/src/Kore/Builtin/Builtin.hs
- kore/src/Kore/Builtin/List.hs
- kore/src/Kore/Step/Simplification/AndTerms.hs
- kore/test/Test/Kore/Step/Simplification/AndTerms.hs
> Do not return \bottom for unsolved List unification cases

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.49.0.0

- .github/workflows/test.yml
> Fix cabal workflow

- scripts/generate-regression-tests.sh
> fixing script

- Jenkinsfile
> Jenkinsfile: fix credentials

- Jenkinsfile
> Jenkinsfile: fix build name

- kore/src/Kore/Exec.hs
- kore/test/Test/Kore/Exec.hs
> Don't crash on unsatisfiable configurations.

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.51.0.0

- scripts/update-tests.sh
> Update tests: change reviewer

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.52.0.0

- README.md
- docs/introduction.md
Extends #2759 
Added hyperlinks in `/docs/introduction.md` to reference source code.
---
-   [ …
> Remove Semantics of K from README.md

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.53.0.0

- .hlint.yaml
- kore/src/Pretty.hs
Needed for https://github.com/kframework/kore/pull/2836
---
-   [ ] **Clean up.** The changes …
> Fix Cabal build for Update issue #2836

- kore/CHANGELOG.md
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> kore-0.58.0.0

- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/State.hs
- kore/test/Test/Kore/Repl/Graph.hs
Fixes #2902
- December 16
---
-   [ ] **Clean up.** The changes are already clean. Clean up …
> kore-repl: In the graph visualizer add no. of nodes on dotted edges

- kore/app/exec/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Rewrite/Strategy.hs
- kore/test/Test/Kore/Reachability/Prove.hs
Fixes #2848
- March 28
---
-   [ ] **Clean up.** The changes are already clean. Clean up …
> Add execute-to-branch option

- kore/src/Logic.hs
Fixes #3052
Re-exports `Control.Monad.Trans` and `Control.Monad` from `Logic`.
Done.
---
- …
> Re-export Control.Monad from Logic

- scripts/integration-k.sh
We're not actively working on --simplifierx anymore, so I'm removing the job which is just bloating CI right now.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue …
> Remove simplifierx job from CI

- kore/src/Kore/Log/WarnStuckClaimState.hs
> Better stuck claim messages

- kore/app/exec/Main.hs
- kore/src/Kore/Simplify/Data.hs
> Kore-server: dedicated initalization procedure

- kore/src/Kore/Log/KoreLogOptions.hs
> KoreLogOptions: improve help message

- kore/test/Test/Kore/Parser/Lexer.hs
Fixes #3022
Adds a test for the previously-faulting unicode code point.
Done.
---
-   [x] …
> Add 10ffff test

- kore/app/exec/Main.hs
- kore/app/share/GlobalMain.hs
- kore/kore.cabal
- nix/kore.nix.d/kore.nix
> Use exec hash to identify versioning issues

- kore/kore.cabal
Fixes different version of `hashable` in Cabal build producing inconsistent test results across cabal, stack & nix builds
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the …
> Pin hashable version across all the builds

- .github/workflows/test.yml
Fixes #nnnn
For the performance job: Checks whether all differences in the statistics table (markdown) are `0` or start by `0.00`, and skips posting a message on the PR if so. 
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing …
> omit mem statistics when all diffs under 1%

- kore/test/Test/Kore.hs
- kore/test/Test/Kore/Exec.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
We have removed `TestLog` from the `Test.Kore` module, which prevented us from progressing in the implementation of the solution to the SMT specialization task, and have substituted it with `LoggerT` instead. This also reduced the amount of code in the test suite.
Test suite.
---
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is …
> Remove TestLog

- .github/workflows/release.yml
- .github/workflows/update.yml
This should fix the failing CI check when merging into master
> Fix CI Nix materialization check on release

- kore/app/check-functions/Main.hs
- kore/app/exec/Main.hs
- kore/app/match-disjunction/Main.hs
- kore/app/repl/Main.hs
- kore/app/rpc/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/JsonRpc.hs
- kore/src/Kore/Simplify/API.hs
- kore/src/Kore/Simplify/Exists.hs
- kore/src/Kore/Simplify/Simplify.hs
- kore/test/Test/Kore/Builtin/Builtin.hs
- kore/test/Test/Kore/Exec.hs
- kore/test/Test/Kore/Rewrite/Function/Integration.hs
- kore/test/Test/Kore/Rewrite/MockSymbols.hs
- kore/test/Test/Kore/Simplify/Exists.hs
Fixes [#3172](https://github.com/runtimeverification/haskell-backend/issues/3172)
> Remove simplifierX switch

- Makefile
- kore/Makefile
This adds targets for using a local `hoogle` to the `Makefile`.
`hoogle` must be installed (e.g., `cabal install hoogle`) for this to work.
* `make hoogle-data` creates a hoogle database from haddock documentation
(will build and run `haddock` unless it has been run before, uses `.stack-work-haddock` work directory)
* `make hoogle` prompts the user for a `Query` and runs it:
```
$ make hoogle
Hoogle 5.0.18.3, https://hoogle.haskell.org/
Query:a -> [a]
Prelude repeat :: a -> [a]
Data.List repeat :: a -> [a]
GHC.List repeat :: a -> [a]
GHC.OldList repeat :: a -> [a]
Data.List.Compat singleton :: a -> [a]
Test.QuickCheck shrinkNothing :: a -> [a]
Test.QuickCheck.Arbitrary shrinkNothing :: a -> [a]
Distribution.Compat.Prelude.Internal repeat :: a -> [a]
Hedgehog.Internal.Prelude repeat :: a …
```
> Hoogle targets in Makefile

- kore/test/Test/Kore/Simplify/IntegrationProperty.hs
Addresses #3244 (work-around)
The simplifier integration test is run with a time-out of 30 seconds for each test case (default is 100 cases). If simplification times out (i.e., hangs), the generated pattern is printed out and the test case discarded.
Example output (from an actual run on my machine):
```
kore> test (suite: kore-test)
WARNING: unable to simplify pattern
\and{#String{}}(
/* term: */
/* Spa */
\not{#String{}}(
/* Spa */
\not{#String{}}(
/* D Spa */
\or{#String{}}(
/* Spa */
\iff{#String{}}(
/* Spa */
\or{#String{}}(
/* Spa */
\or{#String{}}(
/* Spa */
\nu{}(
Jf:#String{},
/* Spa */
\not{#String{}}(/* Fl Fn D Sfa Cl */ "")
),
/* Spa */
\exists{#String{}}(
g:subSort{},
/* Fl Fn D Sfa Cl */
"\U0007334a\U0002e1d9\U00063197\U000c057c"
)
),
/* Spa */
\implies{#String{}}(
/* Spa */ …
```
> Race simplifier integration test against 30sec timeout thread

- kore/src/Kore/Log.hs
> Handle incorrect log path for `--bug-report` option

- .github/workflows/profiling.yaml
> Using action runner permissions token for gh tool

- .github/workflows/profiling.yaml
This should fix the `gh issue comment` problem, and run with code from PRs
> Hotfix: check out local code to use before profiling run

- src/main/kore/prelude.kore
- test/kprove-hangs/test-spec.k.out.golden
Needed for https://github.com/runtimeverification/k/pull/2963
---
-   [ ] **Clean up.** The …
> Make append functional

- .github/workflows/kevm-performance-test.yaml
Part of #3323  (fixing syntax)
> yaml syntax fix

- .github/workflows/kevm-performance-test.yaml
...to align trigger string and K version regex introduced in #3339
> HOTFIX change trigger string for KEVM perf run

- .github/workflows/update.yml
- kore/src/Changed.hs
> .github/update: make sure after formatting, CI still runs

- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Rewrite/RewriteStep.hs
- kore/src/Kore/Rewrite/Step.hs
- kore/src/Kore/Simplify/Application.hs
Partially fixes #3325
The 1st leg of the Simplifier monomorphization.
Modules affected:
* `Kore.Reachability.Prove`
* `Kore.Rewrite.RewriteStep`
* `Kore.Rewrite.Step`
* `Kore.Simplify.Application`
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests …
> Monomorphization of Simplifier, leg #1

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update.yml
> .github/: switch to new cachix system

- kore/src/Kore/Rewrite/Axiom/EvaluationStrategy.hs
- kore/src/Kore/Simplify/Simplify.hs
Here are changes from one commit of big PR #3228 which was not aceepted as a whole but this part was decided to be accepted.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the …
> Remove AcceptsMultipleResults

- kore/src/Kore/Internal/Predicate.hs
- kore/src/Kore/Internal/TermLike/TermLike.hs
A few redundant instance constraints have crept in. Remove them.
Fixes #nnnn
---
-   [ ] …
> Remove some redundant instance constraints

- kore/src/Kore/Exec.hs
- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/State.hs
- kore/test/Test/Kore/Reachability/Prove.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
> Transfer not simplified claims to applyClaim

- kore/src/Kore/Builtin/AssociativeCommutative.hs
- kore/test/Test/Kore/Builtin/Set.hs
Use `HashSet.toMap` (O(1)) instead of converting the `HashSet` to a list and then to a `HashMap` (O(n)).
Fixes #nnnn
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported …
> Remove keys faster

- kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
- kore/src/Kore/Builtin/Builtin.hs
- kore/src/Kore/Builtin/EqTerm.hs
- kore/src/Kore/Builtin/Map.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Reachability/Claim.hs
- kore/src/Kore/Rewrite/Function/Evaluator.hs
- kore/src/Kore/Rewrite/Rule/Simplify.hs
- kore/src/Kore/Simplify/And.hs
- kore/src/Kore/Simplify/AndTerms.hs
- kore/src/Kore/Simplify/Application.hs
- kore/src/Kore/Simplify/Ceil.hs
- kore/src/Kore/Simplify/Condition.hs
- kore/src/Kore/Simplify/Equals.hs
- kore/src/Kore/Simplify/Exists.hs
- kore/src/Kore/Simplify/Iff.hs
- kore/src/Kore/Simplify/Implies.hs
- kore/src/Kore/Simplify/In.hs
- kore/src/Kore/Simplify/Not.hs
- kore/src/Kore/Simplify/OrPattern.hs
- kore/src/Kore/Simplify/Pattern.hs
- kore/src/Kore/Simplify/Predicate.hs
- kore/src/Kore/Simplify/Predicate.hs-boot
- kore/src/Kore/Simplify/SubstitutionSimplifier.hs
- kore/src/Kore/Unification/SubstitutionSimplifier.hs
- kore/src/Kore/Unification/UnifierT.hs
- kore/test/Test/Kore/Rewrite/Rule/Simplify.hs
- kore/test/Test/Kore/Unification/Unifier.hs
Fixes #3325
The 5th leg of the Simplifier monomorphization and specialization.
Modules affected:
`Kore.Builtin.AssocComm.CeilSimplifier`
`Kore.Builtin.Builtin`
`Kore.Builtin.Map`
`Kore.Exec`
`Kore.Reachability.Claim`
`Kore.Rewrite.Function.Evaluator`
`Kore.Rewrite.Rule.Simplify`
`Kore.Simplify.And`
`Kore.Simplify.AndTerms`
`Kore.Simplify.Application`
`Kore.Simplify.Ceil`
`Kore.Simplify.Condition`
`Kore.Simplify.Equals`
`Kore.Simplify.Exists`
`Kore.Simplify.Iff`
`Kore.Simplify.Implies`
`Kore.Simplify.In`
`Kore.Simplify.Not`
`Kore.Simplify.OrPattern`
`Kore.Simplify.Pattern`
`Kore.Simplify.Predicate`
`Kore.Simplify.SubstitutionSimplifier`
`Kore.Unification.SubstitutionSimplifier`
`Kore.Unification.UnifierT`
---
The author performs the actions on the checklist. The reviewer evaluates the work …
> Monomorphization and specialization of Simplifier, leg 5

- kore/src/Kore/Log.hs
- kore/src/Kore/Log/DebugAppliedRewriteRules.hs
- kore/src/Kore/Log/DebugAttemptedRewriteRules.hs
- kore/src/Kore/Log/KoreLogOptions.hs
- kore/src/Kore/Rewrite/RewriteStep.hs
- kore/src/Kore/Rewrite/RulePattern.hs
- kore/src/Kore/Rewrite/Step.hs
- kore/test/Test/Kore/Rewrite/RewriteStep.hs
> Add `--debug-rewrite` options

- flake.nix
> Fix (again) wrapProgram --prefix PATH

- kore/app/repl/Main.hs
- kore/kore.cabal
- kore/src/Kore/Exec.hs
- kore/src/Kore/Log/Registry.hs
- kore/src/Kore/Log/WarnStepTimeout.hs
- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Simplify/Simplify.hs
- kore/src/Log.hs
- kore/src/SMT.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
- nix/kore-ghc8107.nix.d/kore.nix
- nix/kore-ghc923.nix.d/kore.nix
> Add step timeout for repl

- kore/app/exec/Main.hs
- kore/app/repl/Main.hs
- kore/app/share/GlobalMain.hs
- kore/src/Kore/Exec.hs
- kore/src/Kore/Log/WarnStuckClaimState.hs
- kore/src/Kore/Reachability/Claim.hs
- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Repl.hs
- kore/test/Test/Kore/Reachability/MockAllPath.hs
- kore/test/Test/Kore/Reachability/OnePathStrategy.hs
- kore/test/Test/Kore/Reachability/Prove.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- test/assume/Makefile
- test/bottom-lhs/Makefile
Fixes #3411 
Add a flag --allow-vacuous which enables discharging #Bottom paths as #Top.
---
- …
> Add --allow-vacuous, fixed

- kore/app/repl/Main.hs
- kore/kore.cabal
- kore/src/Kore/Exec.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
- nix/kore-ghc8107.nix.d/kore.nix
- nix/kore-ghc923.nix.d/kore.nix
Work on https://github.com/runtimeverification/haskell-backend/issues/3417
---
-   [ ] **Clean …
> Add time printing command/option for steps in repl

- kore/src/Kore/Internal/SideCondition.hs
Fixes #3454
This should improve KEVM (and other semantics which use large, concrete maps or sets) performance significantly.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the …
> Fix strictness bug in definedness check

- docs/2022-07-18-JSON-RPC-Server-API.md
- kore/app/exec/Main.hs
- kore/app/repl/Main.hs
- kore/app/share/GlobalMain.hs
- kore/kore.cabal
- kore/src/Kore/Exec.hs
- kore/src/Kore/Exec/GraphTraversal.hs
- kore/src/Kore/JsonRpc.hs
- kore/src/Kore/Log/WarnStepTimeout.hs
- kore/src/Kore/Reachability/Prove.hs
- kore/src/Kore/Repl.hs
- kore/src/Kore/Repl/Data.hs
- kore/src/Kore/Repl/Interpreter.hs
- kore/src/Kore/Repl/Parser.hs
- kore/src/Kore/Repl/State.hs
- kore/src/Kore/Rewrite/Timeout.hs
- kore/test/Test/Kore/Exec.hs
- kore/test/Test/Kore/Reachability/Prove.hs
- kore/test/Test/Kore/Repl/Interpreter.hs
- kore/test/Test/Kore/Repl/Parser.hs
- nix/kore-ghc8107.nix.d/kore.nix
- nix/kore-ghc923.nix.d/kore.nix
> Moving average timeouts

- docs/2022-07-18-JSON-RPC-Server-API.md
- kore/src/Kore/JsonRpc.hs
- kore/test/Test/Kore/Reachability/Claim.hs
> Fix check-implication output 3

- design-decisions/2018-07-25 Attributes as patterns.md
Fixes: https://github.com/runtimeverification/k/issues/3137
---
-   [ ] **Clean up.** The …
> Update kore design documentation

- test/kevm-optimism-invariant/Makefile
- test/kevm-optimism-invariant/test-optimism-invariant.sh
This should fix the flaky behavior of the optimism test.
---
-   [ ] **Clean up.** The changes …
> Change SMT timeout for optimism test

- kore/src/Kore/JsonRpc.hs
> kore-rpc Catch any runtime exception and send as error

- kore/src/Kore/Reachability/Prove.hs
We previously had an invariant that when execution (or a proof) branches, none of the branch states would be `Stuck`. Since modifying the prover logic to disallow vacuous claims (#3411) this invariant does not hold any more.
Remove the invariant check and return stuck states within the branch states (they will be discovered and handled in the next step). Also, prune `Proven` states from the branch and terminate if all branch states were already `Proven`.
Fixes #3540
> Remove check for stuck states from branch case in prover graph traversal

- kore/src/Kore/Unification/NewUnifier.hs
Problem: Kore-exec fails with "Cannot convert a denormalized substitution to a map!".
Solution: When appending one condition to another we can get condition with denormalized substitution which leads to the error. Therefore if we get condition with denormalized substitution we need to simplify this condition before converting substitution to `Map`.
Fixes #3538
> [#3538] Fix converting substitution to `Map`

- .github/workflows/release.yml
> Switch to new GH Runner based dependency updater

- kore/app/rpc/Main.hs
Previously, when `kore-rpc` was stopped due to receiving `SIGINT` (e.g., by pressing `^C`) it would print an error message. This change catches the `UserInterrupt` exception resulting from `SIGINT` and shuts down with `ExitSuccess`, printing a log message at `INFO` level.
Fixes #3570 
Related to https://github.com/runtimeverification/pyk/issues/317 
---
-   [ ] **Documentation.** Write documentation for new functions. Update …
> Terminate kore-rpc gracefully when receiving SIGINT

- kore/src/Kore/JsonRpc.hs
- kore/src/Kore/Log/DecidePredicateUnknown.hs
Expose `externaliseDecidePredicateUnknown :: DecidePredicateUnknown -> PatternJson.KoreJson` to be used in `kore-rpc-booster`
> Factor-out `DecidePredicacteUnknwon -> KoreJson` into a function

- docs/profiling.md
> mention some RTS options in profiling.md

- flake.nix
- scripts/performance-tests-kevm.sh
Fixes #3855 
Follow-up in K: https://github.com/runtimeverification/k/pull/4335
> Expose `booster-dev`

- kore/src/Kore/Log.hs
The re-perusing of `--log-format oneline` for contextual logs has broken some ad-hoc parsers for in `pyk`. This PR enables the one line rendered in `kore-exec` again.
There's minor code duplication between `renderOneLinePrettyLegacy` and `renderStandardPretty`. I'd argues this is not worth refactoring.
> Add one-line legacy log printer

- .github/workflows/release.yml
looks like we maybe need to explicitly add `draft-release` to the needs section of `update-depends`??
> Fix release CI job

- booster/library/Booster/Pattern/Rewrite.hs
> Filter the requires of rewrites again, after simplifications
