src/main/haskell/language-kore/src/Data/Kore/AST.hs
src/main/haskell/language-kore/src/Data/Kore/ASTPrettyPrint.hs
src/main/haskell/language-kore/src/Data/Kore/Parser/ParserImpl.hs
src/main/haskell/language-kore/src/Data/Kore/Unparser/Unparse.hs
src/main/haskell/language-kore/test/parser/Data/Kore/ASTGen.hs
src/main/haskell/language-kore/test/parser/Data/Kore/Parser/ParserTest.hs
src/test/resources/expected/test-pattern-11.kore.golden
src/test/resources/test-exception-20.kore

* \mem -> \in rename
* Changed \in to accept generic patterns on the first position instead of only variables.

Bring the Haskell Kore code in sync with the docs.

---

src/main/haskell/language-kore/app/parser/GlobalMain.hs
src/main/haskell/language-kore/app/parser/Main.hs
src/main/haskell/language-kore/package.yaml

I added a --version flag to kore-parser and moved the common elements of the kore-parser main module to a new module GlobalMain. GlobalMain exports a function mainGlobal that takes an arbitrary command line parser and combines it with it's predefined parser, handles its global flags and returns all of the parsed options.
I wasn't sure how to expand the project directory structure, but I'm guessing GlobalMain.hs is not in the right place.
In order to print the version information in the package.yaml I would need to add some options to that file that would require setting a minimum version of stack (v1.7) so I have held off on that for now.

global main module and --version flag

---

src/main/haskell/kore/package.yaml
src/main/haskell/kore/src/Data/Functor/Impredicative.hs
src/main/haskell/kore/src/Kore/AST/Builders.hs
src/main/haskell/kore/src/Kore/AST/BuildersImpl.hs
src/main/haskell/kore/src/Kore/AST/Common.hs
src/main/haskell/kore/src/Kore/AST/Kore.hs
src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/Condition.hs

PolyKinds makes many of our constructors much more polymorphic than
intended. The extension is only actually required in
Data.Functor.Impredicative.
Fixes: #163
---

Disable PolyKinds by default

---

src/main/haskell/kore/app/prover/Main.hs
src/main/haskell/kore/app/share/GlobalMain.hs
src/main/haskell/kore/package.yaml
src/main/haskell/kore/src/Logic/Matching/Prover/Command.hs
src/main/haskell/kore/src/Logic/Matching/Prover/Repl.hs
src/main/haskell/kore/src/Logic/Matching/Prover/Repl/Class.hs
src/main/haskell/kore/src/Logic/Matching/Rules/Kore.hs
src/main/haskell/kore/src/Logic/Proof/Hilbert.hs
src/main/haskell/kore/test/Test/Logic/Matching/Rules/Kore/ProofAssistant.hs
src/main/haskell/kore/test/Test/Logic/Matching/Rules/OnePlusOne.hs

improvements:
- Reimplemented the prover repl to utilize monad transformers for a more painless integration of stateful computation on matching logic proofs.
- added undo functionality
Further work:
- move functionality (to reorder proof claims) should be a minor addition.
- Testing.  I have not added tests for the user interface or the undo functionality.
- updating the `prover_repl.md`
---

Control flow overhaul of Prover repl and addition of `Undo`  prover command

---

design-decisions/2018-07-25 Attributes as patterns.md

Add a 'Decision' heading.

---

src/main/haskell/kore/src/Kore/Parser/ParserImpl.hs
src/main/haskell/kore/test/Test/Kore/Parser/Parser.hs
src/test/resources/expected/test-alias-10.kore.golden
src/test/resources/expected/test-alias-11.kore.golden
src/test/resources/expected/test-alias-12.kore.golden
src/test/resources/test-alias-10.kore
src/test/resources/test-alias-11.kore
src/test/resources/test-alias-12.kore

`Kore.Parser.ParserImpl.mlConstructorRemainderParser` is modified so that it
does not take a continuation. Instead, it parses all the matching logic
constructors itself. It takes a level parameter which is used to determine if a
particular constructor should be rejected. Dropping the continuation ensures
that matching logic constructors are always parsed by the same code path, which
fixes the parsing of domain values in aliases.
---

Always parse matching logic constructors the same way

---

src/main/haskell/kore/app/parser/Main.hs
src/main/haskell/kore/src/Kore/ASTVerifier/PatternVerifier.hs
src/main/haskell/kore/src/Kore/ASTVerifier/SentenceVerifier.hs
src/main/haskell/kore/src/Kore/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/Bool.hs
src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/Int.hs
src/main/haskell/kore/src/Kore/Proof/Unification.hs
src/main/haskell/kore/src/Logic/Matching/Rules/Kore.hs
src/main/haskell/kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/PatternVerifier.hs
src/test/resources/expected/test-bool-1.kore.golden
src/test/resources/expected/test-bool-4.kore.golden
src/test/resources/expected/test-dv-1.kore.golden
src/test/resources/expected/test-dv-2.kore.golden
src/test/resources/expected/test-int-1.kore.golden
src/test/resources/expected/test-int-5.kore.golden
src/test/resources/test-bool-1.kore
src/test/resources/test-bool-4.kore
src/test/resources/test-dv-1.kore
src/test/resources/test-dv-2.kore
src/test/resources/test-int-1.kore
src/test/resources/test-int-5.kore

Sort and symbol verification are implemented in master. This PR adds pattern verification and parsing, to decode builtin domain values. The actual implementation of the builtin functions will follow in another pull request.
@u-- : This should be what you need to get started on `MAP`.
---

Builtin pattern verifiers

---

src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/test/Test/Kore/Builtin/KEqual.hs

Reimplementing KEQUAL hooks using \Equals

---

stack.yaml

The SMT tests require Z3 to be installed. By adding it to nix.packages, Stack
will ensure it is provided automatically for Nix users.
---

stack.yaml: Include Z3 in nix.packages

---

src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Merging/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Data.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Exists.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Bool.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
src/main/haskell/kore/test/Test/Kore/Builtin/KEqual.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/And.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Exists.hs
src/main/haskell/kore/test/Test/Kore/Step/Step.hs

Any error that the simplifier would catch has already been detected during the
well-formedness check. Therefore, it does not make sense to have complicated
error handling.
---

Simplifier cannot return error

---

src/main/haskell/kore/src/Kore/Builtin/Bool.hs
src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/Int.hs
src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/src/Kore/Builtin/List.hs
src/main/haskell/kore/src/Kore/Builtin/Map.hs
src/main/haskell/kore/src/Kore/Builtin/Set.hs
src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Simplifier.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/src/Kore/Variables/Fresh.hs
src/main/haskell/kore/test/Test/Kore/Builtin/List.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Step.hs

Why this change is needed:
Our stepping works like this:
1. Wrap axiom variables and pattern variables in `StepperVariables`
2. Unify the pattern with the axiom LHS and get a substitution+predicate
3. Apply the substitution to the axiom RHS and the (axiom predicate + all other predicates)
4. Check that the substitution removed all axiom variables
5. Unwrap the remaining ones
6. Simplify the predicate and the RHS
So, with the current code, simplification works on variables.
However, in order to support map unification, in particular, in order to support using a variable (that gets resolved in another place) as the key we want to change the second step to (small lies to keep things simple)
2.a. Unify the pattern with the LHS and get a substitution + predicate.
2.b. Apply the substitution to …

Generalize stepper variables.

---

src/main/haskell/kore/src/Kore/AST/Common.hs
src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/src/Kore/Builtin/Map.hs
src/main/haskell/kore/src/Kore/IndexedModule/MetadataTools.hs
src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Merging/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Merging/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs-boot
src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/src/Kore/Step/Substitution.hs
src/main/haskell/kore/src/Kore/Step/Substitution.hs-boot
src/main/haskell/kore/src/Kore/Unification/Procedure.hs
src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/DomainValue.hs

As discussed in the standup meeting on Tue 9 Oct 2018, there are three main cases:
1. both maps concrete,
2. one concrete map, one framed map
3. both maps framed
This pull request addresses the first two, which are at least enough for concrete execution.
---

Unify builtin Maps

---

src/main/haskell/kore/src/Kore/Builtin/Map.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs

The commutativity of MAP.concat must be observed so that we can unify
user-defined rules with framing variables, where the user may concatenate the
concrete map and the framing variable in either order.
---

Kore.Builtin.Map.unify: Commute arguments of MAP.concat

---

.gitignore
.stylish-haskell.yaml
Makefile
include.mk
scripts/check-stylish-haskell.sh
scripts/git-assert-clean.sh
scripts/git-rebased-on.sh
src/main/haskell/kore/src/Kore/ASTPrettyPrint.hs
src/main/haskell/kore/src/Kore/SMT/Config.hs
src/main/haskell/kore/src/Kore/SMT/SMT.hs
src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/src/Kore/Step/Substitution.hs-boot
src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
src/main/haskell/kore/test/Test/Kore/SMT/SMT.hs
src/main/haskell/kore/test/Test/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
src/main/k/working/Makefile
src/main/k/working/function-evaluation-demo/Makefile
src/main/k/working/imp-concrete-heat-cool/Makefile
src/main/k/working/imp-monosorted/Makefile

Including the Jenkins script in the repository allows us to track changes in
Git. Contributors may also run the script to check their code before making a
pull request.
This will also enforce the condition, mentioned in the Coding Standards document, that the Git history be linear.
Once merged, I would change the Jenkins configuration to call `scripts/jenkins.sh`.
---

Jenkins script

---

Makefile
include.mk
scripts/check-stylish-haskell.sh

The `stylish` target runs `stylish-haskell` on every Haskell source file in the
repository. The `check` target now uses the `stylish` target in its
style-conformance test. The `check` target now suggests solutions to the errors
it detects.
---

Makefile: Add `stylish` target

---

src/main/haskell/kore/src/Kore/ASTHelpers.hs
src/main/haskell/kore/src/Kore/MetaML/AST.hs
src/main/haskell/kore/src/Kore/Predicate/Predicate.hs
src/main/haskell/kore/src/Kore/Step/PredicateSubstitution.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Exists.hs
src/main/haskell/kore/src/Kore/Unification/SubstitutionNormalization.hs
src/main/haskell/kore/src/Kore/Variables/Free.hs

The new function `freePureVariables` is a simple traversal down the tree,
tracing the bound variables and recording those that occur free.
Note: The implementation is slightly different than I outlined in the associated Trello card, but it is morally the same.
---

Kore.Variables.Free: Replace `pureFreeVariables` with `freePureVariables`

---

Makefile

When I updated the Jenkins builder a few days ago, I also wanted to check that pull request history is linear on top of master, i.e. rebased and not merged. At that time the check was failing, but I did not understand why!
This pull request reinstates the linear-history check. This pull request will fail to build (at least the first time) until I change the Jenkins configuration. That change is backwards-compatible.
---

Ensure that branch is rebased onto master

---

src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
src/main/haskell/kore/test/Test/Kore/Step/Step.hs

Without explicit kind signatures, the type parameters to StepProof were being
swapped in some places.
---

Kore.Step.BaseStep.StepProof: Add explicit kind signatures

---

include.mk

The K submodule reflog tracks the last time the submodule was
changed. Un-committed changes in the submodule will not trigger a rebuild, but
making changes directly in a submodule is a bad idea anyway because Git has a
tendency to casually delete unpushed submodule commits.
---

include.mk: Use the K submodule reflog as a timestamp

---

include.mk
src/main/k/working/function-evaluation-demo/Makefile
src/main/k/working/imp-concrete-heat-cool/Makefile
src/main/k/working/imp-concrete-state/Makefile
src/main/k/working/imp-monosorted/Makefile
src/main/k/working/tests/strict/Makefile

Make 4 introduces some short-hand notation for the `$(shell ...)`
command. Unfortunately, the default Make on macOS is Make 3, which does not
recognize the notation.
@virgil-serbanuta Could you double-check that this works for you?
---

Don't use Make 4 short-hand notation

---

Makefile

`find` expects its first argument to be a search path. GNU Find allows the
search path to be omitted, in which case it is implied to be `.`. macOS Find
does not allow the search path to be omitted.
---

Makefile: Be strict about `find` invocation

---

include.mk
src/main/k/working/function-evaluation-demo/Makefile
src/main/k/working/imp-concrete-heat-cool/Makefile
src/main/k/working/imp-concrete-state/Makefile
src/main/k/working/imp-monosorted/Makefile
src/main/k/working/tests/strict/Makefile

Running K through nailgun causes problems when multiple builds using multiple
versions of K want to run on the same Jenkins instance.
---

Invoke kompile and krun without nailgun

---

src/main/haskell/kore/src/Kore/Builtin/List.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs

Make list unification return ExpandedPattern.bottom instead of Failure

---

src/main/haskell/kore/bench/exec/Main.hs
src/main/haskell/kore/package.yaml

For each K definition in src/main/k/working, shell out to kompile, kast,
and krun to benchmark each test.
---

package.yaml, bench/exec/Main.hs: A first kore execution benchmark suite

---

Makefile
include.mk
src/main/haskell/kore/src/Kore/MetaML/Unlift.hs
src/main/k/in-progress/tests/collections/list/list-unify-any-elem/Makefile
src/main/k/in-progress/tests/collections/list/list-unify-first-elem/Makefile
src/main/k/in-progress/tests/collections/list/list-unify-framing-variable-left/Makefile
src/main/k/in-progress/tests/collections/list/list-unify-framing-variable-right/Makefile
src/main/k/in-progress/tests/collections/list/list-unify-last-elem/Makefile
src/main/k/in-progress/tests/collections/map/map-unify-framing-variable/Makefile
src/main/k/in-progress/tests/collections/set/set-unify-framing-variable/Makefile
src/main/k/working/imp-map/Makefile
src/main/k/working/search/Makefile
src/main/k/working/tests/collections/list-unify-concrete/Makefile
src/main/k/working/tests/collections/map-unify-concrete/Makefile
src/main/k/working/tests/collections/set-unify-concrete/Makefile

This pull request fixes various stale Makefiles after #303.
The `stylish` Makefile target is updated so that it fails if a Haskell source file cannot be parsed. A parse error due to ViewPatterns is fixed.
---

Fix Makefiles

---

.gitignore
stack.yaml

Among various package updates, LTS Haskell updates to GHC 8.4.4 with various bugfixes.
---

LTS Haskell 12.16

---

src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/List.hs
src/main/haskell/kore/src/Kore/Builtin/Map.hs
src/main/haskell/kore/src/Kore/Builtin/Set.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Bottom.hs
src/main/haskell/kore/src/Kore/Step/Simplification/CharLiteral.hs
src/main/haskell/kore/src/Kore/Step/Simplification/DomainValue.hs
src/main/haskell/kore/src/Kore/Step/Simplification/StringLiteral.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Top.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Variable.hs
src/main/haskell/kore/test/Test/Kore.hs
src/main/haskell/kore/test/Test/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Exists.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Floor.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Forall.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplifier.hs

`merge` takes advantage of the idempotency property of disjunction to eliminate
identical patterns from disjunctions. Only patterns that are syntactically
identical are de-duplicated. (Simplification should eventually rewrite
semantically-equivalent patterns into syntactically identical ones.)
---

Kore.Step.OrOfExpandedPattern.merge: Use idempotency property

---

docs/hooks.md
src/main/haskell/kore/src/Kore/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/src/Kore/Builtin/String.hs
src/main/haskell/kore/test/Test/Kore/Builtin/KEqual.hs
src/main/haskell/kore/test/Test/Kore/Builtin/String.hs

I only added `STRING.lt` since this seems to be the only required builtin by `evm-semantics`, at least for now.
It is odd that strings are not between `"`. Should add a card to investigate whether this is a problem in the frontend or here.
---

Add KEQUAL.ite and STRING.lt builtins

---

src/main/haskell/kore/src/Kore/AST/Sentence.hs
src/main/haskell/kore/src/Kore/Attribute/Parser.hs
src/main/haskell/kore/test/Test/Kore/Attribute/Parser.hs

This pull request adds an `instance ParseAttributes Attributes` to recover the list of `Attributes` after indexing a module.
---

Recover parsed Attributes

---

src/main/haskell/kore/app/exec/Main.hs

`--strategy=any` is the default option to `kore-exec`. Using any search options invokes `--strategy=all`.
See also: https://trello.com/c/Zci0Vnyj
---

kore-exec: Do not explore entire state space for simple execution

---

docs/hooks.md
src/main/haskell/kore/src/Kore/Builtin/Int.hs
src/main/haskell/kore/src/Kore/Builtin/String.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Int.hs
src/main/haskell/kore/test/Test/Kore/Builtin/String.hs

Added an implementation for `INT.emod` and a few `STRING.` new builtins:
- `concat`
- `length`
- `find`
- `substr`
- `string2base`
- `string2int`
Updated docs. Added tests. I did not add quickcheck properties since they did not seem to add any real value.
Note that I added these builtins since these are required by `evm-semantics`.
---

Added a few STRING and INT builtins needed for evm

---

src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Condition/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Merging/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Search.hs
src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Data.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/src/Kore/Step/Simplification/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Predicate.hs
src/main/haskell/kore/src/Kore/Step/Simplification/PredicateSubstitution.hs
src/main/haskell/kore/src/Kore/Step/Substitution.hs
src/main/haskell/kore/src/Kore/Unification/Procedure.hs
src/main/haskell/kore/src/Kore/Unification/SubstitutionNormalization.hs
src/main/haskell/kore/src/Kore/Unification/UnifierImpl.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/Condition/Evaluator.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
src/main/haskell/kore/test/Test/Kore/Step/Substitution.hs
src/main/haskell/kore/test/Test/Kore/Unification/SubstitutionNormalization.hs
src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs

`PredicateSubstitution` is a special case of `Predicated`.
---

Refactor PredicateSubstitution

---

include.mk
src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/bench/exec/Main.hs
src/main/haskell/kore/src/Kore/Attribute/Constructor.hs
src/main/haskell/kore/src/Kore/Attribute/Function.hs
src/main/haskell/kore/src/Kore/Attribute/Functional.hs
src/main/haskell/kore/src/Kore/Attribute/Hook.hs
src/main/haskell/kore/src/Kore/Attribute/Injective.hs
src/main/haskell/kore/src/Kore/Attribute/Smtlib.hs
src/main/haskell/kore/src/Kore/Attribute/SortInjection.hs
src/main/haskell/kore/src/Kore/Exec.hs
src/main/haskell/kore/src/Kore/IndexedModule/IndexedModule.hs
src/main/haskell/kore/src/Kore/Step/Search.hs
src/main/haskell/kore/src/Kore/Step/StepperAttributes.hs
src/main/haskell/kore/src/SimpleSMT.hs
src/main/haskell/kore/test/Test/Kore/Exec.hs
src/main/haskell/kore/test/Test/Tasty/HUnit/Extensions.hs

Before I write tests, I would just like to make sure I am on the right track with the way the `exec` function in `src/Kore/Exec.hs` works. Is this the right way to expose concrete execution?
I pushed some of `app/exec/Main.hs` down into `src/Kore/Exec.hs` so that we can expose concrete execution as a library call. Then the concrete execution benchmarks don't have to shell out to krun which in turn shells out to kore-exec.
---

Concrete execution as a library

---

src/main/python/debugger.py

Fix line splitting error in debugger

---

stack.yaml

This pull request removes some unused extra dependencies and updates the Stack resolver to LTS Haskell 12.21.
---

LTS Haskell 12.21

---

src/main/haskell/kore/Makefile
src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/src/Kore/Exec.hs

Added --depth to kprove for the haskell backend.

---

src/main/haskell/kore/src/Kore/ASTPrettyPrint.hs
src/main/haskell/kore/src/Kore/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/Error.hs
src/main/haskell/kore/src/Kore/Unparser.hs

Move `notImplementedInternal` from `Kore.Builtin` to `Kore.Builtin.Error` to
break cycles involving `Kore.Unparser`.
---

Kore.Builtin.Error: Move notImplementedInternal here

---

src/main/haskell/kore/package.yaml

By default, we have been setting `+RTS -N -RTS`, which causes the GHC runtime
system (RTS) to spawn one thread per logical processor for the parallel garbage
collector. Having a large number of GC threads contending for memory bandwidth
is not efficient because the default allocation size is small (1 megabyte). The
default allocation size is increased to 32 megabytes (`-A32M`) to make better
use of the parallel garbage collector. An upper bound is placed so that there
will be no more than 8 GC threads (`-qn8`) to ensure that the number of threads
is appropriate to the new default allocation size.
This improves performance relative to the number of processors. On my laptop (4 cores) the improvement is a modest 15%, but performance improves on my desktop (16 cores) by 30%.
---

Select GHC options for RTS performance

---

src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/src/Kore/Exec.hs
src/main/haskell/kore/src/Kore/OnePath/Step.hs
src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Search.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/src/Kore/Unification/Procedure.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Map.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Set.hs
src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs
src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs

The test using "assertTermEqualsMulti" in Equals.hs highlights a bug in the equals simplification.
---

Unification returns an 'Or'

---

src/main/k/working/imp/Makefile
src/main/k/working/imp/prove/double-sum-spec.k
src/main/python/debugFilter.py

Double sum specification and debugger update

---

src/main/haskell/kore/src/Kore/Builtin/String.hs
src/main/haskell/kore/test/Test/Kore/Builtin/String.hs

I will add integration tests with my next PR ( https://trello.com/c/A1yfIgnB/409-correctly-sanitize-variables-in-exists-and-forall )
---

STRING.ord should return bottom if the input's length is not 1

---

Makefile
src/main/haskell/kore/src/Kore/ASTPrettyPrint.hs
src/main/haskell/kore/src/Kore/Domain/Builtin.hs
src/main/haskell/kore/src/Kore/Domain/External.hs
src/main/haskell/kore/src/Kore/Step/Error.hs
src/main/haskell/kore/src/Kore/Step/Pattern.hs
src/main/haskell/kore/src/Text/IndentingPrinter.hs

Avoid the scourge of missing module headers!
The `make haddock` target now fails if any modules are missing their Haddock header.
---

Check module headers on Jenkins

---

src/main/haskell/kore/src/Kore/AST/Pure.hs
src/main/haskell/kore/src/Kore/Attribute/Axiom/Concrete.hs
src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Attribute/Axiom/Concrete.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs

Function evaluator now refuses to apply function axioms marked with [concrete] to symbolic patterns (patterns containing a variable somewhere).
---

added [concrete] attribute for Kore rules

---

Makefile
include.mk

Program nprocs is not available by default on macOS. Ultimately, we need to
restructure the Makefile so that option -j works correctly, but for now we just
need to get Jenkins running again.
---

include.mk: Remove NPROCS

---

Makefile
include.mk

Allowing the user's environment to override K_DIST makes it much simpler to test
different versions of K with the Makefile.
---

include.mk: Allow overriding K_DIST from environment

---

src/main/haskell/kore/src/Kore/Step/Simplification/Or.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Or.hs
src/main/haskell/kore/test/Test/Kore/Unification/Substitution.hs
src/main/haskell/kore/test/Test/Terse.hs

The main contribution of this pull requests is a set of tests for `Or` simplification and a bug fix for a bug that they found.
The tests were written in "terse/tabular style". The `Test.Terse` module contains support functions for that style.
There's also an additional documentation test that explains the three kinds of `Kore.Unification.Substitution` values. 
---

Kore.Step.Simplification.Or: tests and bugfix

---

src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Builtin/KEqual.hs
src/main/haskell/kore/src/Kore/Builtin/Krypto.hs
src/main/haskell/kore/src/Kore/Builtin/List.hs
src/main/haskell/kore/src/Kore/Builtin/Map.hs
src/main/haskell/kore/src/Kore/Builtin/Set.hs
src/main/haskell/kore/src/Kore/Builtin/String.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Registry.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Step/MockSymbols.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs

This makes the code uniform enough that next I'll be able to replace `These` as a representation for a symbol's simplification code with a single BuiltinAndAxiomSimplifier, then I'll be able to treat ceils and applications in a uniform way.
---

Refactor the function evaluation code

---

src/main/haskell/kore/src/Kore/Builtin/Builtin.hs
src/main/haskell/kore/src/Kore/Step/Function/Data.hs
src/main/haskell/kore/src/Kore/Step/Function/Evaluator.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Comparators.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs

This fixes a bug where functions which were defined over a finite set, with an equation for each possible value, e.g.
```
f(a)=1
f(b)=2
```
were looping indefinitely. This is not the only possible case, but this was a very visible one.
What was happening:
Currently we don't have a way of specifying and using the fact that a function works on a limited set of values, unless the SMT already handles it (e.g. functions on booleans). Therefore, when evaluating such a function applied to a symbolic variable, e.g. `f(x)`, we would always get a remainder of the type `f(x) and (x!=a) and (x !=b) and ...`.
The function evaluator tried to resimplify all possible results, including the remainder, which meant that we would, again, try to re-evaluate `f(x)`.
There were three possible fixes:
1. Stop …

Fix functions defined on constants.

---

src/main/haskell/kore/src/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Or.lhs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Or.hs

`Kore.Step.Simplification.Equals.makeEvaluateFunctionalOr` requires that `Kore.Step.Simplification.Or.disjoinPredicates` disjoins predicates with inequal substitutions, so we do that by promoting the substitution to the predicate.
---

Disjoin predicates with inequal substitutions

---

src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/bench/exec/Main.hs
src/main/haskell/kore/src/Kore/Exec.hs
src/main/haskell/kore/test/Test/Kore/Exec.hs

While working on removing the global counter, I did some cleanup of `Kore.Exec`.
---

Cleanup Kore.Exec

---

src/main/haskell/kore/app/exec/Main.hs
src/main/haskell/kore/src/Kore/AST/Common.hs
src/main/haskell/kore/src/Kore/Exec.hs
src/main/haskell/kore/src/Kore/OnePath/Step.hs
src/main/haskell/kore/src/Kore/OnePath/Verification.hs
src/main/haskell/kore/src/Kore/Proof/Functional.hs
src/main/haskell/kore/src/Kore/Step/AxiomPatterns.hs
src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Function/EvaluationStrategy.hs
src/main/haskell/kore/src/Kore/Step/Function/Registry.hs
src/main/haskell/kore/src/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/src/Kore/Unification/Data.hs
src/main/haskell/kore/src/Kore/Unification/Substitution.hs
src/main/haskell/kore/src/Kore/Variables/Fresh.hs
src/main/haskell/kore/test/Test/Kore/Builtin/Builtin.hs
src/main/haskell/kore/test/Test/Kore/OnePath/Step.hs
src/main/haskell/kore/test/Test/Kore/OnePath/Verification.hs
src/main/haskell/kore/test/Test/Kore/Step/AxiomPatterns.hs
src/main/haskell/kore/test/Test/Kore/Step/BaseStep.hs
src/main/haskell/kore/test/Test/Kore/Step/ExpandedPattern.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/EvaluationStrategy.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Integration.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/UserDefined.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Application.hs
src/main/haskell/kore/test/Test/Kore/Step/Step.hs
src/main/haskell/kore/test/Test/Kore/Unification/Unifier.hs

The responsibilities of `SortedVariable` and `FreshVariable` are divided along clean lines in preparation to remove the global counter, which will involve rewriting the FreshVariable class.
`Kore.Step.BaseStep` is refactored so that variable renaming happens at the beginning of the step; this reduces the amount of state that must be threaded through the stepper. The only remaining complication is alpha-renaming, and that last complication will be removed also when I remove the global counter.
---

Clean up SortedVariable

---

src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/src/Kore/Step/Merging/ExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Merging/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/And.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndPredicates.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/src/Kore/Step/Simplification/In.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Pattern.hs
src/main/haskell/kore/src/Kore/Step/Substitution.hs
src/main/haskell/kore/src/Kore/Unification/Procedure.hs
src/main/haskell/kore/test/Test/Kore/Step/Function/Matcher.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/AndTerms.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/Substitution.hs

* Fix TODO - we now throw errors for x=f(x) substitutions.
---

Refactoring - make ceil evaluation return MultiOr

---

src/main/haskell/kore/package.yaml
src/main/haskell/kore/test/Driver.hs
src/main/haskell/kore/test/Test.hs

The test suite currently runs over 35,000 test cases; displaying all the
successful tests is never useful.
Due to a bug in tasty, the --hide-successes option only works if TERM=dumb is in
the environment. Therefore, we wrap the generated test driver to set that
variable.
---

Hide successful tests by default

---

src/main/haskell/kore/src/Kore/Step/MultiAnd.hs
src/main/haskell/kore/src/Kore/Step/OrOfExpandedPattern.hs
src/main/haskell/kore/src/Kore/Step/Simplification/AndPredicates.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Ceil.hs
src/main/haskell/kore/src/Kore/Step/Simplification/Equals.hs
src/main/haskell/kore/test/Test/Kore/Step/MultiAnd.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Ceil.hs
src/main/haskell/kore/test/Test/Kore/Step/Simplification/Equals.hs

* Make And usage explicit when computing and-of-ceil
* Throw an error when or-of-ceil contains a substitution
---

Fix some leftover thing from the last ceil-as-or refactoring.

---

src/main/haskell/kore/src/Kore/Step/BaseStep.hs
src/main/haskell/kore/src/Kore/Step/Step.hs
src/main/haskell/kore/test/Test/Kore/Step/Step.hs

Unification failures should produce an error, not silently attempt to execute
down other paths.
---

Kore.Step.Step.transitionRule: Do not silence unification failures

---

Makefile
include.mk
scripts/kevm-integration.sh
src/main/k/working/imp-concrete-heat-cool/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-concrete-state/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-map-strict/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-map-unify-strict/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-map-unify/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-map/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp-monosorted/tests/max-symbolic.search.final.output.golden
src/main/k/working/imp/tests/max-symbolic.search.final.output.golden
src/main/k/working/search/tests/initial.final.output.golden
src/main/k/working/search/tests/initial.one.output.golden
src/main/k/working/search/tests/initial.plus.output.golden
src/main/k/working/search/tests/initial.star.initial.output.golden
src/main/k/working/search/tests/initial.star.output.golden

---
This updates to the new syntax used by the frontend for `{_#Equals_}`.

k/working/*.golden: new syntax for `{_#Equals_}`

---

docs/2019-03-06-Equality-Axiom-Configuration-Splitting.md

I'll merge after the first approval.
This allows me to change this condition, which does not work for ceil-related axioms:
https://github.com/kframework/kore/blob/master/src/main/haskell/kore/src/Kore/Step/BaseStep.hs#L591
---

Design doc for configuration splitting for equality axioms.

---

kore/src/Kore/Step/Representation/MultiOr.hs
kore/src/Kore/Step/Simplification/Data.hs
kore/src/Kore/Step/Substitution.hs
kore/src/ListT.hs
kore/test/Test/Kore/Step/Simplification/PredicateSubstitution.hs

Add instances of `MFunctor` and `MMonad` for `ListT`, requiring a small change to the internal representation (this part is pretty technical). The new instances are nicer `BranchT` in the simplifier: the exposed interface is cleaner, and we can sequence effects to, e.g., abort unification the first time any branch fails.
Depends: #504 
---

Instances for ListT

---

docs/2018-11-08-Configuration-Splitting-Simplification.md
docs/glossary.md

@yzhang90 Thanks for pointing out the ceil(not) typo.
---

Add acronyms to glossary and fix typo in documentation.

---

kore/src/Kore/AST/MetaOrObject.hs
kore/src/Kore/AST/Pure.hs
kore/src/Kore/AST/PureToKore.hs
kore/src/Kore/AST/Sentence.hs
kore/src/Kore/IndexedModule/IndexedModule.hs
kore/test/Test/Kore/AST/PureToKore.hs

Extracting a the original definition from the result of verification is very useful for @hreada's work on the new unparser.
---

Extract original definition from IndexedModule

---

kore/src/Kore/Step/Simplification/And.hs
kore/src/Kore/Step/Substitution.hs
kore/test/Test/Kore/Step/Simplification/And.hs

This is not critical, but it removes an unforced `error` call and some dead code.
---

Allow branching in And.makeEvaluate

---

kore/src/Kore/Step/Axiom/Data.hs
kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
kore/src/Kore/Step/Axiom/Registry.hs

Return `NotApplicable` for a function evaluation if the definition does not cover the entire input, i.e. if there are any remainders. This is safe to do because the other backends do not allow functions to branch at all. (This still allows branching, but only if the branches can be proven to cover the entire input.) This is useful to do because it postpones evaluating functions until more information is available; concrete execution of KEVM is up to 40% faster! This also stops the problem where we would loop forever trying to evaluate stuck functions in a remainder: this allows one new KWASM proof to succeed, and all remaining failing proofs get stuck instead of looping!
---

No function remainders

---

kore/src/SMT.hs

Using a non-standard logic is relatively unusual; enough so that we are
justified to require the user to provide their own SMT prelude to set the
logic.
This also prevents problems such as: using quantifiers for constructor axioms, while having quantifiers disabled by the logic.
---

SMT: Use default logic

---

kore/test/Test/Kore/Comparators.hs
kore/test/Test/Tasty/HUnit/Extensions.hs

* Fix argument matching for StructEqualWithExplanation and WrapperEqualWithExplanation in order to let people know they should change the comparators when they change the structures. As you'll notice from this PR, they don't always remember to do it. In case you think that these should be automatically generated: I fully agree, I sent a PR that did it, but it seems that I used a reflection library that wasn't nice enough. Maybe I'll try to do it again, but I won't mind if someone else does it before.
* Fix line length issues.
---

Fixes for comparators

---

kore/app/exec/Main.hs
kore/app/share/GlobalMain.hs
kore/src/Kore/Exec.hs
kore/src/Kore/ModelChecker/Bounded.hs
kore/src/Kore/ModelChecker/Simplification.hs
kore/src/Kore/ModelChecker/Step.hs
kore/src/Kore/Step/Axiom/Registry.hs
kore/src/Kore/Step/Rule.hs
src/main/k/in-progress/bmc/example1/bmc.k
src/main/k/in-progress/bmc/example1/check/fail/test1.kore
src/main/k/in-progress/bmc/example1/check/fail/test2.kore
src/main/k/in-progress/bmc/example1/check/fail/test3.kore
src/main/k/in-progress/bmc/example1/check/success/test1.kore
src/main/k/in-progress/bmc/example1/check/success/test2.kore
src/main/k/in-progress/bmc/example1/check/success/test3.kore
src/main/k/in-progress/bmc/example1/check/success/test4.kore
src/main/k/in-progress/bmc/example1/check/success/test5.kore
src/main/k/in-progress/bmc/example1/check/success/test6.kore
src/main/k/in-progress/bmc/example1/check/success/test7.kore
src/main/k/in-progress/bmc/example1/check/success/test8.kore
src/main/k/in-progress/bmc/example1/check/success/test9.kore
src/main/k/in-progress/bmc/example1/vdefinition.kore

---
1. added '--bmc' flag to the command line which invokes the bounded model checker.
2. Introduced `ImplicationRule` to capture bmc specification (which is different from rewrite rules)
3. Bounded model checker is implemented in a separate module.

prototype of bmc for AG pattern

---

kore/src/Kore/IndexedModule/IndexedModule.hs
kore/src/Kore/Step/Rule.hs
kore/test/Test/Kore/IndexedModule/Resolvers.hs

Sort module sentences before indexing.
The order of sentences in a module is not formally significant, so the order produced by the frontend varies depending on the build, the operating system, the phases of the moon, non-local quantum variables, ...
Although the order of sentences is not formally significant, it affects debugging: if either of two axioms would produce an error, applying them in one order or the other changes which error is actually produced. Therefore, we sort all the sentences before beginning so that errors are more readily-reproducible.
---

Sort module sentences before indexing

---

kore/package.yaml
kore/src/Kore/Domain/Builtin.hs
kore/src/Kore/Internal/TermLike.hs
kore/src/Kore/Predicate/Predicate.hs
kore/src/Kore/Step/Rule.hs
kore/src/Kore/Step/Simplification/AndTerms.hs
kore/src/Kore/Syntax/Exists.hs
kore/src/Kore/Syntax/Forall.hs
kore/src/Kore/Syntax/Pattern.hs
kore/src/Kore/Syntax/PatternF.hs
kore/src/Kore/Syntax/Variable.hs
kore/src/Kore/Unification/Unify.hs
kore/src/Kore/Unparser.hs
kore/test/Test/Kore/Unparser.hs

This pull request introduces a generic unparsing function to eliminate boilerplate associated with unparsing large sum types where the type is unparsed by delegating to each case in the sum. This is also a kind of warm-up exercise for more boilerplate reduction, such as in `Kore.ASTPrettyPrint` and `Test.Kore.Comparators`.
---

Generic unparsing

---

kore/src/Kore/Exec.hs
kore/src/Kore/Internal/OrPattern.hs
kore/src/Kore/Internal/Pattern.hs
kore/src/Kore/ModelChecker/Simplification.hs
kore/src/Kore/OnePath/Step.hs
kore/src/Kore/OnePath/StrategyPattern.hs
kore/src/Kore/OnePath/Verification.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Step/Condition/Evaluator.hs
kore/src/Kore/Step/Result.hs
kore/src/Kore/Step/Simplification/Equals.hs
kore/src/Kore/Step/Simplification/Floor.hs
kore/src/Kore/Step/Simplification/Forall.hs
kore/src/Kore/Step/Simplification/Iff.hs
kore/src/Kore/Step/Simplification/Implies.hs
kore/src/Kore/Step/Simplification/In.hs
kore/src/Kore/Step/Simplification/Next.hs
kore/src/Kore/Step/Simplification/Rewrites.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/src/Kore/Step/Transition.hs
kore/test/Test/Kore/Comparators.hs
kore/test/Test/Kore/Internal/Pattern.hs
kore/test/Test/Kore/OnePath/Step.hs
kore/test/Test/Kore/OnePath/Verification.hs
kore/test/Test/Kore/Step/Simplification/Equals.hs
kore/test/Test/Kore/Step/Simplification/Or.hs

This pull request causes one-path reachability proofs to fail at the first stuck remainder. Such proofs can loop if we fail to apply a circularity (for example) and this makes such a failure easier to debug.
---

Fail early during one-path reachability proofs

---

kore/src/Kore/Step/Rule.hs
kore/test/Test/Kore/Step/Rule.hs

In the future, we expect to need many such defined-ness axioms.
It would also be nice if we could specify these axioms in the frontend, but for now this will do.
---

patternToAxiomPattern: Recognize \ceil axioms

---

kore/src/Kore/ModelChecker/Step.hs

insert unprovable node correctly into the graph when early terminated.
---

bug-fix: early termination

---

docs/hooks.md
kore/src/Kore/Builtin/Set.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/Set.hs

I implemented this because I thought I needed it. In fact, I don't need it, but it would be good to have anyway.
---

Implement SET.intersection

---

kore/test/Test/Kore/Step/Substitution.hs

Follow-up to #616. As discussed, this explicitly checks that the substitution is normalized by the functions which specifically normalize the substitution.
---

Test.Kore.Step.Substitution: Check for normalization

---

kore/src/Kore/Internal/MultiOr.hs
kore/src/Kore/Internal/OrPattern.hs
kore/src/Kore/Step/Simplification/Pattern.hs
kore/test/Test/Kore/Builtin/List.hs
kore/test/Test/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Set.hs
kore/test/Test/Kore/OnePath/Step.hs
kore/test/Test/Kore/OnePath/Verification.hs
kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
kore/test/Test/Kore/Step/Axiom/Matcher.hs
kore/test/Test/Kore/Step/Axiom/UserDefined.hs
kore/test/Test/Kore/Step/Function/Integration.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/PatternAttributes.hs
kore/test/Test/Kore/Step/Simplification/And.hs
kore/test/Test/Kore/Step/Simplification/AndTerms.hs
kore/test/Test/Kore/Step/Simplification/Application.hs
kore/test/Test/Kore/Step/Simplification/Ceil.hs
kore/test/Test/Kore/Step/Simplification/DomainValue.hs
kore/test/Test/Kore/Step/Simplification/Equals.hs
kore/test/Test/Kore/Step/Simplification/Exists.hs
kore/test/Test/Kore/Step/Simplification/Iff.hs
kore/test/Test/Kore/Step/Simplification/Integration.hs
kore/test/Test/Kore/Step/Simplification/Not.hs
kore/test/Test/Kore/Step/Simplification/Pattern.hs
kore/test/Test/Kore/Step/Simplification/Predicate.hs
kore/test/Test/Kore/Step/Step.hs
kore/test/Test/Kore/Step/Substitution.hs
kore/test/Test/Kore/Unification/SubstitutionNormalization.hs

This fixes a bug in `Pattern` simplification related to a use of `traverse`. I also added a card to the story board to clean up other possibly-problematic uses.
Related: #635 
---

Pattern.simplify: Use filterOr

---

kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/test/Test/Kore/Parser.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Parser.hs

Limitations:
~- no parsing error when attempting to add an alias for an existing command (although it will have no real effect)~ fixed
- we don't have great errors (but this is a problem with the repl in general since we hide parsing errors)
~- no checking until we actually try running the alias, so the alias could be completely malformed~
- no checking that the alias is malformed, but we do check that at least the "verb" (first word in the command) is defined
~- you can create infinite loops:~
You can't create infinite loops because of the check above (first line would error because `ln` is not defined
```
> alias l0 = loop
Error: unknown command.
```

Repl: alias with arguments

---

kore/src/Kore/Step/Simplification/Not.hs
kore/src/Kore/Syntax/Not.hs
kore/test/Test/Kore/Step/Simplification/Not.hs

This fixes a small bug in the \not simplifier. I can't seem to trigger this bug "in production," so I'm calling it "small".
In addition to adding a test and fixing the bug, I wrote the simplifier in a more type-ful way, so that I can make changes more confidently in the future.
---

Fix a \not simplifier bug

---

kore/src/Control/Monad/Counter.hs
kore/src/Kore/Logger.hs
kore/src/Kore/Step/Transition.hs
kore/src/SMT.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Set.hs

This is some cleanup I did while investigating the unit test performance regression. These changes themselves have a negligible impact on performance. Ultimately the regression is caused by spawning too many Z3 processes, which will be solved when @vladciobanu adds a dummy solver interface for the tests.
---

Cleanup: Logging

---

kore/app/repl/Main.hs
kore/src/Kore/Exec.hs
kore/src/Kore/Logger.hs
kore/src/Kore/Logger/Output.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Step/Simplification/Data.hs
kore/src/Kore/Unification/Unify.hs
kore/src/SMT.hs
kore/src/SMT/SimpleSMT.hs
kore/test/Test/Kore/Repl/Interpreter.hs

This gets rid of the hacky `IORef` thing. When you start to invert the `Simplifier` hierarchy, you should probably base it on this branch.
---

Refactor SMT logging

---

kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Interpreter.hs

Running the `try` command through the stepper produces confusing output. Running unification directly makes the result clearer and also doesn't modify the execution graph.
---

kore-repl: Do not run stepper for `try` command

---

kore/src/Kore/Builtin/Int.hs

Remove the unimplemented hooks for bitRange and signedExtendBitRange

---

kore/src/Kore/ASTVerifier/SentenceVerifier.hs
kore/src/Kore/Sort.hs
src/test/resources/test-hooks-ctor.kore
src/test/resources/test-hooks-ctor.kore.golden

Error on defining constructor for hooked sorts

---

kore/src/Kore/Step/Substitution.hs
kore/test/Test/Kore/Step/Substitution.hs

@virgil-serbanuta This resolves a `TODO` you left in `Kore.Step.Substitution`.
---

Do not throw an error when branching

---

include.mk

Related: kframework/k#534
Fixes: #727
---

[kevm-integration] Update K to nightly-121d8e122

---

include.mk
kore/src/Kore/ASTVerifier/PatternVerifier.hs

This is just waiting on a new K release.
Fixes: #725 
Related: kframework/k#535 kframework/k#543
---

Remove special handler for K constructors

---

kore/src/Kore/Builtin/Set.hs
kore/src/Kore/Unification/Substitution.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/Set.hs
kore/test/Test/SMT.hs

@virgil-serbanuta I was able to re-create the integration test failure in a unit test. It only appears using `termUnification`, it doesn't happen when simplifying a `mkAnd` pattern, so I guess (?) we stopped running something through the simplifier before unification.
---

Set unit unification

---

kore/app/exec/Main.hs
kore/src/Kore/Exec.hs
kore/src/Kore/ModelChecker/Bounded.hs
kore/src/Kore/ModelChecker/Step.hs
kore/src/Kore/Step/Rule.hs

---
1) We return the counterexample to the frontend instead of using Debug.Trace to print it to the std output.
2) Currently we enforce only one rule in the spec module. If a spec module contains several rules to check, it is hard to present the final results to the user.

return the counterexample and enforce one rule in the spec module

---

kore/src/Kore/AST/AstWithLocation.hs
kore/src/Kore/AST/Error.hs
kore/src/Kore/ASTVerifier/PatternVerifier.hs
kore/src/Kore/ASTVerifier/SentenceVerifier.hs
kore/src/Kore/ASTVerifier/SortVerifier.hs
kore/src/Kore/Attribute/Parser.hs
kore/src/Kore/Builtin/Builtin.hs
kore/src/Kore/Error.hs
kore/src/Kore/IndexedModule/Error.hs
kore/src/Kore/IndexedModule/Resolvers.hs
kore/src/Kore/Syntax/Id.hs

I meant this to be a part of the dv vs constructor verification PR, but it seems that I'll need some changes in that, so I'm sending this as a separate PR.
---

Refactor some of the error code to use text.

---

kore/src/Kore/Builtin.hs
kore/src/Kore/Builtin/AssociativeCommutative.hs
kore/src/Kore/Builtin/Attributes.hs
kore/src/Kore/Builtin/Builtin.hs
kore/src/Kore/Builtin/List.hs
kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Builtin/MapSymbols.hs
kore/src/Kore/Builtin/Set.hs
kore/src/Kore/Builtin/SetSymbols.hs
kore/src/Kore/Domain/Builtin.hs
kore/src/Kore/Exec.hs
kore/src/Kore/Internal/TermLike.hs
kore/src/Kore/Proof/Value.hs
kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
kore/src/Kore/Step/Simplification/Builtin.hs
kore/test/Test/Kore/Builtin.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/List.hs
kore/test/Test/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Set.hs
kore/test/Test/Kore/Proof/Value.hs
kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs

This pull request adds `Kore.Builtin.internalize` which converts external syntax to internal representations. This function is _not_ yet used by default during execution because of the need to re-normalized the builtin associative-commutative representations. I will deal with that in a subsequent pull request.
---

Internal representations

---

kore/src/Kore/AST/AstWithLocation.hs
kore/src/Kore/ASTVerifier/PatternVerifier.hs
kore/src/Kore/Attribute/Parser.hs
kore/src/Kore/Attribute/Pattern/Defined.hs
kore/src/Kore/Attribute/Pattern/Function.hs
kore/src/Kore/Attribute/Pattern/Functional.hs
kore/src/Kore/Domain/Builtin.hs
kore/src/Kore/Internal/TermLike.hs
kore/src/Kore/Parser/Lexeme.hs
kore/src/Kore/Proof/Functional.hs
kore/src/Kore/Proof/Value.hs
kore/src/Kore/Step/PatternAttributes.hs
kore/src/Kore/Step/Simplification/CharLiteral.hs
kore/src/Kore/Step/Simplification/Inhabitant.hs
kore/src/Kore/Step/Simplification/StringLiteral.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/src/Kore/Syntax.hs
kore/src/Kore/Syntax/CharLiteral.hs
kore/src/Kore/Syntax/Inhabitant.hs
kore/src/Kore/Syntax/PatternF.hs
kore/src/Kore/Syntax/StringLiteral.hs
kore/test/Test/Kore.hs
kore/test/Test/Kore/Comparators.hs
kore/test/Test/Kore/Step/Simplification/CharLiteral.hs
kore/test/Test/Kore/Step/Simplification/StringLiteral.hs

This pull request makes (most) of the nodes in the syntax tree into functors to have a uniform representation. Previously, nodes which had no children were not functors, but this restriction is not necessary. When this is done, we can replace [all this](https://github.com/kframework/kore/blob/fab0cb0a96ded0f5a952f55b95931830806c10d7/kore/src/Kore/Internal/TermLike.hs#L305-L520) with some generically-derived code. Also, we can replace [these smart constructors](https://github.com/kframework/kore/blob/fab0cb0a96ded0f5a952f55b95931830806c10d7/kore/src/Kore/Internal/TermLike.hs#L1152-L2107) with generic ones that also work with the parser's pattern representation. (That's less important, but it will make it nicer to write parser/verifier tests and it will split up this giant module.) …

Cleanup: Uniform-ish representation of syntax nodes

---

kore/src/Kore/Builtin/AssociativeCommutative.hs
kore/test/Test/Kore/Builtin/Map.hs

The concatenation change does not have anything to do with the test, I just happened to notice it while looking through the code.
---

Unify symbolic keys

---

kore/src/Kore/Profiler/Data.hs

---
`ghc-events-analyze` was broken because we paired `START` with `END`, but it should be `START` and `STOP`.

Fix eventlog tracing with ghc-events-analyze

---

docs/2019-08-27-Unification-modulo-overloaded-constructors.md

Unification modulo overloaded constructors proposal

---

kore/src/Kore/Internal/Conditional.hs
kore/src/Kore/Predicate/Predicate.hs
kore/src/Kore/Step/SMT/Evaluator.hs
kore/src/Kore/Step/Simplification/Predicate.hs
kore/src/Kore/Unification/Substitution.hs
kore/test/Test/Kore/Unification/Substitution.hs

---
@vladciobanu We need to normalize the implication check which you added. However, this causes the concrete execution tests to fail and the unit tests to loop forever.

Normalize inputs to SMT

---

kore/app/exec/Main.hs
kore/app/repl/Main.hs
kore/app/share/GlobalMain.hs
kore/src/Kore/AST/Error.hs
kore/src/Kore/ASTVerifier/AliasVerifier.hs
kore/src/Kore/ASTVerifier/AttributesVerifier.hs
kore/src/Kore/ASTVerifier/DefinitionVerifier.hs
kore/src/Kore/ASTVerifier/Error.hs
kore/src/Kore/ASTVerifier/ModuleVerifier.hs
kore/src/Kore/ASTVerifier/PatternVerifier.hs
kore/src/Kore/ASTVerifier/SentenceVerifier.hs
kore/src/Kore/ASTVerifier/Verifier.hs
kore/src/Kore/Builtin/Builtin.hs
kore/src/Kore/IndexedModule/IndexedModule.hs
kore/src/Kore/IndexedModule/Resolvers.hs
kore/src/Kore/Syntax/Sentence.hs
kore/test/Test/Kore/ASTVerifier/DefinitionVerifier.hs
kore/test/Test/Kore/ASTVerifier/DefinitionVerifier/SortUsage.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/IndexedModule/Resolvers.hs
kore/test/Test/Kore/Parser/Regression.hs
kore/test/Test/Kore/Step/Rule.hs
src/test/resources/test-hooks-ctor.kore.golden

---
@ana-pantilie 
I fixed the problems with #916, but it looks like you had pushed some changes, and I can't tell anymore which changes are mine or yours, so I'm opening a new pull request; otherwise I'm afraid I might overwrite something you did. The tests pass and you can use a `VerifiedModule` in the pattern verifier now, which should unblock you on #873. I haven't tracked down all the dead code in `Kore.IndexedModule.IndexedModule` yet, but I can do that in another pull request, if you want to review this one.

Refactor DefinitionVerifier (again)

---

Makefile

---
Fix some funny indentation introduced in #909.

Makefile: Fix indentation of .PHONY targets

---

Jenkinsfile

The timeout served its purpose: we immediately observed the slow-down due to
recent changes in the KEVM semantics. Now we will temporarily increase the
timeout so that other work is not blocked while we work on this.
---

Jenkinsfile: Extend the KEVM Integration timeout

---

kore/src/Kore/Syntax/Id.hs
kore/test/Test/Kore/Syntax/Id.hs

---
The `Hashable` instance of `Id` accidentally included the `AstLocation`.

Fix instance Hashable Id

---

kore/src/Kore/Exec.hs
kore/src/Kore/Goal.hs
kore/src/Kore/ProofState.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/State.hs
kore/src/Kore/Strategies/Goal.hs
kore/src/Kore/Strategies/OnePath/Actions.hs
kore/src/Kore/Strategies/OnePath/Verification.hs
kore/src/Kore/Strategies/ProofState.hs
kore/test/Test/Kore/AllPath.hs
kore/test/Test/Kore/Comparators.hs
kore/test/Test/Kore/OnePath/Step.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Strategies/OnePath/Verification.hs

@ttuegel Would this improve the current code? I was trying to understand Goal.hs and it seemed to me that it contained things that shouldn't be in there so I extracted them, what do you think about it?
I also moved OnePath one level down in the module hierarchy, hoping that it will make more sense to put AllPath, OnePath, and whatever else we may add (chain-of-rules execution maybe) in their own directory.
I don't need this refactoring, so I can just drop the PR if it does not make sense.
---

Refactor Goal.hs

---

kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/State.hs
kore/src/Kore/Strategies/Goal.hs
kore/src/Kore/Strategies/OnePath/Actions.hs
kore/src/Kore/Strategies/ProofState.hs
kore/test/Test/Kore/AllPath.hs
kore/test/Test/Kore/Comparators.hs
kore/test/Test/Kore/OnePath/Step.hs

Right now we are removing the destination from the remainder and simplifying the result when deriving rules. That's a bit strange from a strategy/goal point of view, so this PR moves that at the strategy level.
To do that, it splits the `Goal` goal into `Goal` and `GoalRewritten`, so that we can easily ignore the latter until the end of a step.
---

Clarify the onepath strategy

---

Jenkinsfile
kore/src/Kore/Step/Function/Evaluator.hs
kore/src/Kore/Step/Function/Memo.hs
kore/src/Kore/Step/Simplification/Data.hs
kore/src/Kore/Step/Simplification/Simplify.hs
kore/test/Test/Kore/AllPath.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Step.hs
kore/test/Test/Kore/Step/Axiom/Evaluate.hs
kore/test/Test/Kore/Step/Axiom/Registry.hs
kore/test/Test/Kore/Step/Function/Evaluator.hs
kore/test/Test/Kore/Step/Function/Integration.hs
kore/test/Test/Kore/Step/Function/Memo.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Simplification.hs
kore/test/Test/Kore/Step/Simplification/And.hs
kore/test/Test/Kore/Step/Simplification/Exists.hs
kore/test/Test/Kore/Unification/Unifier.hs
scripts/kevm-integration.sh

Fixes #953.
The function cache is implemented in `Kore.Step.Function.Memo`. An "object-oriented" approach is used to minimize the scope of changes; except for some changes to inject a "forgetful" cache into the tests, the only changes are to initialize the cache in `evalSimplifier` and to check and update the cache in `evaluateApplication`. The tests in `Test.Kore.Step.Function.Memo` illustrate the ease with which we can test such a component in isolation.
The timeout on Jenkins is reduced in anticipation of improved performance.
I am really not attached to the names in `Kore.Step.Function.Memo` if they seem too generic to anyone, but I fully intend that module to be imported qualified always.
---

Function memoization

---

kore/src/Kore/Step/Rule.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Rule.hs
kore/test/Test/Kore/Step/Step.hs

Note that the refresh change is tested by the `test_refreshRulePattern` at line 358 in Rule.hs, although the test didn't change.
---

Fix ensures

---

scripts/check.sh

`check.sh` runs stylish on all modified files therefore it fails if any of those files were deleted. This PR should fix this.
---

Make check.sh ignore deleted files

---

kore/src/Kore/Step/Rule/Combine.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Rule/Combine.hs

Given a list of rules
```
L1 -> R1
L2 -> R2
...
Ln -> Rn
```
computes a predicate P such that applying the above rules in succession is the same as applying `(L1 and P) => Rn`.
Also fixes a free-variables bug for rules.
---

Combining a sequence of rules into one

---

kore/src/Kore/Step/Axiom/Evaluate.hs
kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
kore/src/Kore/Step/Function/Evaluator.hs
kore/src/Kore/Step/SMT/Evaluator.hs
kore/src/Kore/Step/Simplification/Conditional.hs
kore/src/Kore/Step/Simplification/OrPattern.hs
kore/src/Kore/Step/Simplification/Pattern.hs
kore/src/Kore/Step/Simplification/Predicate.hs
kore/src/Kore/Step/Simplification/Simplify.hs
kore/test/Test/Kore/Step/Axiom/Evaluate.hs
kore/test/Test/Kore/Step/Axiom/EvaluationStrategy.hs
kore/test/Test/Kore/Step/Simplification/OrPattern.hs

@traiansf  said that child predicates (without the top-level predicate) reduce the SDIV time from >20 min (timeout) to ~9 min
---

Child and top-level predicates

---

kore/src/Kore/Step/Axiom/Identifier.hs
kore/test/Test/Kore/Step/Axiom/Identifier.hs

When `TermLike` patterns are `internalized`, we would not match `AxiomIdentifier`s for internal representations of Map, List, or Set. With this change, we always return an `AxiomIdentifier` based on the external pattern syntax, i.e. ordinary symbols.
Fixes: #1022 
---

Match AxiomIdentifier based on external syntax

---

kore/src/Kore/Attribute/Sort/Constructors.hs
kore/src/Kore/Attribute/Sort/ConstructorsBuilder.hs
kore/src/Kore/Exec.hs
kore/src/Kore/IndexedModule/MetadataTools.hs
kore/src/Kore/IndexedModule/MetadataToolsBuilder.hs
kore/src/Kore/Step/Rule/Expand.hs
kore/src/Kore/Step/SMT/Representation/All.hs
kore/src/Kore/Step/SMT/Representation/Sorts.hs
kore/src/Kore/Variables/Fresh.hs
kore/test/Test/Kore/Attribute/Sort/ConstructorsBuilder.hs
kore/test/Test/Kore/IndexedModule/MetadataTools.hs
kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
kore/test/Test/Kore/Proof/Value.hs
kore/test/Test/Kore/Step.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Rule/Combine.hs
kore/test/Test/Kore/Step/Rule/Expand.hs
kore/test/Test/Kore/Step/SMT/Representation/Sorts.hs
kore/test/Test/Kore/Step/SMT/Sorts.hs
kore/test/Test/Kore/Step/SMT/Symbols.hs
kore/test/Test/Kore/Variables/Fresh.hs
kore/test/Test/Kore/With.hs
src/main/k/working/imp/merge/2.merge-golden
src/main/k/working/k-equal/specs/iszero-ge-spec.kprove.golden
src/main/k/working/k-equal/specs/iszero-gt-spec.kprove.golden

Whenever we have a claim `left => right` in which the left hand side contains a variable from a sort with only one constructor, the variable will be replaced with an application of that constructor over new variables. If the sorts for some of the new variables are also single-constructor ones, they are expanded, and so on.
Fixes #997 
---

Unfold claim variables

---

kore/src/Kore/Exec.hs

This should make the two stay more in sync, and fixes the repl not expanding variables of unique constructor sorts.
---

Refactor prover startup

---

kore/src/SMT.hs

In normal execution, this does matter because errors kill the parent process,
dispatchng the child solver process. In the unit tests, this leaves unused child
solver processes when a test throws an error. If the number of test errors
exceeds the system's child process limit, the remaining tests will fail: they
will be unable to start new solver processes.
---

runSMT: Stop solver gracefully upon error

---

kore/src/Kore/Logger/Output.hs
kore/src/Kore/Step/SMT/AST.hs
kore/src/Kore/Step/SMT/Declaration/Symbols.hs
kore/src/Kore/Step/SMT/Representation/Resolve.hs
kore/src/Kore/Step/SMT/Representation/Symbols.hs
kore/test/Test/Kore/Step/Condition/Evaluator.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/SMT/Representation/All.hs
kore/test/Test/Kore/Step/SMT/Representation/Builders.hs
kore/test/Test/Kore/Step/SMT/Representation/Symbols.hs
kore/test/Test/Kore/With.hs

Fixes #1049 
Fixes runtimeverification/polkadot-verification#39
---

Identify orphan SMT constructors

---

kore/src/Kore/Attribute/Pattern/Created.hs
kore/src/Kore/Internal/TermLike.hs

This puts the `Created` information (if present) on the line above the `TermLike`, similar to how `Conditional` marks the `term`.
---

Nicer unparsing of Created

---

kore/src/Kore/Step/Rule.hs
kore/src/Kore/Step/Simplification/ExpandAlias.hs
kore/test/Test/Kore/Step/Rule.hs

See https://github.com/kframework/kore/issues/988#issuecomment-539571208
Fixes https://github.com/kframework/kore/issues/988
Note: I didn't move `substituteWorker` to `Kore.Internal.Alias` because that would have resulted in a cyclic import issue between `Kore.internal.Alias` and `Kore.Internal.TermLike`
---

Expand aliases when parsing rules

---

kore/src/Kore/Step/Simplification/TermLike.hs

We should not require the predicate to be simplified after simplifying the term!
That is the responsibility of the predicate simplifier, not the term
simplifier. Requiring the predicate to be simplified leads to awkward mutual
recursion between the simplifiers.
---

TermLike.simplifyInternal: Relax the pattern simplification check

---

kore/src/Kore/Builtin/Bool/Bool.hs
kore/src/Kore/Builtin/Int/Int.hs
kore/src/Kore/Builtin/List/List.hs
kore/src/Kore/Builtin/String/String.hs
kore/test/Test/ConsistentKore.hs
kore/test/Test/Kore.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Simplification/Integration.hs

This does not use Gen.recursive, as #1081 expects, because we need to pass the sort down and `recursive` does not allow us to do that.
https://github.com/kframework/kore/pull/1109 , which is based on this, implements actual tests, but that PR can't be merged yet, see its comment.
---

Pattern generators for simplification

---

kore/src/Kore/Unification/UnifierImpl.hs
kore/test/Test/Kore/Step/Function/Integration.hs

This bug fix is a prerequisite for reverting #1144. I am submitting the revert separately to keep this pull request clean.
When we introduced set variables, we forgot to update the function that sorts variable-renaming substitutions; it would accidentally re-order substitutions of the form `x:S{} = @Y:S{}` which is *not* a renaming.
I also renamed the function, because every time I look at it, I forget what it does. But if anyone else feels strongly about this, I will put it back.
---

Only re-order variable-renaming substitutions

---

kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Interpreter.hs

Fixes https://github.com/kframework/kore/issues/1178
---

Repl: print to stdout when output file is missing

---

Jenkinsfile

Jenkinsfile: Extend 'Integration: KEVM' time limit to 48 minutes

---

kore/test/Test/ConsistentKore.hs
kore/test/Test/Kore/Step/MockSymbols.hs
kore/test/Test/Kore/Step/Simplification/IntegrationProperty.hs

The first property test for simplification.
We should also test that marking a simplified term as not simplified and resimplifying yields the same term. However, given how hard it was to make this test work, I would leave it for another PR.
---

Property tests for simplification

---

kore/app/exec/Main.hs
kore/app/share/GlobalMain.hs
kore/src/Kore/Exec.hs
kore/src/Kore/Step/Rule/Combine.hs
kore/test/Test/Kore/Step/Rule/Combine.hs

To merge in batch mode:
```
kore-exec definition.kore --merge-rules rule-list --module WASM-WITH-K-TERM --merge-batch-size 2
```
To merge without batches, just omit the flag:
```
kore-exec definition.kore --merge-rules rule-list --module WASM-WITH-K-TERM
```
---

Merge rules in batches

---

kore/src/Kore/Logger.hs
kore/src/Kore/Logger/Output.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Parser.hs
kore/src/Kore/Repl/State.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Parser.hs

---
Referencing #1187 
- remove `--log none`
- set default `--log-level` to `warning`
- change `--log stdout` in `--log stderr`

Start cleaning up logging options

---

kore/src/Kore/Step/Axiom/Evaluate.hs
kore/src/Kore/Step/Axiom/EvaluationStrategy.hs
kore/src/Kore/Step/Result.hs
kore/src/Kore/Step/Step.hs
kore/test/Test/Kore/Step/Axiom/Evaluate.hs

Various clean-up and reduces time of `kore-exec --prove ... --depth 0` by up to 72%.
Fixes: #1233 
---

assertFunctionLikeResults: Do not re-evaluate results

---

.gitignore
cabal.project
kore/package.yaml

- .gitignore: Add Cabal temporary paths
- package.yaml: Specify some version bounds
The lower version bounds are not strictly necessary, but it's a good idea
anyway. One upper version bound was added which will help avoid trouble with
future updates to LTS Haskell.
I wanted to use Cabal for some of the profiling I'm doing (it has more profiling options and better defaults). There's really no reason not to support building with either Cabal or Stack; even if we all continue to use Stack the ongoing cost is basically zero.
---

Allow building with Cabal out-of-the-box

---

kore/src/SMT.hs

Fixes #1131 
Does it make sense to check the `IOException` and make sure it's this specific error? I'm not sure it can fail in any other way. Maybe if the user doesn't have permission to run `z3`...? But I'm not sure how that would happen.
I also removed `newSolver` as an alternate way to run SMT queries since it was not used anywhere, thus making `runSMT` the only point of failure -- unless we use `SimpleSMT` directly.
---

Handle IOException when we can't find 'z3'

---

Jenkinsfile
kore/app/exec/Main.hs
kore/package.yaml
kore/src/Debug.hs
kore/src/Stats.hs
kore/test/Test/Stats.hs
scripts/integration-kevm.sh
scripts/integration-kwasm.sh

- Enable the `-T` GHC RTS flag by default for `kore-exec` and `kore-test` so that RTS statistics are always available. This does not seem to have significant overhead.
- Add a flag `--rts-statistics ⟨filename⟩` to `kore-exec` which collects the RTS statistics at the end of execution and writes them to the named file (JSON format).
- Use `--rts-statistics` and `KORE_EXEC_OPTS` to collect statistics on Jenkins, instead of using the `time` command. This gives better performance indicators because it does not include frontend time or memory usage (the latter is especially significant).
---

Collect RTS statistics

---

kore/src/Kore/Logger/WarnSimplificationWithRemainder.hs
kore/src/Kore/Step/Axiom/EvaluationStrategy.hs

The message's patterns had no indentation.
A distinct log `Entry` type is added for this warning so that we can eventually suppress multiple warnings for the same rule.
---

Fix format of simplication-with-remainders warning

---

kore/app/exec/Main.hs
kore/app/repl/Main.hs
kore/package.yaml
kore/src/Kore/Exec.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/State.hs
kore/src/Kore/Step/Rule.hs
kore/src/Kore/Step/Rule/Expand.hs
kore/src/Kore/Step/Rule/Simplify.hs
kore/src/Kore/Strategies/Goal.hs
kore/src/Kore/Strategies/Verification.hs
kore/test/Test/Kore/Strategies/AllPath/AllPath.hs
kore/test/Test/Kore/Strategies/OnePath/Step.hs
kore/test/Test/Kore/Strategies/Reachability/Verification.hs

Checkpoint in https://github.com/kframework/kore/issues/906
- `kore-exec` and `kore-repl` now use `ReachabilityRule Variable`
- Replaces the `Coercible` constaints in `Claim` with `ToRulePattern` and `FromRulePattern` on `goal` and `Rule goal`
- Adds `goalToRule` and `ruleToGoal` as methods in `Goal`.
- `Rule (ReachabilityRule Variable)` is now a newtype over `RewriteRule Variable`.
- `Goal.strategy` now returns a `Stream` to make a general version of `verifyClaimStep` typesafe when extracting the first and followup steps from the `Strategy` list/stream. This needed a new package dependency, will revert if you think it's a bit overkill.
- Added `Test.Kore.Strategies.Reachability.Verification`.
---

ReachabilityRule as Claim

---

.gitignore
cabal.project
kore/package.yaml

This pull request improves the profiling experience.
You must use `cabal` to build the package, and you must have version 3.0 or later (run `cabal --version` to check). Stack does not seem to allow the user to override the profiling options passed to GHC, but this is essential for acceptable performance. You can install `cabal` and GHC with [`ghcup`](https://www.haskell.org/ghcup/).
To build:
```
cabal configure --enable-profiling
cabal build kore
cp [...]/kore-exec ./.build/kore/bin
```
With these changes, profiling overhead is about 500%, which is better than the 3000% we were seeing with Stack.
I am adding appropriate `INLINE` pragmas to get reasonable profiling reports. (Anything marked `INLINE` will not be reported automatically.)
Fixes: #1346 
See also: #1335 
---

Better profiling experience

---

test/include.mk
test/regression-evm-semantics-39dd1e5/Makefile
test/regression-wasm-semantics-840390f/Makefile

@andreiburdusa  and I looked earlier over an issue where a `test-...-.sh.out` rule was not firing.
Andrei had to leave but I managed to find the issue in the fact that the dependency rule `$(TEST_DIR)/test-%-*` was requiring that at least one file matching that pattern exists.
Assuming we don't always want to provide such a file, I've modified the rule to usa a `wildcard` (and had to enable [Make Secondary Expansion](https://www.gnu.org/software/make/manual/html_node/Secondary-Expansion.html).
@andreiburdusa : I hope that works.
What also confused us was the default rule of `make a.out` to copy `a` to `a.out` which was being used since matching our rule didn't work...
---

Fixed no-helpers found bug

---

kore/src/Kore/Builtin/KEqual.hs
kore/src/Kore/Step/Remainder.hs
kore/src/Kore/Step/Simplification/And.hs
kore/src/Kore/Step/Simplification/AndPredicates.hs
kore/src/Kore/Step/Simplification/Ceil.hs
kore/src/Kore/Step/Simplification/Condition.hs
kore/src/Kore/Step/Simplification/Equals.hs
kore/src/Kore/Step/Simplification/Exists.hs
kore/src/Kore/Step/Simplification/Iff.hs
kore/src/Kore/Step/Simplification/Implies.hs
kore/src/Kore/Step/Simplification/Not.hs
kore/src/Kore/Step/Simplification/SubstitutionSimplifier.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/src/Kore/Step/Substitution.hs
kore/src/Kore/Unification/SubstitutionSimplifier.hs
kore/test/Test/Kore/Step/Simplification/And.hs
kore/test/Test/Kore/Step/Simplification/Iff.hs
kore/test/Test/Kore/Step/Simplification/Implies.hs
kore/test/Test/Kore/Step/Simplification/Not.hs
kore/test/Test/Kore/Step/Simplification/SubstitutionSimplifier.hs

Probably it's not worth the trouble, but this seems to somewhat improve the run time for `test/regression-evm-semantics-39dd1e5/test-sum-to-n.sh` by ~5%
Without this PR:
455.71user 30.96system 4:50.48elapsed 167%CPU (0avgtext+0avgdata 1243420maxresident)k
0inputs+0outputs (0major+340944minor)pagefaults 0swaps
With this PR:
434.27user 30.46system 4:36.44elapsed 168%CPU (0avgtext+0avgdata 1250492maxresident)k
0inputs+0outputs (0major+342744minor)pagefaults 0swaps
---

Stop using side conditions for substitutions

---

kore/src/Kore/Attribute/Pattern.hs
kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Internal/SideCondition/SideCondition.hs
kore/src/Kore/Internal/Variable.hs
kore/src/Kore/Step/EquationalStep.hs
kore/src/Kore/Step/RewriteStep.hs
kore/src/Kore/Step/Simplification/ExpandAlias.hs
kore/src/Kore/Step/Step.hs
kore/src/Kore/Syntax/Variable.hs
kore/src/Kore/Variables/Target.hs
kore/test/Test/Kore/ASTVerifier/DefinitionVerifier.hs
kore/test/Test/Kore/Internal/Pattern.hs
kore/test/Test/Kore/Step/Function/Integration.hs
kore/test/Test/Kore/Step/RewriteStep.hs
kore/test/Test/Kore/Step/Simplifier.hs
kore/test/Test/Kore/Unification/Unifier.hs

After: #1537 
This long-awaited refactoring of the `SortedVariable` class is necessary to (safely) state certain injectivity properties of `toVariable`. That allows us to change `SideCondition.Representation` in turn, yielding a 46% speed-up of the `sum-to-n` proof.
See also: #1399 
Fixes: #1472 
---

Factor class VariableName out of SortedVariable

---

kore/src/Kore/Step/Rule/Combine.hs
kore/src/Kore/Step/RulePattern.hs
kore/test/Test/Kore/Step/Rule/Combine.hs

In the current implementation of `refreshVariables`, the renamed variables get the same name, but after #1539 they will get new names. That breaks some tests.
---

mergeRules: Do not rename rule variables twice

---

test/include.mk

I noticed this seems to be missing. Our tests are obviously not using it, but I think it's nice to have for debugging and people wanting to try out our REPL.
---

Add makefile rule for running the REPL for spec tests

---

Jenkinsfile

The backend has gotten too fast. We should reduce the timeout to catch potential regressions.
---

Jenkinsfile: Set integration test timeout to 24 minutes

---

kore/src/Kore/Internal/Pattern.hs
kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Step/Rule/Simplify.hs
kore/src/Kore/Step/RulePattern.hs
kore/src/Kore/Step/SMT/Evaluator.hs
kore/test/Test/Kore/Step/Rule/Simplify.hs

Include the `requires` clause of a claim as its side condition during initial simplification.
Fixes: #1547
---

Simplify claims with side conditions

---

kore/app/exec/Main.hs
kore/bench/exec/Main.hs
kore/src/Kore/Attribute/Priority.hs
kore/src/Kore/Step.hs
kore/src/Kore/Step/EqualityPattern.hs
kore/src/Kore/Step/RulePattern.hs
kore/src/Kore/Step/Strategy.hs
kore/src/Kore/Strategies/Goal.hs
kore/test/Test/Kore/Attribute/Priority.hs
kore/test/Test/Kore/Exec.hs
kore/test/Test/Kore/Step.hs
kore/test/Test/Kore/Step/Axiom/Registry.hs
test/priority/priority.k

Fixes https://github.com/kframework/kore/issues/1587
Also modifies `priorityAttribute` to receive an Integer instead of a String.
Fixes default priorities bug in https://github.com/kframework/kore/pull/1580 as well.
---

Exec and search with priority rules

---

kore/package.yaml

The "release" flag is enabled by default. When disabled, the build is about 25%
faster, but the build products are 5-10% slower. For developers, this is a good
trade-off.
After this is merged, I will update the kframework/k release job to force the `release` flag. Then I will make another pull request to disable it by default in the backend, so that builds are faster for our developers.
---

Add a "release" flag

---

Jenkinsfile
kore/src/Kore/Log.hs

Exceptions from child threads are not raised until Async.wait is
called. Instead of running the main thread to termination before caling
Async.wait, immediately call Async.waitBoth to raise exceptions.
@ana-pantilie I think this will fix the problem you were having with log thread exceptions not being raised before the main thread terminates.
---

Kore.Log.withAsyncLogAction: Raise exceptions in main thread

---

kore/src/Kore/Internal/Predicate.hs
kore/src/Prelude/Kore.hs

`Data.List.nub` has quadratic complexity. Predicate is an instance of Ord, so we can use `Data.Containers.ListUtils.nubOrd` to make it `O(n log n)` instead.

Replace Data.List.nub with Data.Containers.ListUtils.nubOrd in makeMultipleAnd(/Or)Predicate.

---

kore/src/Kore/Repl/Data.hs
kore/src/Kore/Step/Simplification/Data.hs
kore/src/Kore/Step/Transition.hs
kore/src/ListT.hs
kore/src/Log.hs
kore/src/SMT.hs
kore/test/Test/Kore/Strategies/AllPath/AllPath.hs

Part of https://github.com/kframework/kore/issues/1491:
"Add a logWhile :: Entry entry => entry -> m a -> m a, which will add the entry to the "call stack". Give a default implementation in terms of MFunctor. Give a no-op implementation for LoggerT."
---

Add logWhile method to MonadLog

---

kore/src/Kore/Exec.hs
kore/src/Kore/Log.hs
kore/src/Kore/Log/DebugSolver.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/State.hs
kore/src/Log.hs
kore/src/Log/Entry.hs
kore/src/SMT.hs
kore/src/SMT/SimpleSMT.hs
kore/test/Test/Kore/Repl/Interpreter.hs

Part of https://github.com/kframework/kore/issues/1491
- Add a data type data ActualEntry = ActualEntry { entryContext :: Seq SomeEntry, actualEntry :: SomeEntry }.
- Define instances From ActualEntry SomeEntry and From SomeEntry ActualEntry which forget the entryContext and add an empty entryContext respectively.
- LoggerT should carry a LogAction IO ActualEntry instead of LogAction IO SomeEntry. Use Colog.contramap (from @SomeEntry) and Colog.contramap (from @ActualEntry) as necessary to fix type errors.
---

Use ActualEntry instead of SomeEntry in the logger

---

kore/app/share/GlobalMain.hs

Replace "K framework" with "Kore" for " --version"

---

kore/src/Kore/Log/ErrorRewritesInstantiation.hs
kore/src/Kore/Log/InfoAttemptUnification.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/ModelChecker/Step.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Step.hs
kore/src/Kore/Step/EquationalStep.hs
kore/src/Kore/Step/RewriteStep.hs
kore/src/Kore/Step/Search.hs
kore/src/Kore/Step/Step.hs
kore/src/Kore/Strategies/Goal.hs
kore/src/Kore/Unification/Procedure.hs
kore/src/Kore/Unification/UnificationProcedure.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Step/RewriteStep.hs
kore/test/Test/Kore/Unification/Unifier.hs

~Please review #1668 first.~
This pull request removes unused `MonadUnify` constraints from code that applies `\rewrites` rules. The unifier introduces a redundant means of branching during rule application. Applying a rule should always return a single `Results` value, not a disjunction of `Results`es. This will eliminate some `error` cases in #1659.
I also added some proper log entries to reduce duplication between modules that apply `\rewrites` rules.
---

Refactor UnificationProcedure

---

docs/hooks.md
kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Builtin/Map/Map.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/Map.hs

- Solves https://github.com/kframework/kore/issues/1678.
- I used `Map.isSubmapOf`, which takes `O(n + m)` time according to the docs. `O(n log m)` is also on option if this becomes an issue.
- I've added three unit tests, one positive and two negative (because of keys from the first map missing in the second and common keys mapping to different values, respectively).
- I noticed passing by that the documentation for `inKeys` seemed to be mistaken regarding argument order, so I fixed it.

Add Map.inclusion hook.

---

kore/src/Kore/Builtin/Bool.hs
kore/src/Kore/Internal/Condition.hs
kore/src/Kore/Internal/Conditional.hs
kore/src/Kore/Internal/Symbol.hs
kore/src/Kore/Step/Simplification/AndTerms.hs
kore/test/Test/Kore/Builtin/Bool.hs
test/bmc/fail-3-bmc-spec.k.out.golden
test/bmc/fail-4-bmc-spec.k.out.golden
test/regression-wasm-semantics-840390f/test-memory-concrete-type.sh.out.golden
test/symbolic-ensures/1.strict.out.golden

This implements internally the rule
```
\equals(andBool(X, Y), true) => \and(\equals(X, true), \equals(Y, true))
```
See also: #1648
---

Evaluate BOOL.and by unification

---

kore/package.yaml

The K Framework release job will still build with the flag enabled, but
developers building from source will get faster builds.
Fixes: #1527 
---

kore/package.yaml: Disable flag release by default

---

default.nix

The `profiling` flag builds profiled executables. For convenience, libraries are
now always built with profiling enabled.
---

default.nix: Add profiling flag

---

shell.nix

Fixes a bug introduced by #1707.
---

shell.nix: Changed type of default.nix

---

kore/app/exec/Main.hs
kore/src/Kore/Equation.hs
kore/src/Kore/Equation/Equation.hs
kore/src/Kore/Equation/Registry.hs
kore/src/Kore/Equation/Sentence.hs
kore/src/Kore/Equation/Simplification.hs
kore/src/Kore/Equation/Types.hs
kore/src/Kore/Internal/Predicate.hs
kore/src/Kore/Step/Axiom/Registry.hs
kore/src/Kore/Step/EqualityPattern.hs
kore/src/Kore/Step/Rule.hs
kore/src/Kore/Step/Simplification/And.hs
kore/src/Kore/Step/Simplification/Data.hs
kore/src/Kore/Step/Simplification/Rule.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/src/Kore/Step/Step.hs
kore/src/Kore/Strategies/Goal.hs
kore/test/Test/Expect.hs
kore/test/Test/Kore/Attribute/Overload.hs
kore/test/Test/Kore/Equation/Sentence.hs
kore/test/Test/Kore/Internal/Predicate.hs
kore/test/Test/Kore/Step/Axiom/Registry.hs
kore/test/Test/Kore/Step/Rule.hs
kore/test/Test/Kore/Step/Simplification/AndTerms.hs
kore/test/Test/Kore/Step/Simplification/Integration.hs

The parts of the backend related to applying equations are scattered through several parts of the code. Here, I begin to collect them under `Kore.Equation`.
See also: #1560 
---

Begin to collect the scattered parts of equation application

---

kore/src/Debug.hs
kore/src/Kore/Attribute/Pattern.hs
kore/src/Kore/Attribute/Symbol.hs
kore/src/Kore/Equation/Application.hs
kore/src/Kore/Equation/Equation.hs
kore/src/Kore/Internal/Condition.hs
kore/src/Kore/Internal/Pattern.hs
kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Step/Axiom/Matcher.hs
kore/test/Test/Expect.hs
kore/test/Test/Kore/Equation/Application.hs

This pull request adds the module `Kore.Equation.Application` for applying equations. I have not yet replaced `Kore.Step.EquationalStep` throughout the code, but it does have dedicated unit tests in `Test.Kore.Equation.Application`. This is a rewrite of `EquationalStep` that avoids the external solver whenever possible. I also found several latent bugs in the former implementation.
There is an unrelated change included: the `Debug` class gets a `debugPrecBrief` method to avoid the verbosity of printing all pattern and symbol attributes.
Fixes #1561 
---

Kore.Equation.Application

---

kore/src/Kore/Internal/SideCondition.hs
kore/test/Test/Kore/Equation/Application.hs

This pull request duplicates some tests from `Test.Kore.Step.Axiom.Evaluate` into `Test.Kore.Equation.Application` in preparation to remove the former.
---

Port tests from evaluateAxioms to applyEquation

---

.hlint.yaml
default.nix
kore/src/Kore/Internal/Predicate.hs
kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Log/DebugEvaluateCondition.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Log/WarnDecidePredicateUnknown.hs
kore/src/Kore/Profiler/Data.hs
kore/src/Kore/Profiler/Profile.hs
kore/src/Kore/Step/SMT/Evaluator.hs
kore/src/Kore/Step/SMT/Lemma.hs
kore/src/Kore/Step/SMT/Translate.hs
kore/src/Kore/Step/Simplification/Simplify.hs
kore/src/SQL.hs
kore/test/Test/Kore/Log/DebugEvaluateCondition.hs
kore/test/Test/Kore/Step/SMT/Evaluator.hs
kore/test/Test/Kore/Step/SMT/Symbols.hs
kore/test/Test/Kore/Step/SMT/Translate.hs

This pull request allows sending side conditions to the solver.
1. `decidePredicate` is modified to take a `NonEmpty` list of predicates.
1. `Evaluable` instances are added for pairs `(SideCondition variable, Predicate variable)` and `(SideCondition variable, Condition variable)`.
1. The solver's response is now added to the log.
---

Send side conditions to the solver

---

kore/src/SMT/SimpleSMT.hs

If the solver's model is desired, the user can load the query (see the
`--solver-transcript` option) into the solver offline to produce the model.
---

Do not log SMT models

---

kore/CHANGELOG.md
kore/package.yaml

kore-0.19.0.0

---

ghcid.sh
hie-bios.sh

The script loads the entire package into a single GHCi session, which (among other things) avoids building the library.
---

Add a script for launching ghcid

---

kore/src/Kore/Builtin/AssocComm/CeilSimplifier.hs
kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Step/Simplification/Ceil.hs
kore/src/Kore/Step/Simplification/CeilSimplifier.hs
kore/src/Kore/Step/Simplification/Simplify.hs
kore/test/Test/Expect.hs
kore/test/Test/Kore/Builtin/Map.hs

This pull request implements symbolic evaluation of the `MAP.in_keys` hook, the first part of fixing #1665.
---

Add built-in symbolic evaluator for MAP.in_keys

---

kore/src/Kore/Log/ErrorRewritesInstantiation.hs

It seems that for the substitution coverage error we were reporting the assigned instead of the unassigned variables. This PR addresses this issue.
---

SubstitutionCoverageError: Report unassigned variables

---

.gitignore
default.nix
shell.nix

This adds `ghc-tags-plugin` to the `shell.nix` environment, so that GHC and GHCi can generate tags files for editors that use them (Emacs and Vim). Use the plugin by adding options `-plugin-package=ghc-tags-plugin -fplugin=Plugin.GhcTags -fplugin-opt=Plugin.GhcTags:--etags` to the GHCi command line. Omit the `-fplugin-opt=...` for Vim.
---

Allow local modications to Nix environment

---

Jenkinsfile
kore/package.yaml
kore/test/Driver.hs
stack.yaml
stack.yaml.lock

tasty-test-reporter displays failing tests better in the console and can display
test failures in the CI logs while simultaneously producing a Jenkins XML
report.
---

Replace tasty-ant-xml with tasty-test-reporter

---

test/include.mk

This pull request is required to fix the integration tests on my machine.
---

test/include.mk: `true` is not `/bin/true`

---

kore/CHANGELOG.md
kore/package.yaml

kore-0.21.0.0

---

kore/package.yaml

Compiling with -eventlog by default has no discernible overhead, but allows the
user to enable the eventlog at runtime without recompiling.
See also: #1897 
---

kore: Build executables with -eventlog

---

docs/2020-06-22-Rewrite-Rule-Priorities.md
docs/2020-06-30-Combining-Priority-Axioms.md

Design document for combining priority axioms

---

kore/test/Test/Kore/Step/Simplification/TermLike.hs

An earlier refactoring of this module disconnected the mock simplifier, using
the real simplifier instead.
---

simplifyEvaluated: Use local mock simplifier

---

kore/src/Prelude/Kore.hs

The base Prelude does not export all of Semigroup's methods because they rely on
NonEmpty, which is also not in the default scope.
---

Prelude.Kore: Export Semigroup and NonEmpty

---

kore/app/exec/Main.hs
kore/src/Kore/BugReport.hs
kore/src/Kore/Log.hs

The logging infrastructure is changed to write the log synchronously from the main thread. This reduces memory use slightly, but dramatically reduces runtime by up to 50%!
Exception logging is simplified so that `withBugReport` is the final exception handler; it logs any uncaught exception, creates the bug report archive, and sets the exit code.
---

Synchronous logging

---

kore/src/Kore/Log/KoreLogOptions.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Parser.hs

Fixes https://github.com/kframework/kore/issues/1956
---

kore-repl: debug-equation dynamically

---

kore/CHANGELOG.md
kore/src/Kore/Internal/Pattern.hs
kore/src/Kore/Internal/Substitution.hs
kore/src/Kore/Rewriting/RewritingVariable.hs
kore/test/Test/Kore/Internal/Pattern.hs
kore/test/Test/Kore/Internal/Substitution.hs
kore/test/Test/Kore/Step/RewriteStep.hs

This fixes a bug where variables introduced by symbolic narrowing were not named correctly.
---

Bug fix for symbolic narrowing

---

kore/src/Kore/Repl/Data.hs

---
Fixes #1957 
Please see also the [wiki](https://github.com/kframework/kore/wiki/Kore-REPL#available-commands-in-the-kore-repl)

Abbreviate help command

---

kore/app/exec/Main.hs
kore/app/repl/Main.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Log/WarnIfLowProductivity.hs
kore/src/Stats.hs

Warn when productivity is low

---

kore/src/Kore/Internal/TermLike.hs
kore/test/Test/Kore/Attribute/Pattern/ConstructorLike.hs
kore/test/Test/Kore/Internal/TermLike.hs
kore/test/Test/Kore/Step/MockSymbols.hs

mkDefined: Descend into elements of collections

---

default.nix

Updating haskell.nix removed `project.kore.components.all`, so we are adding a
virtual package `kore` that combines all the executables.
---

default.nix: Add kore attribute

---

.hlint.yaml
kore/src/Kore/Step/Transition.hs
kore/test/Test/Kore/Step/Transition.hs

Implementing `ifte` for `TransitionT` allows us to write a simple, lazy implementation of `orElse`, which improves memory use (#2028). Normally, we think of laziness as increasing memory use, but the problem here is partial laziness: the former implementation of `orElse` would only force the _spine_ of the list and not the values (that is, `_ : _ : _ : []`) so we would end up with a large list of unevaluated thunks. This fully-lazy implementation of `orElse` only forces conses `(:)` on-demand.
I wrote this in a TDD style as a demonstration, but I also caught a bug doing it that way.
---

Kore.Step.Transition: Lazy orElse

---

Jenkinsfile

The generic updater allows us to change dependents without making PRs into this repo. Not super important here, but I'm migrating all the updaters over.
---

Jenkinsfile: switch to generic update

---

kore/src/Kore/Log/WarnIfLowProductivity.hs

Disable WarnIfLowProductivity when total run time is below 60s

---

kore/src/Kore/Equation/Application.hs
kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Step/SMT/Translate.hs
kore/test/Test/Expect.hs
kore/test/Test/Kore/Equation/Application.hs
kore/test/Test/Kore/Step/SMT/Translate.hs

Outer predicate sorts are erased before sending to the solver.
Fixes: #2076 
---

translatePredicateWith: Erase predicate sorts

---

kore/src/Kore/Internal/MultiOr.hs

These are higher-order functions and inlining them might expose more optimizations. It will also produce cleaner profiles.
---

MultiOr: INLINE observeAllT and gather

---

kore/src/Kore/Log/ErrorBottomTotalFunction.hs
kore/src/Kore/Step/Function/Evaluator.hs
kore/src/Kore/Step/Simplification/Application.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Step/Simplification/TermLike.hs

This reverts commit 9c3511c64db901c4b2b21b37a3d346b687fbbee4.
The intermittent failure in the release job has become more frequent, blocking important updates.
---

Revert "Stop execution on ErrorBottomTotalFunction (#2088)"

---

kore/test/Test/Kore/Builtin/Int.hs

==Int simplification

---

kore/src/Kore/Step/Simplification/AndTerms.hs
kore/src/Kore/Step/Simplification/Equals.hs
kore/src/Kore/Step/Simplification/Exists.hs
kore/src/Prelude/Kore.hs
kore/test/Test/Kore/Equation/Application.hs
kore/test/Test/Kore/Internal/OrPattern.hs
kore/test/Test/Kore/Reachability/OnePathStrategy.hs
kore/test/Test/Kore/Step.hs
kore/test/Test/Kore/Step/Function/Integration.hs
kore/test/Test/Kore/Step/RewriteStep.hs
kore/test/Test/Kore/Step/Simplification/Condition.hs
kore/test/Test/Kore/Step/Simplification/Exists.hs
kore/test/Test/Kore/Step/Simplification/Integration.hs
kore/test/Test/Kore/Step/Simplification/OrPattern.hs
test/bmc/fail-2-non-positive-bmc-spec.k.out.golden
test/bmc/fail-2-positive-bmc-spec.k.out.golden
test/bmc/fail-3-bmc-spec.k.out.golden
test/bmc/fail-4-bmc-spec.k.out.golden
test/imp/2.merge.out.golden
test/imp/sum-save-proofs-spec.k.out.golden
test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden
test/issue-1872/1.test.out.golden
test/issue-2095/test-issue-2095.sh.out.golden
test/k-equal/iszero-ge-spec.k.out.golden
test/k-equal/iszero-gt-spec.k.out.golden
test/priority/1.merge.out.golden
test/priority/2.merge.out.golden
test/remove-destination/test-1-spec.k.out.golden
test/symbolic-ensures/1.strict.out.golden

Normalize order of terms in \equals

---

.gitignore

The symlink `hie.yaml` used for running the Language Server is often highlighted by git so I think it should be added to `.gitignore`

Made git ignore hie.yaml

---

kore/app/exec/Main.hs
kore/app/repl/Main.hs
kore/src/Options/SMT.hs
kore/src/SMT.hs

Fixes https://github.com/kframework/kore/issues/2207
---

kore-exec: Add option --solver-reset-interval

---

kore/app/exec/Main.hs
kore/src/Kore/Exec.hs
kore/src/Kore/Reachability.hs
kore/src/Kore/Reachability/AllPathClaim.hs
kore/src/Kore/Reachability/OnePathClaim.hs
kore/src/Kore/Reachability/Prove.hs
kore/src/Kore/Reachability/SomeClaim.hs
kore/src/Kore/Step/ClaimPattern.hs
kore/test/Test/Kore/Reachability/Claim.hs
kore/test/Test/Kore/Reachability/Prove.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Step/RewriteStep.hs
kore/test/Test/Kore/Step/Rule/Common.hs
kore/test/Test/Kore/Step/Rule/Simplify.hs
test/save-proofs/test-1-spec.k
test/save-proofs/test-1-spec.k.out.golden
test/save-proofs/test-2-spec.k

Save proofs even when successful

---

include.mk
kore/app/exec/Main.hs
kore/app/format/Main.hs
kore/app/parser/Main.hs
kore/app/repl/Main.hs
kore/app/share/GlobalMain.hs

Ignore KORE_EXEC_OPTS outside kore-exec

---

kore/src/Kore/Step/Simplification/Pattern.hs
test/issue-2221/Makefile
test/issue-2221/spec.kore
test/issue-2221/test-issue-2221.sh
test/issue-2221/test-issue-2221.sh.out.golden
test/issue-2221/vdefinition.kore

Fix SideCondition normalization error

---

kore/src/Kore/Log.hs
kore/src/Kore/Log/KoreLogOptions.hs
kore/src/Kore/Log/Registry.hs

Add option to turn an arbitrary log entry into an error

---

kore/app/format/Main.hs
kore/app/share/GlobalMain.hs
kore/src/Kore/Log/KoreLogOptions.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Parser.hs
kore/src/Kore/Parser/Lexer.hs
kore/src/Kore/Parser/ParserUtils.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Parser.hs
kore/test/Test/Kore/Parser/Lexer.hs
kore/test/Test/Kore/Parser/Parser.hs
kore/test/Test/Kore/Repl/Parser.hs
kore/test/Test/Kore/Unparser.hs

Fixes #2189 
---
-   [x] **Clean up.** The changes are already clean. Clean up anything near …

Improve the performance of the Kore parser

---

kore/src/Kore/Step.hs
kore/test/Test/Kore/Step.hs

Fixes #2299 
Update `executionStrategy` so that `Simplify` always appears after `Rewrite`. If execution is stopped by the depth limit, fully-simplified states will be printed for the user.
---
-   [x] **Tests.** Write unit tests for every change. Write the unit tests that …

Always output fully-simplified states

---

kore/CHANGELOG.md
kore/kore.cabal
kore/package.yaml
nix/kore.nix.d/kore.nix

kore-0.38.0.0

---

kore/src/Kore/Equation/Application.hs
kore/test/Test/Kore/Equation/Application.hs
test/priority/priority-1-spec.k
test/priority/priority-1-spec.k.out.golden
test/priority/priority.k

Fixes https://github.com/kframework/kore/issues/2361
Fixes bug introduced in 3d10ab9e8f087a0df81aae567a07ca430fe5114e.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported …

Do not ignore antiLeft if argument is Nothing

---

kore/CHANGELOG.md
kore/kore.cabal
kore/package.yaml
nix/kore.nix.d/kore.nix

Update the package version to 0.40.0.0.
---
-   [ ] **Clean up.** The changes are already …

kore-0.40.0.0

---

kore/src/Kore/Internal/Conditional.hs
kore/src/Kore/Reachability/Claim.hs
kore/test/Test/Kore/Reachability/Prove.hs

- makes `Kore.Internal.Conditional.Conditional`'s `term` field strict. 
- fixes bug where we would potentially mark `\\bottom` terms as defined in the `simplify` strategy step
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing …

Make Conditional's term a strict field

---

kore/CHANGELOG.md
kore/kore.cabal
kore/package.yaml
nix/kore.nix.d/kore.nix

kore-0.41.0.0

---

kore/src/Kore/ASTVerifier/SentenceVerifier.hs
kore/src/Kore/Equation/Sentence.hs
kore/src/Kore/Equation/Validate.hs

PR #2168 was merged before I could address the last review comments so this PR is meant to do that.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as …

Issue 2100 follow up

---

docs/hooks.md
kore/src/Kore/Builtin/String.hs
kore/src/Kore/Builtin/String/String.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/String.hs

Fixes #2554 
Overwrites #2589 
* Extend evalString2Base to support bases 2-36
* Add evalBase2String to convert an integer to string representation with base 2-36
* Update string2Base tests, add base2String tests
---
-   [ ] **Tests.** Write unit tests for every change. Write …

Implement hooks string2base and base2string over 2 <= base <= 36

---

src/main/kore/prelude.kore

The LLVM backend expects exactly one `\in` clause for each argument in the
argument matching field on the left-hand side of an equation, even if that
argument is not matched but passed directly through to the right-hand side.
Fixes kframework/k#1939
---
-   [ ] **Tests.** …

prelude.kore: Fix function equations for LLVM backend

---

kore/app/exec/Main.hs
kore/src/Kore/Log/KoreLogOptions.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/src/Kore/Step/Step.hs
kore/src/Kore/Unification/SubstitutionNormalization.hs
kore/src/Prelude/Kore.hs
kore/test/Test/Kore.hs
kore/test/Test/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Set.hs

This pull request exports `Data.Functor.(<&>)` and `Data.Functor.void` from `Prelude.Kore`. These are generally useful functions that are already used around the code.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the …

Prelude.Kore: Export (<&>) and void

---

nix/shell.fourmolu.nix

We must set LOCALE_ARCHIVE so that the Haskell standard library can access the
current locale setting through glibc, otherwise we will see errors such as:
> hGetContents: invalid argument (invalid byte sequence)
---
-   [ ] **Tests.** Write unit tests for every change. Write …

shell.fourmolu.nix: Set LOCALE_ARCHIVE on relevant platforms

---

kore/src/Kore/Internal/SideCondition.hs
kore/src/Kore/Step/Simplification/Predicate.hs
kore/src/Kore/Step/Simplification/TermLike.hs
kore/test/Test/Kore/Step/Simplification/Predicate.hs

This pull request will store the `Predicate` and `TermLike` replacements separately in the `SideCondition`. To do so, the new `Predicate` simplifier is modified to apply the replacements itself, instead of delegating to the `TermLike` simplifier. This will be required by #2650 and #2653.
---
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation …

SideCondition: Separate Predicate and TermLike replacements

---

kore/src/Kore/Step/Simplification/Condition.hs

This pull request will clean up the merge after #2599.
---
-   [ ] **Clean up.** The changes …

Clean up Kore.Step.Simplification.Condition

---

kore/src/Kore/Internal/Predicate.hs
kore/src/Kore/Internal/TermLike/TermLike.hs
kore/src/Kore/Rewrite/SMT/Evaluator.hs
kore/src/Kore/Rewrite/SMT/Lemma.hs
kore/src/Kore/Rewrite/SMT/Translate.hs

Needed for https://github.com/kframework/kore/pull/2719
`translatePredicateWith` doesn't convert the `Predicate` into a `TermLike` anymore for translating. But a conversion is still done [here](https://github.com/kframework/kore/pull/2760/files#diff-cdf4fd7952200cc8e9164c9ac6f6d7fdd8bacf53975c4dcb29ab1b347c8aa9f0R257) for unparsing.
---
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for …

Translate Predicate directly

---

kore/src/Kore/Simplify/Predicate.hs
kore/test/Test/Kore/Simplify/Predicate.hs

Overhaul Predicate simplifier: In simplifier

---

kore/src/Kore/Log/DebugUnifyBottom.hs

…er called twice.
This code issue was discovered when investigating the performance regression for #2643, but it appears the gain is independent of that pull request, so this fix should be pushed to master independently, and #2643 should be investigated further.
---
-   [ ] …

debugUnifyBottomAndReturnBottom: remove duplicate call to TermLike.mapVariables

---

kore/src/Kore/Simplify/Equals.hs
kore/src/Kore/Simplify/Predicate.hs

Fixes #2570
Completes all cases of `Predicate.simplify`.
I didn't add any tests for `simplifyEquals` because it only calls `Equals.simplify`, which we will need to modify for https://github.com/kframework/kore/issues/2610.
---
-   [ ] **Tests.** Write unit tests for every …

Overhaul Predicate simplifier: Equals, v2

---

kore/src/Kore/Reachability/Claim.hs
kore/test/Test/Kore/Reachability/Prove.hs

Use `Transition.ifte` like [here](https://github.com/kframework/kore/blob/98e241ede419e7a9e1266393104fcbd84fb796e4/kore/src/Kore/Reachability/Claim.hs#L317) to turn empty transitions into `Proven`. Part of #2786 
---
-   [ ] **Tests.** Write unit tests for every change. …

Clarify final configuration

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update.yml

This PR is a fix for CI failures related to a new Nix release yesterday. It does two things:
* Bumps the github actions we use for nix (`install-nix`, `install-cachix`) to their newest versions.
* Pins Nix to 2.3.16 as a temporary fix, as 2.4 breaks on macos at the moment.

Bump CI action versions, pin nix to 2.3.16

---

kore/src/Kore/Rewrite/Search.hs

Search: use matching instead of unification

---

kore/CHANGELOG.md
kore/kore.cabal
nix/kore.nix.d/kore.nix

kore-0.60.0.0

---

kore/src/Kore/Attribute/Axiom.hs

There may be other fixes needed to the code, but this PR seems to address the issues I noted on Slack.

Parse `non-executable` attribute

---

kore/kore.cabal

GHC --make supports parallel builds within a single module, but stack and cabal, to the best of my knowledge, do not yet explicitly support this level of parallelism. Thus, we enable parallel builds by default on the components that most benefit from it, by means of a ghc-options flag in kore.cabal.
---
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete …

enable parallel build of kore libraries

---

kore/kore.cabal

Reverts runtimeverification/haskell-backend#3028
Testing to see if this fixes the failed PRs.

Revert "enable parallel build of kore libraries"

---

kore/kore.cabal
kore/src/Kore/Log/DebugCreatedSubstitution.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Rewrite/RewriteStep.hs
nix/kore.nix.d/kore.nix

Fixes #3029
Example log entry, standard format:
```
kore-exec: [1097047] Debug (DebugCreatedSubstitution):
(InfoReachability) while applying axioms:
Created and applied the following substitution:
/* Spa */
\and{SortGeneratedTopCell{}}(
/* Spa */
\and{SortGeneratedTopCell{}}(
/* Spa */
\and{SortGeneratedTopCell{}}(
/* Spa */
\and{SortGeneratedTopCell{}}(
/* Spa */
\and{SortGeneratedTopCell{}}(
/* Spa */
\equals{SortGeneratedCounterCell{}, SortGeneratedTopCell{}}(
/* Fl Fn D Sfa */
RuleVar'Unds'DotVar0:SortGeneratedCounterCell{},
/* Fl Fn D Sfa */
Lbl'-LT-'generatedCounter'-GT-'{}(
/* Fl Fn D Sfa */
ConfigVar'Unds'DotVar1:SortInt{}
)
),
/* Spa */
\equals{SortK{}, SortGeneratedTopCell{}}(
/* Fl Fn D Sfa */ RuleVar'Unds'DotVar2:SortK{},
/* Fl Fn D Sfa Cl */ dotk{}()
)
),
/* Spa */ …
```

Add log entry for created substitutions

---

kore/src/Kore/Rewrite/Axiom/EvaluationStrategy.hs
kore/src/Kore/Rewrite/Axiom/Identifier.hs
kore/src/Kore/Simplify/Simplify.hs
kore/test/Test/Kore/Rewrite/Function/Integration.hs
kore/test/Test/Kore/Simplify/Application.hs
kore/test/Test/Kore/Simplify/Condition.hs
kore/test/Test/Kore/Simplify/Integration.hs

Previously, if you had a simplification rule whose left-hand side was \equals and one of the children of the \equals was a variable, it would not correctly find that axiom in the index if the term being simplified was an equality between two application patterns.
I have not been able to minimize the example that I was using for testing; when I did, the simplifier was able to solve it even without this change, and I'm not entirely sure what the issue is. If someone wants to help by writing a test for this, that would be great.
---
-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a …

fix simplification indexing for rules with variables under \equals

---

Makefile
kore/app/share/GlobalMain.hs
kore/kore.cabal
nix/kore.nix.d/kore.nix

Moves `GlobalMain` and `Paths_kore` away from the applications into the library, so it will be compiled only once.
Build time with stack dropped from 1m51s to 1m40s on my machine (Intel I9 12thGen)
---
-   [X] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Tests.** Write unit tests for every change. Write the unit …

#3103 compile GlobalMain only once

---

.github/workflows/test.yml
kore/app/repl/Main.hs
kore/kore.cabal
kore/src/Kore/Repl/Parser.hs
nix/kore-ghc8107.nix.d/kore.nix

Fixes current build breakage
Adjusts code that latest `hlint` complains about, fixes `hlint` version to 3.4.1 in the github workflow.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples …

Fix hlint breakage, pin version in github workflow

---

kore/app/share/GlobalMain.hs
kore/src/Kore/Rewrite/SMT/Lemma.hs
kore/src/Kore/Simplify/Data.hs
kore/src/SMT.hs
kore/test/Test/Kore/Builtin/Bool.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Builtin/KEqual.hs
kore/test/Test/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Set.hs
kore/test/Test/Kore/Reachability/MockAllPath.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Rewrite/Axiom/Matcher.hs
kore/test/Test/Kore/Rewrite/Axiom/Registry.hs
kore/test/Test/Kore/Rewrite/Function/Evaluator.hs
kore/test/Test/Kore/Rewrite/Function/Integration.hs
kore/test/Test/Kore/Rewrite/SMT/Evaluator.hs
kore/test/Test/Kore/Rewrite/SMT/Translate.hs
kore/test/Test/Kore/Simplify.hs
kore/test/Test/Kore/Simplify/IntegrationProperty.hs
kore/test/Test/Kore/Simplify/Overloading.hs
kore/test/Test/Kore/Simplify/TermLike.hs
kore/test/Test/SMT.hs

This is the first step towards monomorphisation of the monad transformer stack used in `kore` (for improved performance). Previously there were two separate base monads:
```haskell
newtype NoSMT a = NoSMT {getNoSMT :: LoggerT IO a}
newtype SMT a = SMT {getSMT :: ReaderT SolverSetup (LoggerT IO) a}
```
The choice of the base monad was determined at runtime. Now we have a single base monad:
```haskell
newtype SMT a = SMT (Maybe SolverSetup -> LoggerT IO a)
```
This makes it possible to use a monomorphic monad where previously a polymorphic one was required:
```diff
execute ::
KoreSolverOptions ->
SmtMetadataTools StepperAttributes ->
[SentenceAxiom (TermLike VariableName)] ->
-   (forall exe. MonadExecute exe => exe r) ->
+   SMT r ->
Main r
```
Note that this change alone is insufficient …

Unify SMT and NoSMT; kill MonadExecute

---

kore/src/Kore/Exec.hs
kore/src/Kore/Simplify/Data.hs
kore/test/Test/Kore/Builtin/Bool.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Exec.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Rewrite.hs
kore/test/Test/Kore/Rewrite/Axiom/Matcher.hs
kore/test/Test/Kore/Rewrite/Axiom/Registry.hs
kore/test/Test/Kore/Rewrite/Function/Evaluator.hs
kore/test/Test/Kore/Rewrite/Function/Integration.hs
kore/test/Test/Kore/Rewrite/MockSymbols.hs
kore/test/Test/Kore/Simplify.hs
kore/test/Test/Kore/Simplify/Overloading.hs
kore/test/Test/Kore/Simplify/TermLike.hs
kore/test/Test/Kore/Unification/Unifier.hs

Previously, `Simplifier` was defined as follows:
```haskell
newtype SimplifierT smt a =
SimplifierT (StateT SimplifierCache (ReaderT (Env (SimplifierT smt)) smt) a)
type Simplifier = SimplifierT SMT
```
The `smt` type variable was instantiated to either `SMT` or `NoSMT`, depending on whether an external `SMT` solver was available. Now that `SMT` and `NoSMT` have been unified, we can define `Simplifier` as a base monad rather than a transformer:
```haskell
newtype Simplifier a =
Simplifier (StateT SimplifierCache (ReaderT Env SMT) a)
```
This definition is simpler and allows us to remove parameterization from `Env`.
As a knock-on effect, this forces us to remove some of the unnecessary polymorphism over `MonadSMT` in the following functions:
* `makeSerializedModule`
* `exec`
* `search`
* …

Simplifier as a base monad; drop SimplifierT 

---

kore/src/Kore/Exec.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/State.hs
kore/test/Test/Kore/Repl/Interpreter.hs

In those modules the abstract monad was never instantiated to anything but `Simplifier`, so it was straightforward to specialize it.

Specialize Kore.Exec and Kore.Repl to Simplifier

---

kore/src/Kore/Rewrite/Rule/Simplify.hs
kore/src/Kore/Simplify/Exists.hs
kore/src/Kore/Simplify/Simplify.hs
kore/test/Test/Kore/Rewrite/Rule/Simplify.hs
kore/test/Test/Kore/Simplify/TermLike.hs

These definitions were unused:
* `liftConditionSimplifier` is dead code
* `simplifyRewriteRule` is dead code
* `TestSimplifier` is dead code
* `simplifyRulePattern` is used in tests but not the app
* `simplifyPatternId` is a no-op wrapper around fromPattern

Remove a few unused definitions

---

kore/src/Kore/Rewrite/SMT/Evaluator.hs
kore/src/Options/SMT.hs
kore/src/SMT.hs

Fixes #3162
Add a new option, `--smt-retry-limit`, which controls how many times we will retry an SMT query that returned `Unknown`. Previously, we would always retry once.
I think it's done already, but it's unclear where tests for this feature should go (or even if there should be any, as retries were previously untested anyway).
---
-   [x] **Documentation.** Write documentation for new functions. Update documentation for …

Implement --smt-retry-limit option

---

.github/workflows/update.yml
flake.lock
flake.nix
nix/kore-ghc8107.nix.d/default.nix
nix/kore-ghc8107.nix.d/kore.nix
nix/kore-ghc923.nix.d/default.nix
nix/kore-ghc923.nix.d/kore.nix

Updated the `Update/ Nix` CI script to re-materialize both the current GHC8.10.* and the GHC9 expressions in the `nix/` folder.

[nix] Rematerialize GHC9 in the CI

---

.hlint.yaml
kore/app/exec/Main.hs
kore/kore.cabal
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Log/WarnUnexploredBranches.hs
kore/src/Kore/Reachability/Prove.hs
kore/test/Test/Kore/Reachability/Prove.hs
nix/kore-ghc8107.nix.d/kore.nix
nix/kore-ghc923.nix.d/kore.nix

Fixes #3119 
When a proof fails on one branch (or more, when using `--max-counterexamples`), the prover indicates with a warning if any other branches existed that were left unexplored.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were …

3119 output unexplored leaf count when failing

---

nix/kore-ghc923.nix.d/default.nix
stack-nix-ghc9.yaml

Also aligned the order of dependencies in `kore-ghc8107.nix.d/default.nix` and `kore-ghc923.nix.d/default.nix` to make comparisons easier.
Fixes ghc-9.2.3 build
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the …

HOTFIX added decision-diagrams to ghc-9.2.3 setup

---

kore/src/Kore/Exec/GraphTraversal.hs
kore/src/Kore/Reachability/Prove.hs
kore/test/Test/Kore/Reachability/Prove.hs

* The rewritten prover was returning a final instead of a stopped state when stopping at branches
* Proof depth for unproven claims was not logged at info level as before.
This fixes both problems, and adds a unit test for stopping at branches.
Fixes #3198
---
-   [ ] …

[3198] fix stopping prover on branches + logging unproven

---

kore/src/Kore/Unification/NewUnifier.hs

I was working on reimplementing pattern matching and Jost pointed out an issue with that code, which is that I was treating where bindings like they would only be evaluated when they were used, when in fact they get evaluated when the function that has the where binding gets called. This was leading to some issues in my code, but I realized also that it might be causing some performance degradations in the new unification algorithm as well, since that code was written in a similar style. And indeed, we were definitely making the mistake of using strict evaluation to evaluate some things that shouldn't need to get evaluated. So I made this PR. I have not tested the performance yet; want to make sure the tests pass first.
---
The author performs the actions on the checklist. The reviewer …

make a couple values lazy so they behave more like functions

---

.github/workflows/release.yml
.github/workflows/test.yml

Fixes #3165
This PR adds two new jobs to be ran at release, which build the haskell and cabal projects and cache the results. This way, the cache is persisted between feature branches as they originate from master (see the issue for details).
We also have fallback options when a new package is added to `kore.cabal`, which would otherwise cause a cache miss. Now, we should be able to get the last cache anyway and not have to build from scratch.

Fix Cabal and Stack CI caching

---

kore/app/exec/Main.hs
kore/app/rpc/Main.hs
kore/app/share/GlobalMain.hs
kore/kore.cabal
kore/src/Data/InternedText.hs
kore/src/Kore/Reachability/AllPathClaim.hs
kore/src/Kore/Reachability/OnePathClaim.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Rewrite/Rule.hs
kore/src/Kore/Rewrite/RulePattern.hs
kore/src/Kore/Rewrite/SMT/AST.hs
kore/src/Kore/Syntax/Id.hs
kore/src/Kore/Validate/SentenceVerifier.hs
kore/src/Kore/Variables/Fresh.hs
kore/test/Test/Data/InternedText.hs
kore/test/Test/Debug.hs
kore/test/Test/Kore/AST/Common.hs
kore/test/Test/Kore/Attribute/Sort/ConstructorsBuilder.hs
kore/test/Test/Kore/Rewrite/Axiom/Matcher.hs
nix/kore-ghc8107.nix.d/kore.nix
nix/kore-ghc923.nix.d/kore.nix
test/imp/sum-save-proofs-spec.k.save-proofs.kore.golden

Fixes #3112
Profiling revealed that there are a lot of operations over identifiers (i.e. `Kore.Syntax.Id`). Operations such as `==` and `hash/hashWithSalt` operate over text values which can be slow. 
This PR uses string interning to allow for faster implementations of `Eq`/`Hashable`/`Ord`.
* Each interned string has a unique ID. 
* This ID is generated via an incremental counter. Thus, a string's ID may be different across multiple runs.
* `Eq` simply checks if the two strings' IDs are equal
* `Hashable` hashes the ID. NB: since the ID may be different across multiple runs, hashes are not stable.
* `Ord` uses a "fast path" branch to check if the IDs are equal; if so, it returns `EQ`. Otherwise, it falls back on comparing the strings' contents.
We managed to squeeze a ~10% speedup. The …

[#3112] Intern IDs

---

kore/app/share/GlobalMain.hs
kore/src/Kore/IndexedModule/IndexedModule.hs
kore/src/Kore/Validate/DefinitionVerifier.hs
kore/src/Kore/Validate/ModuleVerifier.hs
kore/src/Kore/Validate/SentenceVerifier.hs

Fixes part of #3112
When `GlobalMain` loads a definition, it needs to verify that all `Id`s
are unique. The following chain of events is triggered:
```
GlobalMain.loadDefinitions
-> GlobalMain.verifyDefinitionWithBase
-> DefinitionVerifier.verifyAndIndexDefinitionWithBase
-> ModuleVerifier.verifyUniqueNames
-> SentenceVerifier.verifyUniqueNames
-> SentenceVerifier.verifyUniqueId
```
This process:
* Builds up a list of all visited `Kore.Syntax.Id`s in a `Map Text AstLocation`
* Un-interns the text contained inside `Id.getInternedId` (see
`SentenceVerifier.toUnparameterizedId`)
* Check whether that `Text` exists in the `Map Text AstLocation` (see
`SentenceVerifier.verifyUniqueId`)
The problem is that we're un-interning the string prematurely. This
would probably be faster if we took …

[#3112] Use `InternedText` for verifying IDs are unique

---

.github/workflows/test.yml
.github/workflows/update.yml
README.md
flake.lock
flake.nix
kore/src/Injection.hs
kore/src/Kore/Builtin/Int.hs
kore/src/Kore/Internal/Variable.hs
kore/src/Kore/Reachability/Prove.hs
kore/src/Kore/Unification/NewUnifier.hs
kore/src/Kore/Unparser.hs
kore/src/Kore/Variables/Fresh.hs
kore/src/SQL/SOP.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Syntax/Json/Roundtrips.hs
scripts/fourmolu.sh

Partially addresses [#3236](https://github.com/runtimeverification/haskell-backend/issues/3236)

Add fourmolu to nix flake as a convenient script

---

kore/src/Kore/Exec.hs
kore/src/Kore/Exec/GraphTraversal.hs
kore/src/Kore/ModelChecker/Bounded.hs
kore/src/Kore/ModelChecker/Step.hs
kore/src/Kore/Reachability/Claim.hs
kore/src/Kore/Reachability/Prove.hs
kore/src/Kore/Rewrite.hs
kore/src/Kore/Rewrite/Strategy.hs
kore/test/Test/Kore/Reachability/OnePathStrategy.hs
kore/test/Test/Kore/Rewrite.hs
kore/test/Test/Kore/Rewrite/Strategy.hs

Fixes #3243 
Removes type `Strategy` from the codebase. For readability, is replaced by an alias `type Step action = [action]`.
Some exports and re-exports  are removed from `Kore.Rewrite.Strategy` and `Kore.Rewrite` modules, too.
---
-   [ ] **Tests.** Write unit tests for …

3243 remove strategy type

---

kore/app/repl/Main.hs
kore/src/Kore/Exec.hs
kore/src/Kore/JsonRpc.hs
kore/src/Kore/Log.hs
kore/src/Kore/Log/DebugSolver.hs
kore/src/Kore/Log/ErrorBottomTotalFunction.hs
kore/src/Kore/Log/ErrorDecidePredicateUnknown.hs
kore/src/Kore/Log/ErrorEquationRightFunction.hs
kore/src/Kore/Log/ErrorEquationsSameMatch.hs
kore/src/Kore/Log/ErrorException.hs
kore/src/Kore/Log/ErrorOutOfDate.hs
kore/src/Kore/Log/ErrorParse.hs
kore/src/Kore/Log/ErrorRewriteLoop.hs
kore/src/Kore/Log/ErrorRewritesInstantiation.hs
kore/src/Kore/Log/ErrorVerify.hs
kore/src/Kore/Log/KoreLogOptions.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Log/SQLite.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/State.hs
kore/src/Log.hs
kore/src/Log/Entry.hs
kore/test/Test/Kore.hs
kore/test/Test/Kore/Repl/Interpreter.hs

Pre-requisite for  #3238
This PR refactors the log entry types type by adding the context directly to the `SomeEntry` type, making `ActualEntry` redundant. This change also removes context from the environment and instead bundles context with each `SomeEntry` directly. This is necessary when throwing errors, since we want to re-throw errors with the bundled context at each `logWhile` call, mirroring what we do with the log messages in this method.
Finally, the format of the log and error messages has been re-factored, with the context being moved at the bottom of the message for (hopefully) better readability:
```
kore-exec: [167082] Error (ErrorDecidePredicateUnknown):
Failed to decide predicate:
/* Sfa */
\not{_}(
/* Spa */
\equals{SortBool{}, _}(
/* Fl Fn D Sfa */ VarB:SortBool{},
/* …
```

Remove `ActualEntry` and refactor logging/throwing pretty printing

---

kore/test/Test/ConsistentKore.hs
kore/test/Test/Kore/Internal/TermLike.hs

Fixes #3244
Restricts the `TermLike` generator inside `ConsistentKore` to avoid generating terms that should only be present in a predicate (`\bottom`, `\exists`, `\forall`, `\iff`, `\implies`, `\not`, `\mu`, `\nu`). 
* `\top` was kept because otherwise the generator would fail on terms of sort `otherTopSort` and was at times looping (which should be investigated separately).
* (term-typed) `\and` and `\or` were kept as requested but are restricted to not occur within terms inside a predicate.
---
-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing …

3244 restrict `TermLike` test data generator

---

kore/kore.cabal
kore/src/Kore/JsonRpc.hs
kore/src/Kore/Network/JSONRPC.hs
nix/kore-ghc8107.nix.d/kore.nix
nix/kore-ghc923.nix.d/kore.nix

Part of #3287
This PR modifies the `kore-rpc` server to use `aeson-pretty` for encoding the JSON responses. This means we can sort the object keys for better readability. e.g. message before the change:
```json
{
"result": {
"state": {
"term": {
"format": "KORE",
"term": {
"args": [
{
"args": [...],
"tag": "App",
"sorts": [],
"name": "Lbl'-LT-'T'-GT-'"
},
{...}
],
"tag": "App",
"sorts": [],
"name": "Lbl'-LT-'generatedTop'-GT-'"
},
"version": 1
}
},
"next-states": [...],
"reason": "branching",
"depth": 0
},
"jsonrpc": "2.0",
"id": 1
}
```
vs the new version:
```json
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"reason": "branching",
"depth": 0,
"state": {
"term": {
"format": "KORE",
"version": 1,
"term": {
"tag": "App",
"name": "Lbl'-LT-'generatedTop'-GT-'",
"sorts": [],
"args": [
{
"tag": …
```

`kore-rpc` now uses aeson-pretty for encoding JSON messages

---

.github/workflows/profiling.yaml

Two more small adjustments to the profiling workflow.
Currently the final `on_success` and `on_failure` have the wrong token and fail to post a message, see https://github.com/runtimeverification/haskell-backend/actions/runs/3223960737/jobs/5274887739

Use correct token to post comment, avoid checkout work

---

kore/src/Kore/Builtin/AssociativeCommutative.hs

`addToMapDisjoint` uses an unexported helper function `addElementDisjoint` to insert elements into a `HashMap`. For some reason, these were written to accumulate a (reversed) list of the elements inserted along with the actual `HashMap`, and then throw the list away. This was both wasteful and confusing. Stop doing it.
Fixes #nnnn
---
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions …

Streamline addElementDisjoint

---

.github/workflows/kevm-performance-test.yaml
.github/workflows/profiling.yaml

* Adds a new KEVM performance run triggered by PR comments containing the string `/ KEVM-perf-run`. This currently runs a test with code from the PR as well as code from master (the branch point of the PR, `GITHUB_SHA`).
* Corrects the existing profiling run (triggered by comments linking to an attached `*.tar.gz`) to use code from the PR head if triggered from a PR.
Explanation for how we check out the code::
When triggering actions from an `issue_comment`, the pull_request context items that online references refer to for `actions/checkout` are not available. Instead:
* If the issue that received the trigger comment was a PR, the context `event.issue.pull_request` is filled. It contains a `url` where PR meta-data can be downloaded.
* The PR meta-data contains the current head SHA of the …

KEVM performance timing run triggered by comments + fix profiling run

---

kore/src/Kore/Rewrite/Axiom/Matcher.hs
kore/test/Test/Kore/Rewrite/Axiom/Matcher.hs
test/issue-3294/Makefile
test/issue-3294/test-spec.k
test/issue-3294/test-spec.k.out.golden
test/issue-3294/test.k

Refute matches where the pattern contains concrete elements that are not in the subject.
This crucially depends on the fact that we are _matching_, not _unifying_, so any variables in the subject will be treated as opaque constants.
The new test case checks that pattern `SetItem(0) SetItem(Y)` does not match subject `SetItem(1) SetItem(X)` even though these two terms would of course _unify_ with substitution `X = 0 /\ Y = 1`.
Fixes #3294
---
-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git …

3294 - add AC matching case (excess concrete elements in pattern)

---

kore/src/Kore/Log/DecidePredicateUnknown.hs

* Use quoting sugar fully to avoid manual lifts.
* Remove redundant quoting.
* Use `TemplateHaskellQuotes` instead of `TemplateHaskell` where it is sufficient.
Fixes #nnnn
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before …

Clean up some Template Haskell quoting

---

kore/src/Kore/Equation/Application.hs
kore/src/Kore/Internal/MultiExists.hs
kore/src/Kore/Internal/Substitution.hs
kore/src/Kore/ModelChecker/Simplification.hs
kore/src/Kore/Rewrite/Axiom/Matcher.hs
kore/src/Kore/Rewrite/ClaimPattern.hs
kore/src/Kore/Rewrite/Implication.hs
kore/src/Kore/Rewrite/RewritingVariable.hs
kore/src/Kore/Rewrite/Rule/Expand.hs
kore/src/Kore/Rewrite/RulePattern.hs
kore/src/Kore/Syntax/Variable.hs
kore/src/Kore/Unification/NewUnifier.hs
kore/src/Kore/Variables/Fresh.hs
kore/test/Test/Kore/Internal/MultiExists.hs

* Use `sequence` instead of a custom `combine` function to take repeated Cartesian products.
* Use `partitionEithers` rather than filtering and mapping to avoid using partial functions unnecessarily and to (potentially) collect some garbage more eagerly.
Fixes #nnnn
---
- …

Minor cleanups in Kore.Unification.NewUnifier

---

kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Reachability/Claim.hs
kore/src/Kore/Rewrite/Function/Evaluator.hs
kore/src/Kore/Simplify/AndTerms.hs
kore/src/Kore/Simplify/Ceil.hs
kore/src/Kore/Simplify/Equals.hs
kore/src/Kore/Simplify/Exists.hs
kore/src/Kore/Simplify/Iff.hs
kore/src/Kore/Simplify/Implies.hs
kore/src/Kore/Simplify/OrPattern.hs
kore/src/Kore/Simplify/Overloading.hs
kore/src/Kore/Simplify/Pattern.hs
kore/src/Kore/Simplify/Predicate.hs
kore/src/Kore/Simplify/Simplify.hs
kore/src/Kore/Simplify/SubstitutionSimplifier.hs
kore/src/Kore/Unification/NewUnifier.hs
kore/src/Kore/Unification/Procedure.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Rewrite/Function/Integration.hs
kore/test/Test/Kore/Rewrite/MockSymbols.hs

Work on https://github.com/runtimeverification/haskell-backend/issues/3325 (partially fixes this issue)
The 3rd leg of the Simplifier monomorphization.
Modules affected:
`Kore.Builtin.Map`
`Kore.Reachability.Claim`
`Kore.Rewrite.Function.Evaluator`
`Kore.Simplify.AndTerms`
`Kore.Simplify.Ceil`
`Kore.Simplify.Equals`
`Kore.Simplify.Exists`
`Kore.Simplify.Iff`
`Kore.Simplify.Implies`
`Kore.Simplify.OrPattern`
`Kore.Simplify.Overloading`
`Kore.Simplify.Pattern`
`Kore.Simplify.Predicate`
`Kore.Simplify.Simplify`
`Kore.Simplify.SubstitutionSimplifier`
`Kore.Unification.NewUnifier`
`Kore.Unification.Procedure`
---
-   [ ] **Summary.** Write a summary of the changes. …

Monomorphization of Simplifier, leg #3

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update.yml

Fixes #3397
Seems ubuntu-latest (i.e. 22.04) breaks the cachix action: https://github.com/cachix/cachix-action/issues/130

pin CI to ubuntu-20.04

---

kore/src/Kore/Builtin/Builtin.hs
kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Simplify/And.hs
kore/src/Kore/Simplify/AndTerms.hs
kore/src/Kore/Simplify/Equals.hs
kore/src/Kore/Unification/SubstitutionSimplifier.hs
kore/src/Kore/Unification/UnifierT.hs
kore/test/Test/Kore/Unification/Unifier.hs

Fixes #3362
Remove the redundant `UnifierT` from `NotSimplifier` as it creates nested `UnifierT`s.
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration …

Remove `UnifierT` from `NotSimplifier`

---

kore/src/Kore/Builtin/AssociativeCommutative.hs
kore/src/Kore/Rewrite/Function/Evaluator.hs
kore/src/Kore/Simplify/AndPredicates.hs
kore/src/Kore/Simplify/Condition.hs
kore/src/Kore/Simplify/Equals.hs
kore/src/Kore/Simplify/Not.hs
kore/src/Kore/Simplify/Simplify.hs

Work on https://github.com/runtimeverification/haskell-backend/issues/3325 (partially fixes this issue)
The 4th leg of the Simplifier monomorphization.
Modules affected:
`Kore.Builtin.AssociativeCommutative`
`Kore.Rewrite.Function.Evaluator`
`Kore.Simplify.AndPredicates`
`Kore.Simplify.Condition`
`Kore.Simplify.Equals`
`Kore.Simplify.Not`
`Kore.Simplify.Simplify`
---
-   [ ] **Documentation.** Write documentation for new functions. …

Monomorphization of Simplifier, leg 4

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update.yml

CI jobs recently started failing with
```
unknown compression method 'zstd'
```
This is because cachix started rolling out ZSTD compression for all it's caches, which means we need nix >=2.4, which is the first release which supports this new compression. THe affected CI runs were on 2.3.*.
See the announcement: https://blog.cachix.org/posts/2022-12-19-zstd-compression/

Update nix to >=2.4 in CI

---

kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/test/Test/Kore/Repl/Parser.hs

Fixes #2404 
Added commands `debug-rewrite`, `debug-rewrite-attempt` and `debug-rewrite-apply` which allow to switch on rewrite debugging for labeled rules in repl.
---
-   [x] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the …

add debug-rewrite repl command

---

kore/src/Kore/Builtin/Builtin.hs
kore/src/Kore/Builtin/EqTerm.hs
kore/src/Kore/Builtin/Map.hs
kore/src/Kore/Simplify/And.hs
kore/src/Kore/Simplify/AndTerms.hs
kore/src/Kore/Simplify/Equals.hs
kore/src/Kore/Simplify/Iff.hs
kore/src/Kore/Simplify/Implies.hs
kore/src/Kore/Simplify/In.hs
kore/src/Kore/Simplify/Not.hs
kore/src/Kore/Simplify/NotSimplifier.hs
kore/src/Kore/Simplify/TermLike.hs
kore/src/Kore/Unification/SubstitutionSimplifier.hs
kore/src/Kore/Unification/UnifierT.hs
kore/test/Test/Kore/Builtin/Bool.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Builtin/Endianness.hs
kore/test/Test/Kore/Builtin/KEqual.hs
kore/test/Test/Kore/Builtin/Set.hs
kore/test/Test/Kore/Builtin/Signedness.hs
kore/test/Test/Kore/Simplify/And.hs
kore/test/Test/Kore/Simplify/AndTerms.hs
kore/test/Test/Kore/Simplify/SubstitutionSimplifier.hs
kore/test/Test/Kore/Unification/Unifier.hs
kore/test/Test/Kore/Unification/UnifierT.hs

Passing around `NotSimplifier` manually is tedious and a bit confusing. Make it a class instead.
Fixes #nnnn
---
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as …

Make NotSimplifier a class

---

kore/app/repl/Main.hs
kore/kore.cabal
kore/src/Kore/Exec.hs
kore/src/Kore/Repl.hs
kore/src/Kore/Repl/Data.hs
kore/src/Kore/Repl/Interpreter.hs
kore/src/Kore/Repl/Parser.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Parser.hs
nix/kore-ghc8107.nix.d/kore.nix
nix/kore-ghc923.nix.d/kore.nix

Work on #2797 (partially fixes this issue)
Add commands to print unparsed configurations and axioms. 
At the moment, we do not unparse the claims, as there is a bug in the `kore-print` https://github.com/runtimeverification/k/issues/3105.
---
-   [ ] **Tests.** Write unit …

Add unparsed versions of commands for kore-repl

---

kore/app/exec/Main.hs
kore/app/repl/Main.hs
kore/app/share/GlobalMain.hs
kore/src/Kore/Exec.hs
kore/src/Kore/Log/WarnStuckClaimState.hs
kore/src/Kore/Reachability/Claim.hs
kore/src/Kore/Reachability/Prove.hs
kore/src/Kore/Repl.hs
kore/test/Test/Kore/Reachability/MockAllPath.hs
kore/test/Test/Kore/Reachability/OnePathStrategy.hs
kore/test/Test/Kore/Reachability/Prove.hs
kore/test/Test/Kore/Repl/Interpreter.hs
test/assume/Makefile
test/bottom-lhs/Makefile

This reverts commit eea7841322a69b9032a200880b8783381e961769.
The bug report inside https://github.com/runtimeverification/haskell-backend/issues/3432 reveals an issue regarding stuck configurations. The output on the second, stuck, branch becomes:
```
Kore (2)> step
kore-repl: [22375637] Warning (WarnStuckClaimState):
The configuration's term unifies with the destination's term, but the implication check between the conditions has failed. Location: /Users/petarmax/Projects/RV/_audits_Ethereum-optimism_optimism/optimism_foundry/out/specs/calldataspec-test-deposittransaction-emit-creationtrue-sender-equals-origin-spec.k:349:7-409:89
Context:
(InfoReachability) while checking the implication
kore-repl: [22380037] Warning (WarnStuckClaimState):
The left-hand side of the claim has been …
```

Revert "Add --allow-vacuous  (#3425)"

---

.github/workflows/kevm-performance-test.yaml
.github/workflows/profiling.yaml

Fixing Nix env setup by workflow and expect env of runner to container nix before running test.

Removing forced nix env setup in workflow

---

kore/src/Kore/Reachability/OnePathClaim.hs
kore/src/Kore/Reachability/Prove.hs

Fixes issue in https://github.com/runtimeverification/k/pull/3101
Branching on rule applications would result in an extra `\\bottom` state during one-path reachability proving. That state shouldn't be recorded inside the execution graph, but pruned immediately.
Before (with https://github.com/runtimeverification/haskell-backend/pull/3443):
---
After correction (with https://github.com/runtimeverification/haskell-backend/pull/3443):
---
-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git …

Immediately prune remainders of axiom applications

---

kore/src/Kore/Equation/DebugEquation.hs

Problem: When debugging equational rules we want to see in debug output rule label if it exists.
Solution: Extract label information from equation and add it to debug output.
Fixes #3428 
Fixes #3428 only regarding equational rules labels
---
-   [ ] **Tests.** Write unit …

Add equational rule label in debug output (#3428)

---

kore/src/Kore/Log/KoreLogOptions.hs
kore/test/Test/Kore/Repl/Interpreter.hs
kore/test/Test/Kore/Repl/Parser.hs

Problem: Several data types for debug options has attribute `selected` that makes ambiguities when `selected` is used to get internal value and makes `selected` attribute useless. Therefore to get internal value we stuck only to pattern matching that makes working with those types annoying because of long data type names.
Solution: Create type class `HasSelected` with `selected` function which just extracts the internal value and implement instances for each debug option data type. This allows use `selected` for every data type, what makes code more readable.

Refactoring of `KoreLogOptions`

---

kore/src/Kore/Rewrite/SMT/Evaluator.hs
kore/src/SMT.hs
kore/src/SMT/SimpleSMT.hs
kore/test/Test/Kore/Rewrite/SMT/Helpers.hs

Problem: Variable names and some predicate names are translated as `<n>` where n is a natural number. We need to keep original names in comments.
Solution: Put comment like `origName -> <n>` just before declaration.
Fixes #3462

[#3462] Keep original names in SMT transcript

---

.hlint.yaml
docs/2022-07-18-JSON-RPC-Server-API.md
kore/kore.cabal
kore/src/Kore/JsonRpc.hs
kore/src/Kore/JsonRpc/Base.hs
kore/src/Kore/Rewrite/Timeout.hs
nix/kore-ghc925.nix.d/kore.nix

Pert of  #3475 
Most of this code was already present, but resided in `Kore.JsonRpc`. The separate module makes it easier to re-use the code elsewhere.
New: `stop-reason: aborted` (never returned by code in this repository)
Also added some additional `FromJSON` and `ToJSON` instances

3475 align rpc protocol

---

kore/src/Kore/JsonRpc.hs

This is needed when using the old server as a library

Fully export module `Kore.JsonRpc`

---

kore-rpc-types/src/Kore/Syntax/Json/Types.hs
kore/src/Kore/Syntax/Json/Internal.hs
kore/test/Test/Kore/Syntax/Json.hs

Fixes  #3502
Implements `Left/RightAssoc` as suggested in the issue:
```json
{ 
"tag": "LeftAssoc",
"symbol": ...,
"sorts" : ...,
"argss": ...
}
```

Split MultiApp into LeftAssoc and RightAssoc

---

kore/src/Kore/Equation/Sentence.hs
kore/src/Kore/Equation/Validate.hs
test/issue-3170/Makefile
test/issue-3170/test.k

Problem: Right now we support equational rules where the LHS has a function(al) symbol, \\equals or \\ceil at the top. The backend should abort execution if it detects anything else in this spot and provide an appropriate error message containing the source location of the rule.
Solution: Match LHS to supported terms. And if it don't match, throw the `UnsupportedLHS` error.
Fixes #3170

[#3170] Detect if equational rules are unsupported

---

kore/src/Kore/Exec.hs
kore/src/Kore/Internal/Predicate.hs
kore/src/Kore/Rewrite/Rule.hs
kore/src/Kore/Rewrite/RulePattern.hs
kore/test/Test/Kore/Rewrite/Rule.hs

Fixes #3567 
The Haskell backend already supported the simplified encoding of rewrite rules. We needed to add support for the following:
- reverse ordering of the arguments inside the rule
- the backend should not expect priority rules to be of the "complex" form
After the frontend removes support for the antileft-encoding, we should remove the antileft field in the `RulePattern` type.
---
-   [ ] **Documentation.** Write …

Make necessary changes for new encoding of rewrites

---

kore-rpc-types/src/Kore/JsonRpc/Types/Log.hs

Make the `rule-id` field in the RPC failure logs optional, as the failure may not be attached to a particular rule, e.g. a message saying no rules could be found for the particular configuration.

RPC logging tweak

---

.github/workflows/release.yml
kore/kore.cabal

There seems to be a breaking change in the API for optparse-applicative v0.17 and above, which causes the master cabal cache run to fail

Lock down optparse-applicative to <0.17.1

---

kore-rpc-types/src/Kore/JsonRpc/Types.hs

Part of https://github.com/runtimeverification/hs-backend-booster/issues/182
* Adds instances necessary to use this type downstream. 
* Also renames `APIMethods` to `APIMethod`

Rename APIMethods to APIMethod + derive some instances

---

.hlint.yaml
cabal.project
kore/app/exec/Main.hs
kore/app/share/GlobalMain.hs
kore/kore.cabal
kore/src/Data/Compact/Serialize.hs
kore/src/Kore/IndexedModule/MetadataTools.hs
kore/test/Test/Kore/IndexedModule/MockMetadataTools.hs
kore/test/Test/Kore/Syntax/Json.hs
stack.yaml
stack.yaml.lock
test/serialized-definition/Makefile
test/serialized-definition/README.md
test/serialized-definition/a-to-f-definition.kore
test/serialized-definition/test-smoke-definition.kore
test/serialized-definition/test-totalSupply-definition.kore

Part of #3595 , and general house-keeping.
* Use a released version of `monad-validate`
* Simplify the `MetadataSyntax` type
* assimilate `Data.Compact.Serialize` and remove dependency on (unmaintained) `compact`
By accident, I discovered that the `cabal` build broke with the latest `hedgehog` update and included the 1-line fix here.
* be explicit about the argument type of a `Gen.element` call in the json generator.

3595 clean up library dependencies

---

kore/src/Kore/Equation/Application.hs
kore/src/Kore/Exec.hs
kore/src/Kore/JsonRpc.hs
kore/src/Kore/Simplify/API.hs
kore/src/Kore/Simplify/Simplify.hs
kore/test/Test/Kore/Builtin/Builtin.hs
kore/test/Test/Kore/Exec.hs
kore/test/Test/Kore/Rewrite/Function/Integration.hs
kore/test/Test/Kore/Rewrite/MockSymbols.hs

Part of #3624
Omits tracing simplifications and rewrites when no trace was requested by the caller.
This fixes a memory issue for execute requests with large depth - traces would otherwise take up large amounts of heap and bring the server down.

3624 omit trace collection unless required

---

kore/src/Kore/Rewrite/SMT/Lemma.hs
kore/src/Kore/Simplify/Condition.hs

Fixes #3619
The definition provided in the above issue now throws the following error:
```
kore-rpc: [4462799] Error (ErrorException):
The definitions sent to the solver may not be consistent (Z3 timed out).
CallStack (from HasCallStack):
error, called at src/Kore/Rewrite/SMT/Lemma.hs:180:9 in kore-0.60.0.0-inplace:Kore.Rewrite.SMT.Lemma
```

Fail when checking definition with Z3 returns Unknown

---

flake.lock

Downstream nix setup for `hs-backend-booster` fails with "unknown index state" when trying to  upgrade to 6.0.x versions.

Update haskell-nix dependency to enable upgrading K release downstream

---

kore/src/Kore/JsonRpc.hs

This PR fixes the case of an `ExecuteRequest` with logging parameters `{logSuccessfulRewrites = Just True, logSuccessfulSimplifications = Nothing}` not retuning any logs (except of terminal/cut-point case).

Use (||) directly when enabling tracing

---

kore/src/Kore/Exec.hs

The backend can currently return branching with a single branch

HOTFIX rpc exec branch prune

---

kore-rpc-types/kore-rpc-types.cabal
kore-rpc-types/src/Kore/JsonRpc/Types.hs
kore-rpc-types/src/Kore/JsonRpc/Types/Depth.hs
kore-rpc-types/src/Kore/JsonRpc/Types/Log.hs
kore/src/Kore/JsonRpc.hs

This PR modifies the `LogEntry` type in `kore-rpc-types` in two ways:
* add `origianlTerm` into `Rewrite` log entry constructor (and emit Nothing for now in Kore to retain the current behavior. This change is not necessary at the moment, but we may need to log these terms in future.
* Add `Fallback` constructor to `LogEntry` to enable `kore-rpc-booster` to emit a trace when it falls back from Booster to Kore.

Add `Fallback` to `LogEntry`

---

kore-rpc-types/kore-rpc-types.cabal
kore-rpc-types/src/Kore/JsonRpc/Types.hs
kore/src/Kore/JsonRpc.hs
test/rpc-server/add-module/add/response.golden

Previously `decodeKoreRpc` in the booster would treat certain terms as an AddModule response that were not in fact such a term. By changing how we parse and unparse the json corresponding to AddModule responses, I am hoping to fix this.
---
-   [ ] **Tests.** Write unit …

add AddModuleResult type

---

flake.nix

Minor tweak to the nix derivation to read the z3 version from the source code of the z3 repo, specifically from `scripts/release.yml`. Because nix doesn't read YAML, we use a regex, which is slightly hacky but should be stable enough. This change is useful when overriding z3 via
```
nix build github:runtimeverification/haskell-backend#kore-exec --override-input z3-src github:Z3Prover/z3/z3-4.8.15
```
With this change, we build
```
/nix/store/m9filf9jjcwihfrfglqv01wnawg6jdq9-z3-4.8.15
```
whereas before this change, the package name would have been
```
/nix/store/...-z3-4.12.1
```
even though calling
```
/nix/store/...-z3-4.12.1/bin/z3 --version
```
would have reported 4.8.15.

Nix - read the z3 version from release.yml

---

kore/src/Kore/Parser/Parser.y

This change brings back parsing of `\*-assoc{}(\or, ...)` constructs which were used in `definition.kore` files before October 2023.

re-enable parsing older definitions (or in *assoc)

---

kore/src/Kore/Rewrite/SMT/Evaluator.hs

This (hopefully) fixes https://github.com/runtimeverification/k/issues/3729, specifially the error below, thrown [here](https://github.com/runtimeverification/haskell-backend/blob/58a101d279efb64e7042bab2968a22f27a9e2706/kore/src/SMT/SimpleSMT.hs#L444-L450)
```
kore-exec: [41516716] Error (ErrorException):
user error (Unexpected result from the SMT solver:
Command: (push 1 )
Expected: success
Result: (error "line 178 column 8: push canceled" )
)
```
This error occurs when smt-limit is low and we send an assert query to the solver. When this happens, we want to re-try instead of letting the error bubble up, as it currently does.
I have tested this and confirmed that at a threshold level of `smt-timeout` where Z3 fails intermittently, with this change, we re-try the specified number of …

Catch IOError when a query times out and retry correctly

---

kore/src/Kore/JsonRpc.hs

This PR changes the JSON RPC handler for `DecidePredicateUnknown`.
Before we pretty-printed (ugly-printed, let's be honest) the predicate and returned that as the "data" field of the JSON RPC error. Now we conjunct the predicates and side conditions, serialize the conjunction as JSON and return that as "data".
This will solve two sources of paper cuts when using Kontrol:
* the server won't spam `stderr` with incomprehensible Kore output when encountering difficult predicates
* `pyk`/`kontrol` can handle server errors with `"code": 5, "message":"Smt solver error` better, for example by pretty-printing the JSON predicate into surface K or tool-specific representation.

Serialize the unknown predicate as JSON on `DecidePredicateUnknown`

---

kore/src/Kore/JsonRpc.hs
kore/src/Kore/Log/DecidePredicateUnknown.hs

Follow-up for #3694.
Knowing which rule caused `DecidePredicateUnknown` is useful, but seeing the Kore of the predicate in the logs is not, since we now have it in the response anyway.

Reduce `DecidePredicateUnknown` pretty instance to only rule locations

---

kore/src/Kore/Rewrite/SMT/Lemma.hs
kore/src/SMT.hs

When calling Z3 to check consistency of the prelude/smt-lemmas, if `--smt-tactic TACTIC` was given, we were calling `(check-sat-using TACTIC)`. That causes problems if we give an experimental tactic. We should always use the plain `(check-sat)` at the initialization step.

Use plain `(check-sat)` when checking consistency of SMT lemmas

---

docs/2022-07-18-JSON-RPC-Server-API.md
kore-rpc-types/src/Kore/JsonRpc/Types.hs
kore/src/Kore/JsonRpc.hs

Add `"unknown-predicate"` as an optional field to `"execute"` JSON-RPC response. The intention is to change servers' response on encountering `ErrorDecidePredicateUnknwon`, i.e. when Z3 returns Unknwon while checking a rewrite rule's side condition.
The current behavior is to return `SmtSolverError` even if progress was made. I.e. we could have made 100 rewrite steps and only get Unknown during step 101.
Instead, we should return the state before the error, and the predicate that Z3 had trouble deciding. This way, the client will be able to make an informed decision about that to do next and/or report the problematic predicate to the user, so that they can add lemmas if appropriate.
Unfortunately, altering `kore-rpc` itself is quite difficult. therefore I will implement a prototype of …

Add optional unknown predicate into "execute" response

---

kore/src/Kore/BugReport.hs

When something goes wrong while internalizing `definition.kore`, we can see the reason in the created bug report archive. This approach proves to be obsolete in today's workflow, where `pyk`-level bug reports are dominant, and server-level bug reports are not used at all.
With this change, we can see  the contents of `error.log` on `stderr` directly after `kore-rpc-booster` shutdown, saving the need to unpack the bug report archive. For example: 
```
[Info#proxy] Loading definition from /home/geo2a/.cache/kdist-46a7e08/evm-semantics/haskell/definition.kore, main module "EDSL"
[Info#kore] : Info (LogMessage):
Reading the input file TimeSpec {sec = 0, nsec = 21030748} []
[Info#kore] : Info (LogMessage):
Parsing the file TimeSpec {sec = 0, nsec = 1467} []
[Info#kore] : Info (LogMessage): …
```

Print error message on `stderr` before writing the bug report

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update-regression-tests.yml
kore/src/Kore/Attribute/Symbol/SymbolKywd.hs
kore/src/Kore/Builtin/Endianness.hs
kore/src/Kore/Builtin/Signedness.hs
kore/src/Kore/Internal/Symbol.hs
kore/test/Test/Kore/Attribute/Symbol.hs
kore/test/Test/Kore/Attribute/Symbol/SymbolKywd.hs
kore/test/Test/Kore/Internal/Symbol.hs

The definition is now allowed to include attributes `symbol(<arg>)` . No functionality is currently using this attribute shape.
Also includes updates to the github actions to avoid warnings about nodejs-16.
Fixes https://github.com/runtimeverification/k/issues/3990

optional text argument for symbol attribute (empty text = no argument)

---

kore/app/rpc/Main.hs
kore/src/Kore/JsonRpc.hs

Fixes a corner case tested for in https://github.com/runtimeverification/pyk/pull/871 where
* we send module `M1` with the name `"m<hash of M2>"` and `"name-as-id": true`
* we send `M2`
In this case, the server should reject `M2`, but currently both requests succeed, with `M1` being overridden by `M2`

Add module fix

---

design-decisions/2020-02-06-One-Path-Deterministic.md
test/all-path/00-basic/01-one-rule/path.k
test/all-path/00-basic/02-cyclic-rule/path.k
test/all-path/00-basic/03-concurrent-rules/path.k
test/all-path/00-basic/04-different-length/path.k
test/all-path/02-constructors/00-case-analysis/path.k
test/all-path/03-unification/set-select/path.k
test/all-path/limitations/interfering-specs/path.k
test/functions/functions.k
test/issue-1665/issue-1665-spec.k
test/issue-1665/test.k
test/issue-2138/issue-2138-spec.k
test/itp-nth-ancestor/chain.k
test/itp-nth-ancestor/nth1-spec.k
test/itp-nth-ancestor/nth2-spec.k
test/k-equal/test-k-equal.k
test/lib/adomains.k
test/lib/astate.k
test/overloads/simple-lists/simple-lists.k
test/save-proofs/test-2-spec.k

Part of runtimeverification/k#4009
Replace usages of deprecated tokens:
- `syntax priorities` with `syntax priority`
- `require` with `requires`
- `import` with `imports`

Replace usages of `priorities`, `require`, and `import`

---

kore-rpc-types/src/Kore/JsonRpc/Error.hs
kore/src/Kore/JsonRpc.hs

We are currently nesting the two types of errors in the booster. it would therefore be better to emit objects which can have both the context and term

unify ErrorWithTerm and ErrorWithContext

---

.gitignore

Fixes #3803 
Note that the real fix is:
```
ln -s booster/cbits cbits
```
and this change avoids committing the symlink.

Ignore fantom cbits

---

.github/workflows/test.yml

I've noticed we are running unit test as part of the "'Nix / Integration'" job, but we also have a dedicated "'Nix / Unit Tests" job that runs them in exactly the same way, so we may as well skip them in the integration tests job.

Do not run unit test as part of integration tests

---

booster/tools/booster/Proxy.hs
booster/tools/booster/Server.hs

Logs are showing that the simplification performed before fall-back execute requests is often not productive. This PR provides a server flag to switch it off and save the overhead.
OTOH, the simplification may prune spurious branches, saving a `Branching` re-execution in `kore-rpc` in some cases. Therefore the default behaviour is still to simplify before fallback requests.

Booster flag to disable simplification before fall-back request

---

booster/tools/booster/Server.hs
dev-tools/kore-rpc-dev/Server.hs

Previously, the logging filter would always enable JSON logs, even without `-l SimplifyJson`.

Fix json logging redirection predicate

---

docs/2022-07-18-JSON-RPC-Server-API.md

fixes [#3834](https://github.com/runtimeverification/haskell-backend/issues/3834)

Update docs with information about new branching fields

---

.github/workflows/test.yml
booster/library/Booster/Pattern/Base.hs

We do not currently re-trigger the CI run if formatting is pushed within the CI run.

Retrigger run when pushing formatting changes via CI

---

booster/library/Booster/Pattern/Base.hs
booster/unit-tests/Test/Booster/Pattern/InternalCollections.hs

Fix pattern synonyms to store e.g. {...REST} as just REST

Fix collections internalisation

---

booster/tools/booster/Server.hs

* like `kore-rpc` , `kore-rpc-booster` should read additional options from an environment variable.
* This PR chooses the same variable name as for `kore-rpc` for consistency and to avoid it getting too long.
Use case: testing optional optimisation in performance tests without having to modify the pytest framework or the `KoreServer` in `pyk`

Allow kore-rpc-booster to read additional options from KORE_RPC_OPTS

---

docs/2022-07-18-JSON-RPC-Server-API.md

The documentation mentions `log-timing` is a valid option for `implies` and `simplify`: https://github.com/runtimeverification/haskell-backend/blob/5db6dfc03c9f3b18191bf35954a966a59c441cba/docs/2022-07-18-JSON-RPC-Server-API.md?plain=1#L304
This PR includes the parameter under the corresponding request descriptions.

Add `log-timing` for `implies` and `simplify` in docs

---

booster/library/Booster/Pattern/ApplyEquations.hs
booster/library/Booster/Pattern/Rewrite.hs

For warnings during evaluation/simplification, the warning message advises users to use a certain log context. This PR changes the recommended log context to `*abort*detail`, for which informative details have been added in all call sites of `logWarn`.
At the same time, the warning about too many iterations was duplicated in the `Rewrite` module, and was therefore downgraded to `Simplify` level there.
Fixes #3849

Add details to evaluation aborts that cause warnings

---

booster/library/Booster/JsonRpc.hs
booster/tools/booster/Proxy.hs
docs/2022-07-18-JSON-RPC-Server-API.md
kore-rpc-types/src/Kore/JsonRpc/Types.hs

Partially reverts  #3846 by disabling the implication endpoint in booster until we figure out and address #3857

Partially revert the implication endpoint

---

booster/tools/booster/Proxy.hs
booster/tools/rpc-client/RpcClient.hs
cabal.project

* `--interim-simplification` problem: When `maxDepth < forceFallback` , the proxy was considering a genuine `DepthBound` result as an artefact caused by the interim simplification, and would try to continue execution.
* The `cabal.project` file was set up to never profile any `booster` or `kore-rpc-types` code
* When given a path to a non-existing file as input, `RpcClient` reported a server connection error and retried (the criterion for recognising connection errors was to general).

Fix some small problems

---

flake.lock

We need to update Nixpkgs to get LLVM 18 in the LLVM backend; this is the corresponding mirror change that will keep the two backends in sync with each other.
See: https://github.com/runtimeverification/llvm-backend/pull/1070

Update to new Nixpkgs

---

kore/src/Kore/Builtin/Map.hs
kore/test/Test/Kore/Builtin/Definition.hs
kore/test/Test/Kore/Builtin/Map.hs

Fixes #3898 
`MAP.updateAll` was previously returning `notImplemented` (always returning `NotApplicable`) but this causes an error when its arguments are fully-concrete.
This change implements the hook for fully-concrete maps, by doing the obvious update of the underlying hash map and special-casing empty maps.

`MAP.updateAll` implementation on concrete arguments

---

.github/workflows/release.yml
.github/workflows/test.yml
dev-tools/booster-dev/Server.hs
flake.nix

Add context "booster" to all log messaged emitted by `booster-dev`, in line with `kore-rpc-booster`, so that we can use the same filters with both executables.

Fix `booster-dev` context logging

---

.github/workflows/release.yml
.github/workflows/test.yml
booster/library/Booster/CLOptions.hs
booster/library/Booster/Definition/Attributes/Base.hs
booster/library/Booster/Definition/Attributes/Reader.hs
booster/library/Booster/Definition/Base.hs
booster/library/Booster/Definition/Util.hs
booster/library/Booster/Pattern/ApplyEquations.hs
booster/library/Booster/Pattern/Index.hs
booster/library/Booster/Pattern/Rewrite.hs
booster/library/Booster/Syntax/Json/Internalise.hs
booster/library/Booster/Syntax/ParsedKore.hs
booster/library/Booster/Syntax/ParsedKore/Internalise.hs
booster/library/Booster/Util.hs
booster/test/internalisation/mx-hs-kasmer-definition0.kore.report
booster/test/llvm-integration/LLVM.hs
booster/tools/booster/Server.hs
booster/unit-tests/Test/Booster/Fixture.hs
booster/unit-tests/Test/Booster/Pattern/ApplyEquations.hs
booster/unit-tests/Test/Booster/Pattern/Index.hs
booster/unit-tests/Test/Booster/Pattern/Rewrite.hs
dev-tools/booster-dev/Server.hs
dev-tools/parsetest-binary/ParsetestBinary.hs
flake.nix

* The index on the `k` cell is generalised to an index on one or more arbitrary cells containing K sequences (default stays the same, the `k` cell only). 
* The cell(s) to index are read from a definition attribute named `indexCells`. This attribute is expected to contain an argument list of names _quoted as all symbols in kore_  (e.g., `Lbl'-LT-'k'-GT-'` for the `k` cell).
* Alternatively, the cell(s) to index can be overridden by a command line option `--index-cells CELL1,CELL2,...` to `booster-dev` and `kore-rpc-booster`.  This option takes plain names (like `k` for the `k` cell), which are quoted and prefixed before overriding the definition attribute of the loaded definition.
Fixes #3874

3874 use several cells to index

---

kore/src/Kore/Rewrite/SMT/Evaluator.hs

Some `kasmer` proof rely heavily on simplifications and start failing when we stop applying them.
This reverts commit 40c912bf769b3bf7cfae8552e0faf698ac727920.

Revert "Do not retry SMT query when WarnDecidePredicateUnknown"

---

booster/library/Booster/Pattern/Rewrite.hs
booster/library/Booster/SMT/Interface.hs

This PR makes sure we do not immediately hard-stop with an RPC error when receiving `Unknown` from Z3 in Booster.
- use pure exceptions in SMT functions, check results at call sites to `checkPredicates`
- threat Z3-`Unknown` predicates as any other unclear conditions: abort rewriting

Abort on "Unknown" side conditions, don't crash

---

booster/library/Booster/Pattern/Rewrite.hs
booster/library/Booster/SMT/Interface.hs

* Re-introduces the 'indeterminate' result for checkPredicates, and returns that on inconsistent ground truth.
* In the rewrite, aborts on `SMTSolverUnknown` when checking requires clauses, but throws actual exceptions (terminating the request) on other SMT errors (translation error, general error).
Follow-up to #3907

HOTFIX re-introduce indeterminate result for `checkPredicates` instead of exceptions

---

scripts/booster-analysis.sh

The previous change introduced an `-or` which requires repeating the `-print0`.

Make booster-analysis script work for *tar again

---

.github/workflows/master.yml

Fixes an oversight in the job dependency changes of #3924 
I also pushed a branch named `release` to github to make the `version-bump` job work.

Remove cross-workflow dependency from master:cache-stack job

---

booster/library/Booster/Log/Context.hs
docs/logging.md

This change allows us to write the following filter:
```
kore|booster>!(kore-term|detail).
``` 
i.e. log everything from kore and booster except for the innermost `kore-term` or `detail` contexts, which contain the pretty printed terms and extra details about e.g. rule locations which may be too noisy. This was previously not possible because we couldn't apply `!` over a bracketed expression. I've added conjunction `&` for good measure, so we could also write the above filter as `kore|booster>!kore-term&!detail.`

Implement conjunction and negation over glob terms

---

.github/workflows/release.yml

Follows the example from https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job to store the version number in a job output.

HOTFIX store version in step output and read back to publish release

---

.github/workflows/master.yml
.github/workflows/release.yml
.github/workflows/test.yml

We noticed that we are trying to cache the cabal store, however, Nix already does this for us, as we have seen from the fact that cache has been broken but builds run just as fast. Therefore, this caching should be removed entirely.
This also fixes an issue where the cache key on master was not being built correctly, because we forgot to set the `ghc_version` ENV variable. THis also meant we were building with a different version of GHC on master push vs the feature branches.

Remove cabal cache form CI

---

booster/library/Booster/CLOptions.hs
booster/library/Booster/Pattern/ApplyEquations.hs

Fixes #3927
This PR disables the display of the three equation-related warning in Booster by default. They can be re-enabled by the flag `-l EquationWarnings`, which is a shorthand to the context expression `--log-context booster>(simplification *|function *)>warning`.

Add `-l EquationWarnings` and `warning` context in Booster

---

booster/library/Booster/CLOptions.hs

The context string was changed in prior PR #3919  but the configuration options were not, leading to incomplete data for abort analysis..

HOTFIX change condition to constraint in context options

---

booster/tools/booster/Server.hs
kore/kore.cabal
kore/src/Kore/Log/DebugAppliedRewriteRules.hs
kore/src/Kore/Log/DebugRewriteRulesRemainder.hs
kore/src/Kore/Log/Registry.hs
kore/src/Kore/Rewrite/RewriteStep.hs
kore/src/Log/Entry.hs

This PR allows logging Kore's rewrite rule remainders in full.
Example log message with `'kore>remainder'`:
```
[kore][execute][remainder][detail] After applying  1  rewrite rules there is a satisfiable remainder condition:  \not{_}(\not{_}(\equals{SortInt{}, _}(ConfigVarCONTRACT'Unds'ID:SortInt{}, Lbl'UndsAnd-'Int'Unds'{}(\dv{SortInt{}}("1461501637330902918203684832716283019655932542975"), Lbllookup{}(ConfigVarCONTRACT'Unds'STORAGE:SortMap{}, \dv{SortInt{}}("1"))))))
```
and in json:
```
{"context":["kore","execute","remainder",{"term":"39a4b3d"},{"rules-count":"1"}],"message":{"format":"KORE","version":1,"term":{"tag":"Not","sort":{"tag":"SortApp","name":"SortBool","args":[]},"arg":{"tag":"Not","sort":{"tag":"SortApp","name":"SortBool","args":[]},"arg":{"tag":"Equals","argSort":{"tag":"S …
```

Log rewrite rule remainders

---

.github/workflows/release.yml

This is a simple oversight on my part; I forgot to replicate this stanza from the test to the release job when making #3955.

Install missing prerequisites for Ubuntu package on release

---

scripts/performance-tests-kevm.sh

https://github.com/runtimeverification/evm-semantics/pull/2504 has renamed the `test-prove-pyk` Makefile target to `test-prove-rules`. This PR now runs this target when evaluating KEVM performance.

Fix KEVM script by calling the new Makefile target

---

dev-tools/package.yaml
dev-tools/process-logs/Main.hs
kore-rpc-types/src/Kore/JsonRpc/Types/ContextLog.hs
kore/src/Kore/Log/DebugAppliedRewriteRules.hs

First version so we get a baseline for additional code to add later.
filters the log on stdin or given in file option `-i`
```
$ .build/kore/bin/process-logs filter "proxy>timing." "proxy."  -i log-with-timestamps.json
{"timestamp":"2024-07-05T02:04:09.646316","context":["proxy"],"message":"Loading definition from ./definition.kore, main module \"MX-WASM\""}
{"timestamp":"2024-07-05T02:04:16.971803","context":["proxy"],"message":"Starting RPC server"}
{"timestamp":"2024-07-05T02:05:32.49184","context":["proxy"],"message":"Processing request 1"}
{"timestamp":"2024-07-05T02:05:32.49184","context":["proxy"],"message":"Starting execute request"}
{"timestamp":"2024-07-05T02:05:43.138762","context":["proxy"],"message":"Booster Stuck at Depth {getNat = 0}"} …
```

Start of a log processing tool

---

booster/tools/rpc-client/RpcClient.hs

- when running a tarball, consider the requests from all directories, not just the one prefixed with `rpc_`
- allow creating parent directories when unpacking a tarball

Remove directory name assumption in `kore-rpc-client`

---

booster/tools/booster/Server.hs

Most `[proxy]` log entries are prefixed with `[request ID]`. The exception are are entries that are emitted in-between requests.
Before:
```
[proxy] Starting RPC server
[proxy] Processing request 0
[proxy] Starting execute request
[request 0][booster][execute][depth] 0 steps.
...
[proxy] Booster Aborted at Depth {getNat = 0}
[proxy] Simplifying booster state and falling back to Kore
[proxy] Simplifying execution state
...
```
After:
```
[proxy] Starting RPC server
[proxy] Processing request 0
[request 0][proxy] Starting execute request
[request 0][booster][execute][depth] 0 steps.
...
[request 0][proxy] Booster Aborted at Depth {getNat = 0}
[request 0][proxy] Simplifying booster state and falling back to Kore
[request 0][proxy] Simplifying execution state
...
```

Add `[request id]` context to relevant proxy log entries

---

booster/test/rpc-integration/test-issue3764-vacuous-branch/response-branch-after-one.json
booster/test/rpc-integration/test-issue3764-vacuous-branch/response-branch-in-zero.json
booster/tools/booster/Proxy.hs

Increase depth and emit a trace when pruning vacuous branches in `Proxy.hs`

---

booster/tools/booster/Proxy.hs

Only emit proxy branch-eliminating rewrite trace when asked

---

booster/library/Booster/SMT/Interface.hs
booster/library/Booster/SMT/Runner.hs

Fixes (hopefully) #3959 by making the `solver`/`solverClose` handles into an `IORef`. This way, we can be (reasonably) sure that when we write the new handles into the `IORef`, there will be no other references held to the old ones elsewhere, which was previously preventing the old z3 instance from terminating, leaving a zombie process.

Use an IORef to hold a reference to the solver/solverClose

---

booster/package.yaml
booster/tools/rpc-client/RpcClient.hs

Fixes #3978 
This change is backwards compatible and works on the old style tarballs which do not contain the `sequence` folder.

Order requests from a tarball based on the sequence folder

---

booster/library/Booster/CLOptions.hs
booster/test/llvm-integration/LLVM.hs
booster/test/llvm-integration/definition/llvm.k

* Adds the new `request <N>` prefix  in front of  the `proxy` context to the `-l Aborts` short-hand
* updates `llvm.k` to use `symbol(Bla)` instead of `klabel(Bla), symbol` to avoid warnings

House-keeping: adjust `-l Abort` log switch, update llvm.k test definition

---

.github/workflows/master.yml

The previous PR #3983 had an error in the line that pushes the tag (missing `origin`) see https://github.com/runtimeverification/haskell-backend/actions/runs/9972668145/job/27556861219

HOTFIX master.yml: Push version tag to `origin`

---

.github/workflows/master.yml

The `v<VERSION>` tags are already used by the `release` branch, so use `release-<VERSION>` for `master` to avoid conflicts

Use a `release-` prefix for the tag on `master`

---

booster/library/Booster/Pattern/ApplyEquations.hs
booster/library/Booster/Pattern/Rewrite.hs

Booster's rewriting algorithm, upon getting stuck (or aborting due to `RuleApplicationUnclear`), will try so simplify the configuration once and retry applying rules. When we cannot not finish simplifying the term due to a `TooManyIterations`, we throw the partial result away and fail.
This PR handles the `TooManyIterations` exception and attempts applying rewrite rules to the partially simplified term.

Recover from `TooManyIterations` when simplifying during rewriting

---

package/debian/changelog
package/debian/control.jammy
package/debian/copyright

This PR removes any final references to my contact details from the LLVM backend repo, and assigns them to @geo2a  instead.

Remove references to my contact details from repo

---

booster/library/Booster/Pattern/Rewrite.hs

Supplies the SMT solver from the `performRewrite` instead of a (wrong) value from `RewriteStepState`.
We don't need the SMT solver in the `RewriteStepState` as it won't be modified, and the old code was also setting it to `Nothing`.

remove SMT solver from RewriteStepState, use solver from arg. to evaluate

---

booster/library/Booster/JsonRpc.hs
booster/library/Booster/Pattern/Rewrite.hs
booster/test/rpc-integration/resources/questionmark-vars.k
booster/test/rpc-integration/test-questionmark-vars/README.md
booster/test/rpc-integration/test-questionmark-vars/response-one-ques-substitution.booster-dev
booster/test/rpc-integration/test-questionmark-vars/response-one-ques-substitution.json
booster/test/rpc-integration/test-questionmark-vars/state-one-ques-substitution.execute
booster/unit-tests/Test/Booster/Pattern/Rewrite.hs

When rewriting with rules that have existentials on the RHS, booster needs to rename these existential variables to avoid collisions.
However, the input is pre-processed to recognise predicates of the form `X ==K expr` and apply them (after checking/vetting) as a _substitution_ to the configuration and (other) path conditions.
As a result, the variable names in the substitution are not present in the pattern any more when rewriting. The substitution is added back (as additional information) in the output, so subsequent simplification steps will apply it again, falsely, if variable names from the substitution are reused during rewriting.
As a solution, we supply the "forbidden variable names" to the rewriter. Alternatively, we could stop including the applied substitution in the output, …

Booster: Avoid var. names from input substitution when creating new ones

---

booster/library/Booster/Pattern/Match.hs
booster/unit-tests/Test/Booster/Pattern/InternalCollections.hs
booster/unit-tests/Test/Booster/Pattern/MatchEval.hs
booster/unit-tests/Test/Booster/Pattern/MatchImplies.hs
booster/unit-tests/Test/Booster/Pattern/MatchRewrite.hs

This PR adds rudimentary matching of internalized sets: only empty sets are allowed to match, and an indeterminate result is returned for non-empty sets.

Allow matching empty sets

---

booster/library/Booster/Pattern/ApplyEquations.hs
booster/library/Booster/Pattern/Rewrite.hs

To avoid situations where the cache contains successive mappings `e -> e1 -> e2 -> e3 ... -> e_n` (a "lookup chain"), the following modifications are made:
1. When inserting `e -> e1`, first check whether `e1 -> e2` is in the cache, and insert `e -> e2` instead in this case.
2. When looking up `e` and a binding `e -> e1` is found, check whether a binding `e1 -> e2` is also in the cache.
In this case, update the binding for `e` to `e -> e2` and return `e2`.
This will eventually lead to removing all lookup chains that may exist in a cache (for "interesting" cached values that are being looked up), without the risk of a loop.
Assume the following:
* the cache was initially empty;
* insertions and lookups are performed as described above;
* the cache contains a lookup chain `e -> e1 -> e2`. …

EXPERIMENTS: shorten cache lookup chains, invalidate cache on new ensures

---

booster/library/Booster/LLVM.hs
booster/library/Booster/Pattern/ApplyEquations.hs
booster/library/Booster/Util.hs
booster/test/llvm-integration/LLVM.hs
booster/tools/booster/Stats.hs

This change steps away from maximising the terms we send to the LLVM backend for evaluation, and only sends terms with an unevaluated function call at the top. It addresses a particular constellation that has been observed in downstream semantics/proofs:
* a configuration containing large data structures in cells that remain unchanged
* a long-running sequence of rewrites that keep inserting concrete function applications into cells required for the next rewrite step,
* and therefore require frequent configuration simplifications
Each time the configuration is simplified, the large unchanged data structure is sent to the LLVM backend, which incurs considerable overhead.
On the flip side, we will send each function that needs to be evaluated individually. However, rewrites or equations …

Only send unevaluated functions to LLVM

---

booster/library/Booster/CLOptions.hs
booster/library/Booster/SMT/Interface.hs
booster/library/Booster/SMT/Runner.hs

This change will let us call `z3` with `smt.ematching=false` in booster, which seems to help with non-linear arithmetic.

Pass args to the smt solver via `--smt-arg`

---

booster/library/Booster/SMT/Interface.hs

Followup to #4017 addressing a potential issue I noticed whilst refactoring the SMT interface in booster. Namely, we set the hard-coded timeout value when checking the consistency of the prelude, before setting the user supplied value for general queries. This PR instead just sets the user supplied timeout value before checking the prelude.

Set user supplied value when checking the SMT prelude in booster

---

kore/src/Kore/Rewrite/SMT/Translate.hs
test/rpc-server/runTests.py

This is a bridge PR that we need before bumping Z3 to 4.13.0.
- modify `test/rpc-server/runTests.py` to not compare the actual model from `"get-model"` responses, as it may be non-deterministic. Only compare the `"satisfiable"` field, i.e. model existence;
- when back-translating the results of `"get-model"` from SMTLIB2 s-expression to Kore, allow unary minus.

Back-translate the SMTLIB unary minus, ignore models in `"get-model"` tests

---

booster/library/Booster/JsonRpc/Utils.hs
booster/library/Booster/SMT/Interface.hs

Fixes https://github.com/runtimeverification/haskell-backend/issues/4036

Booster: Only check SMT prelude in `initSolver`

---

booster/library/Booster/Definition/Base.hs
booster/library/Booster/Syntax/ParsedKore/Internalise.hs
booster/test/llvm-integration/LLVM.hs
booster/unit-tests/Test/Booster/Fixture.hs

Follow up to #4028, which further cleans up the code-base by removing internalisation of anti-left rules, as these are:
a) unused for over a year now (since #3391)
b) the previous PR essentially left the inernalisation of anti-left broken, but we wanted to remove it fully in a separate PR for ease of review.

Remove support for antiLeft rules and aliases

---

scripts/performance-tests-kevm.sh
scripts/performance-tests-kontrol.sh

Due to recent packaging changes to the blockchain plugin, the KEVM performance script started to fail as it was using libraries provided by brew and not nix on my local machine. The fix is to call `nix develop` with `--ignore-environment`, which purges the path of any non-nix paths. In general it is good practice to do this in any dev shells we call in one of these scripts, as there is less likelihood of similar issues arising.

Pass `--ignore-environment` to nix dev shells in performance scripts

---

booster/library/Booster/CLOptions.hs
dev-tools/booster-dev/Server.hs

This small PR:
- adds `[request ID]` contexts to logs emitted from `booster-dev`, similarly to `kore-rpc-booster`
- the above also makes the per-defined logging contexts `Booster.CLIOptions` useful again, as they did not match before due to the absence of `[request ID]`
- redirects the log messages to a file if asked for
- also lists the available logging formats in `--help`

Fix handling of logging contextx in `booster-dev`

---

dev-tools/package.yaml
dev-tools/pretty/Pretty.hs

The tool was not printing the substitution after internalising a pattern. 
Also switched it to using `Text` to print things and prettified the format a bit (infix printing, indentations).

Make Pretty prettier

---

booster/library/Booster/Syntax/Json/Internalise.hs
booster/library/Booster/Syntax/ParsedKore/Internalise.hs
booster/test/rpc-integration/test-vacuous/README.md
booster/test/rpc-integration/test-vacuous/response-vacuous-but-rewritten.json
booster/test/rpc-integration/test-vacuous/response-vacuous-without-rewrite.json

Booster now recognises predicates of shape `true #Equals (VAR ==Int <expr>)` and `true #Equals (VAR ==K <expr>)` as substitutions (given the global scope does not contradict that, i.e., no cycles or multiple substitutions for the same VAR...).
Currently only matches ==Int and ==K.
We could also match notBool (_ =/=Int _) and notBool (_ =/=K _) (more magic).
When internalising rules and equations, the substitution must be turned back into predicates for the `requires` clause. Currently we also turn back the ensures clause substitutions into predicates (might want to change that).
Part of #4059

Recognise ==Int and ==K equations as substitutions when internalising

---

booster/library/Booster/JsonRpc.hs
booster/library/Booster/Pattern/Rewrite.hs
booster/library/Booster/SMT/Interface.hs
booster/test/rpc-integration/test-substitutions/README.md
booster/test/rpc-integration/test-substitutions/response-circular-equations.booster-dev
booster/test/rpc-integration/test-substitutions/response-symbolic-bottom-predicate.booster-dev
booster/test/rpc-integration/test-substitutions/response-symbolic-bottom-predicate.json

When checking `ensures` conditions of rewrite rules with the SMT solver, we must mark rewrite as trivial if the ground truth is inconsistent. If the SMT solver returns unknown, we must abort rewriting.
Previously, we were swallowing both of there cases and finalizing the rewrite step successfully. This behavior of Booster went undetected for a long time since we would usually abort rewriting or detect a vacuous state at the next step, resulting in wasted work but no unsoundness.
We also tweak the return type of `checkPredicates` to convey addition information why the result is unknown. This will be useful when we start tolerating SMT unknowns and branching on that.

Handle inconsistent ground truth and SMT unknowns when checking `ensures`

---

booster/library/Booster/JsonRpc.hs
booster/library/Booster/Pattern/Rewrite.hs
booster/test/rpc-integration/test-vacuous/README.md
booster/test/rpc-integration/test-vacuous/response-vacuous-but-rewritten.json
booster/test/rpc-integration/test-vacuous/response-vacuous-without-rewrite.json

- before returning a `"simplify"` response, check if any constrains are `false` and return `#Bottom` in that case
- when simplifying rewriting results, prune branches if there's a literal `false`
- this triggers the change in the `test-vacuous` integration test, where the original state is now returned. [simplifyP](https://github.com/runtimeverification/haskell-backend/blob/booster-bottom-on-false-constaint/booster/library/Booster/Pattern/Rewrite.hs#L1029) now returns `Nothing` for the result and thus we get to return `RewriteTrivial` from `performRewrite`
- note that the outdated responses for this integration tests actually had a literal `false` as one of the constraints.

Turn `Pattern` into `#Bottom` if any constraint is literal false

---

booster/library/Booster/Pattern/ApplyEquations.hs

This PR breaks-up new symbolic conjuncts when simplifying a pattern.
It is useful in conjunction K rule:
```
rule [notBool-or]:  notBool ( A  orBool B ) => ( notBool A ) andBool ( notBool B ) [simplification]
```

Break-up new top-level `_andBool_` in `evaluatePattern'`

---

booster/library/Booster/Pattern/Rewrite.hs

When Booster detects an indeterminate `requires`, it adds it to the constraints on the rewritten `Pattern`. However, when we check the `ensures` clause, we only pass the the constraints on the old pattern as known truth. This PR corrects that by adding the uncertain conditions as additional known truth, as the `ensures` check should be performed on the rewritten pattern, not the old one.

Assume the rule remainder condition when checking ensures

---

booster/library/Booster/Pattern/Implies.hs
booster/tools/booster/Proxy.hs

The `logMessage'` function, which emits log messages _unconditionally_, was used for logging some exception conditions in booster. However, these warnings should not appear by default in user-facing output when booster is called through the proxy and just falls back to using kore-rpc.
The changes do not remove the log messages, they are now emitted at context `[proxy]`, which is a common and recommended log setting to see what the server is up to.
Besides changing the `logMessage'` calls, a comment is added to point out where the incompleteness of the `implies` endpoint is rooted in the code.

HOTFIX Make some informative warning logs optional, comment about implies

---

booster/library/Booster/Pattern/Rewrite.hs

When the SMT solver timed out while checking `requires` clauses of a rule, the unclear conditions were returned in the same way as conditions that were known to be indeterminate. This created bogus branches in proofs when the solver had a problem to decide a condition.
On such timeouts, and on inconsistent ground truths, booster now aborts the entire rewrite. This might lead to increased spurious aborts in complex proofs, but is probably better than having to prune the bogus branches from the client side. The fall-back to legacy kore was able to prune the bogus branch easily in the case that was investigated.

HOTFIX abort rewrite when SMT solver times out

---

booster/library/Booster/LLVM/TH.hs
booster/tools/booster/Server.hs
dev-tools/booster-dev/Server.hs
dev-tools/kore-rpc-dev/Server.hs
kore-rpc-types/src/Kore/JsonRpc/Server.hs
kore/src/Kore/JsonRpc.hs

Fixes a problem with recently-introduced thread-local storage in the LLVM backend.
We have to make sure that all foreign calls relating to an LLVM-based term evaluation use the same OS thread, which can only be achieved [via bound threads](https://downloads.haskell.org/ghc/latest/docs/libraries/base-4.20.0.0-1f57/Control-Concurrent.html#g:8) .
This PR
* adds a flag to the generic RPC server in `kore-rpc-types` to run request worker threads in bound threads (using `forkOS`)
* `kore-rpc-booster` uses this flag for bound threads when an LLVM backend library is used
* declares the LLVM backend calls `unsafe` to make executing OS threads block instead of having new OS threads created for concurrent Haskell execution (they won't read HS heap data and never call back into Haskell).
This _should_ …

Hotfix bound threads for workers unsafe calls for llvm

---

flake.lock
flake.nix

This PR updates Z3 to its latest version. It was observed that this version is performing much more efficiently in Kontrol engagement proofs, which require reasoning about complex non-linear arithmetic. 
The improvements in performance are as follows (will be updated as I collect more information):
- SAT checks that would take ~64 seconds in v4.13.0 now take ~3 seconds.

Bump z3 to v4.13.4

---

docs/kore-syntax.md

Reflects the changes of #3666 in `kore-syntax.md`.

Update `kore-syntax.md` with multiary `\and` syntax

---

kore/src/Kore/Builtin/InternalBytes.hs
kore/test/Test/Kore/Builtin/InternalBytes.hs

```
jost@freshcode-1:$ kompile test.k
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
jost@freshcode-1:$ krun -cPGM='Bytes2Int(b"\x00\x80", LE, Signed)'
<k>
-32768 ~> .K
</k>
jost@freshcode-1:$ kompile test.k --backend haskell
[Warning] Compiler: Could not find main syntax module with name TEST-SYNTAX in
definition.  Use --syntax-module to specify one. Using TEST as default.
jost@freshcode-1:$ krun -cPGM='Bytes2Int(b"\x00\x80", LE, Signed)'
<k>
32768 ~> .K
</k>
```
32768 is not representable in 16 bit signed integers.
Root cause was a missing `=` , tests did not catch it because they applied the same (wrong) logic as the conversion itself.

Fix an off-by-one error in the `Bytes2Int` hook

---

booster/library/Booster/Pattern/Implies.hs
booster/library/Booster/Pattern/Match.hs
booster/library/Booster/Pattern/Rewrite.hs
booster/unit-tests/Test/Booster/Pattern/Rewrite.hs
scripts/performance-tests-kontrol.sh

Fixes #4100 
During rewriting, booster was reporting the rule match as "failed" when trying to match a non-variable in the rule to a variable in the subject (introduced by a refactoring mid 2024).
This produces unsound results because the subject variable could be constrained to have a value that would match the rule term, enabling the application of this rule.
The result in `booster` should therefore be `aborted` as long as we don't allow for introducing constraints like this to the rule application.
The new code adds the subject variable to a set of "indeterminate" match pairs. Code has been kept separate so we can later extend the branching mechanism by the collected constraints on subject variables.

4100 booster abort rewrite on subject vars

---

booster/library/Booster/Pattern/Rewrite.hs

The previous change contained some incomplete code that would forward errors from the constraint pre-evaluation to RPC caller. This change is to handle some, and log all other, errors that could arise.

HOTFIX more comments and error handling in constraint pre-evaluation

---

booster/cbits/kllvm-c.h
booster/cbits/stdint.h
booster/hs-backend-booster.cabal
booster/library/Booster/JsonRpc.hs
booster/library/Booster/LLVM.hs
booster/library/Booster/LLVM/Internal.hs
scripts/performance-tests-kontrol.sh

Fixes a problem that surfaced in the `kontrol` upgrade (symptom: server crashes unexpectedly after some iterations).
The LLVM backend was changed to not call `munmap` within `free_all_kore_mem` any more, which makes the `mmap` calls to initialise thread-local heap address space fail after a number of requests.
This is a hot-fix which calls `reset_munmap_all_arenas`, a function not currently included in the LLVM backend C API.
The function will be included in the API once https://github.com/runtimeverification/llvm-backend/pull/1210 is merged, then the header file and the function name should be aligned with the API again.
The backend is _not going to work with older LLVM backends_ because [the function that needs to be called is new as of June …

HOTFIX free after simplify bool, call munmap after each request

---

.github/workflows/test.yml

macos-12 is outdated and is deprecated in public space

Set MacOS CI Runner Version to Latest 
